'use strict';
const ICONS={
 sail:'M5 18h15l-3 3H8z M11 3v14 M13 4l7 10h-7 M9 6l-5 8h5',
 fire:'M13 3c2 5-2 6 1 9 1-2 2-3 3-4 3 4 4 7 1 10-3 4-10 2-11-2-1-4 3-7 4-9 0 3 1 3 1 4',
 house:'M3 11l9-8 9 8 M5 10v11h14V10 M10 21v-7h4v7',tent:'M2 20L12 4l10 16H2 M12 4v16 M12 13l5 7',
 leaf:'M19 3C7 3 3 7 5 13c2 6 13 6 14-10z M4 21l10-11',log:'M5 8l12-4c5 0 6 9 2 10L8 18 M8 18c-4 1-6-8-3-10 4-1 7 8 3 10 M6 11c2-1 4 4 2 4',
 axe:'M5 21L16 4 M10 7l4-4 7 5-4 6-7-7',bow:'M6 3c15 4 15 14 0 18 M6 3l5 9-5 9 M3 12h18 M18 9l3 3-3 3',
 fish:'M3 12l4-5c6-5 12 0 14 5-2 5-8 10-14 5l-4-5z M3 12l-1-4 5 2 M3 12l-1 4 5-2 M16 10h.01',
 food:'M4 8h16v4c0 5-16 5-16 0V8z M3 8h18 M8 5V3 M12 5V2 M16 5V3 M7 20h10',
 basket:'M3 9h18l-2 11H5L3 9z M7 9l5-7 5 7 M9 13v4 M15 13v4',sprout:'M12 21v-9 M12 14C4 14 3 8 3 6c7 0 10 4 9 8 M12 10c0-7 5-8 9-8 0 6-3 10-9 8',
 stone:'M4 8l6-5 8 2 4 8-6 8-11-2-3-6 2-5z M4 8l8 3 6-6 M12 11l4 10',water:'M12 3C9 8 5 12 5 15a7 7 0 0014 0c0-3-4-7-7-12 M8 15c0 2 2 4 4 4',
 spark:'M12 2l2 7 7 3-7 2-2 8-3-8-7-2 7-3 3-7z',tools:'M14 3c-3 0-4 3-3 5l-8 9 4 4 8-9c5 2 9-4 5-8l-3 4-3-3 3-3z',
 people:'M8 11a4 4 0 100-8 4 4 0 000 8 M1 21v-3c0-6 14-6 14 0v3 M17 4c5 1 5 7 0 8 M17 15c5 0 6 2 6 6',
 heart:'M12 21C-6 9 6-3 12 6c6-9 18 3 0 15z',book:'M12 5C8 2 4 3 2 4v16c4-2 7-1 10 1 3-2 7-3 10-1V4c-3-1-6-2-10 1v16',
 beacon:'M8 21l2-11h4l2 11 M8 10h8V5H8v5 M7 5l5-3 5 3 M4 8H1 M23 8h-3',
 rope:'M7 16c-6-5 0-13 6-10l5 3c6 4 0 12-6 8l-6-4c-2-2 1-5 3-4l8 5',
 lantern:'M8 8h8v11H8z M7 8l5-5 5 5 M12 3V1 M7 19h10 M12 11v5',bench:'M3 13h18v3H3z M5 16v5 M19 16v5 M4 5h16v5H4z M6 10v3 M18 10v3',
 compass:'M12 2a10 10 0 110 20 10 10 0 010-20 M16 7l-3 7-6 3 3-7 6-3z',
 arrow:'M4 12h16 M15 7l5 5-5 5',plus:'M12 5v14 M5 12h14',minus:'M5 12h14',close:'M6 6l12 12 M18 6L6 18',
 pause:'M8 5v14 M16 5v14',play:'M8 4l12 8-12 8V4z',rotate:'M20 7a9 9 0 10-1 12 M20 2v5h-5',
 menu:'M5 6h14 M5 12h14 M5 18h14',eye:'M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12 M12 9a3 3 0 110 6 3 3 0 010-6',
 sound:'M3 9h4l5-5v16l-5-5H3V9 M16 7c4 3 4 7 0 10 M19 4c6 5 6 11 0 16',
 path:'M4 22c-8-8 16-6 8-13C7 5 13 2 19 2 M10 22c-9-5 14-8 7-14',check:'M4 12l5 5L20 6',lock:'M5 10h14v11H5V10 M8 10V6a4 4 0 018 0v4',save:'M5 3h12l4 4v14H3V3h2 M7 3v6h10V3 M7 21v-8h10v8'
};
const ico=(name,cls='')=>`<svg class="ico ${cls}" viewBox="0 0 24 24" aria-hidden="true"><path d="${ICONS[name]||ICONS.leaf}"/></svg>`;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const $=s=>document.querySelector(s);
const SAVEKEY='tidefolk.firsthearth.v1';
let sim,view;
const UI={panel:null,category:'All',techCategory:'All',showLocked:false,selected:null,ghost:null,pathMode:false,wasRunning:false,lastPaint:0,lastPanel:0,toastUntil:0,saveAt:0,endShown:false,storageOK:true,sound:null};
function icons(){document.querySelectorAll('[data-icon]').forEach(e=>{e.innerHTML=ico(e.dataset.icon);e.removeAttribute('data-icon');});}
function avatar(p,large=false){return `<div class="avatar ${large?'large':''}" style="--shirt:${p.color};--skin:${p.skin}"></div>`;}
function costHTML(cost){return `<div class="cost">${Object.entries(cost).map(([k,v])=>`<span class="${sim.s.stock[k]<v?'missing':''}">${ico(GOODS[k][1])}${v} ${esc(GOODS[k][0])}</span>`).join('')}</div>`;}
function safeLoad(){try{let raw=localStorage.getItem(SAVEKEY);if(!raw)return null;let data=TideSim.validate(JSON.parse(raw));if(data.version===1&&!localStorage.getItem(SAVEKEY+'.backup-v1'))localStorage.setItem(SAVEKEY+'.backup-v1',raw);return data;}catch(e){UI.storageOK=false;return null;}}
function save(){if(!sim||!sim.s.started||sim.s.demo)return;try{localStorage.setItem(SAVEKEY,JSON.stringify(sim.toJSON()));UI.storageOK=true;}catch(e){UI.storageOK=false;}}
function setupSim(s){sim=s;sim.onEvent=e=>{showToast(e.title,e.text,e.icon);if(UI.sound)UI.sound.note();};view?.visualPeople.clear();UI.endShown=false;}
function showToast(title,text,icon='leaf'){if(!sim?.s.started)return;$('#toast').innerHTML=ico(icon)+`<div><strong>${esc(title)}</strong><small>${esc(text)}</small></div>`;$('#toast').classList.add('show');UI.toastUntil=performance.now()+4500;}
function error(msg){if(msg)showToast('A little thing first',msg,'leaf');}
function modal(html){$('#modal').hidden=false;$('#modal').innerHTML=html;sim.s.paused=true;icons();}
function hideModal(){ $('#modal').hidden=true;}
function welcome(){closePanel(false);UI.ghost=null;UI.pathMode=false;$('#placement').hidden=true;let saved=safeLoad();modal(`<div class="welcome"><div class="logoicon">${ico('sail')}</div><div class="eyebrow">Chapter one · the first hearth</div><h1>Tidefolk</h1><div class="subtitle">An island to discover. A life together.</div><p>Four castaways reach an unfamiliar shore.<br>Build a fire. Give them a home.<br>Discover what a small community can become.</p>${saved?`<button class="primary" data-act="continue">Continue your story ${ico('arrow')}</button><button class="secondary" data-act="newconfirm">Begin a new story</button>`:`<button class="primary" data-act="begin">Begin your story ${ico('arrow')}</button>`}<button class="secondary" data-act="demo">Visit a thriving island</button><div class="smallprint">A playable concept · Touch & mouse<br>Slower days · Uncharted trails · Saved on this device</div></div>`);}
function startFresh(){setupSim(new TideSim());sim.s.started=true;sim.s.paused=false;UI.selected=null;view.cx=0;view.cz=0;view.zoom=1;hideModal();save();showToast('The first shore','Tap the wreck to recover supplies. Take your time; your people are safe.','compass');}
function openPanel(kind,id=null){$('#toast').classList.remove('show');if(!UI.panel){UI.wasRunning=!sim.s.paused;sim.s.paused=true;}UI.panel={kind,id};UI.ghost=null;UI.pathMode=false;$('#placement').hidden=true;$('#panel').hidden=false;renderPanel();}
function closePanel(resume=true){$('#panel').hidden=true;if(UI.panel&&resume&&UI.wasRunning)sim.s.paused=false;UI.panel=null;document.querySelectorAll('.navbtn').forEach(b=>b.classList.remove('active'));}
function preview(type){if(!UI.panel)UI.wasRunning=!sim.s.paused;sim.s.paused=true;closePanel(false);UI.pathMode=false;UI.ghost={type,x:view.cx,z:view.cz+3,rot:0};UI.selected=null;$('#placement').hidden=false;paintPlacement();}
function paintPlacement(){if(UI.pathMode){$('#placement').innerHTML=`<h3>A path through the island</h3><p>Draw with your finger. Villagers prefer these routes.</p><button class="primary" data-act="endpath">Done drawing</button>`;return;}let b=UI.ghost;if(!b)return;let d=BUILD[b.type],msg=sim.placement(b.type,b.x,b.z,b.moveId)||(!b.moveId&&!sim.canPay(d.cost)?'Need '+sim.missing(d.cost):'');$('#placement').innerHTML=`<h3>${d.name}</h3><p>Tap the ground to position. Drag to move the view.</p>${b.moveId?'<div class="note">Relocation is free in this concept build. People keep their homes and jobs.</div>':costHTML(d.cost)}<div class="error">${esc(msg||'A good place to begin.')}</div><div class="actions"><button class="secondary" data-act="cancelplace" aria-label="Cancel placement">${ico('close')}</button><button class="secondary" data-act="turnplace" aria-label="Rotate building">${ico('rotate')}</button><button class="primary" data-act="place" ${msg?'disabled':''}>${b.moveId?'Move here':'Build here'} ${ico('check')}</button></div>`;}
function nodePanel(n){if(!n)return '<p>Nothing here yet.</p>';if(!sim.knownAt(n.x,n.z))return regionPanel(regionAt(n.x,n.z));if(n.kind==='cache')return `<div class="card-art">${ico(n.icon)}</div><p>${esc(n.desc)}</p><div class="note">${n.left>0?`${n.amount} ${esc(GOODS[n.resource][0].toLowerCase())} per trip · ${n.left} trips remaining. Supplies arrive only when the gatherer returns home.`:'This patch is exhausted. There may be more supplies elsewhere on the island.'}</div><button class="primary" data-act="investigate:${n.id}" ${n.left<=0?'disabled':''}>Gather supplies ${ico('basket')}</button><button class="secondary" data-act="focusnode:${n.id}">Show on island</button>`;let shared=!!sim.s.flags[n.id];return `<div class="card-art">${ico(n.icon)}</div><p>${esc(n.desc)}</p>${n.kind==='discover'?`<div class="note">${n.found?(shared?'The community shared this discovery at the Hearth.':'Discovered. The knowledge will be shared at the next evening Hearth.'):'Choose an available adult to investigate. The discovery belongs to the whole community.'}</div>`:`<div class="note">${n.id==='wreck'?'Each trip recovers wood and thatch. The first trip also saves a sailcloth set for your future boat.':'An island resource. Mark it for gathering and a free person will come.'}</div>`}${!n.found?`<button class="primary" data-act="investigate:${n.id}" ${n.left===0?'disabled':''}>${n.kind==='discover'?'Send someone to explore':'Gather supplies'} ${ico('arrow')}</button>`:''}${n.id==='spring'&&shared?'<p>Citizens can fetch drinking water here. A Water Station will make their workday easier.</p>':''}${n.id==='copper'&&shared?`<div class="row"><span>Accessible copper</span><strong>${Math.floor(sim.s.oreLeft??40)} ore</strong></div>`:''}`;}
function buildPanel(){let cats=['All','Home','Work','Food','Community','Seafaring','Details'];return `<div class="tabs">${cats.map(c=>`<button class="chip ${UI.category===c?'active':''}" data-act="category:${c}">${c==='Seafaring'?'Sea':c}</button>`).join('')}</div><button class="secondary" style="margin:0 0 14px" data-act="path">${ico('path')} Draw a dirt path</button><div class="cards">${Object.entries(BUILD).filter(([id,d])=>(UI.category==='All'||d.category===UI.category)&&(UI.showLocked||sim.learned(d.tech))).map(([id,d])=>{let locked=!sim.learned(d.tech),exists=d.unique&&sim.buildings.some(b=>b.type===id);return `<button class="build-card ${locked||exists?'locked':''}" data-act="${locked?'needtech:'+d.tech:exists?'nothing':'preview:'+id}"><div class="card-art">${ico(d.icon)}</div><h3>${d.name}</h3><small>${exists?'Already part of our island':locked?`Learn ${TECH[d.tech].name}`:`${Object.entries(d.cost).map(([k,v])=>v+' '+GOODS[k][0].toLowerCase()).join(' · ')}`}</small></button>`;}).join('')}</div><button class="secondary" data-act="togglelocked">${UI.showLocked?'Hide future ideas':'See what we could build'}</button><p class="smallprint">Materials are reserved when placed. Available villagers build and haul; assigned workers keep their day jobs. Plans can be cancelled for a full refund.</p>`;}
function personList(){return `${sim.s.pendingArrival?`<div class="note"><strong>${esc(sim.s.pendingArrival.first)} is waiting on the beach.</strong><br>Someone saw a chance for a new beginning.<button class="primary" style="margin-top:10px" data-act="welcome">Welcome them to the island</button></div>`:''}<p>Every person has a home, a calling, and a story. Tap someone to get to know them.</p>${sim.people.map(p=>`<button class="item" style="width:100%;text-align:left" data-act="person:${p.id}">${avatar(p)}<div class="item-main"><strong>${esc(p.first+' '+p.last)}</strong><small>${esc(p.profession)} · ${sim.life(p)}${p.pregnantUntil?' · Expecting':''}</small></div>${ico('arrow')}</button>`).join('')}<div class="note">Newcomers arrive on the beach. A Signal Fire attracts more people. Homes create space for households.</div>`;}
function personPanel(p){if(!p)return '<p>Person not found.</p>';let skills=Object.keys(SKILL_NAMES).sort((a,b)=>sim.skill(p,b)-sim.skill(p,a));let mate=sim.people.find(q=>q.id===p.partner),home=sim.getB(p.home);return `<div class="person-hero">${avatar(p,true)}<div><h3>${esc(p.first+' '+p.last)}</h3><small>${sim.age(p)<1?'Under one year':Math.floor(sim.age(p))+' years'} · ${sim.life(p)}<br>${esc(p.profession)}</small></div></div><div class="status">${esc(p.status)} · ${p.well>=80?'Doing well':p.well>=60?'Needs a little care':'Feeling strained'}</div>${p.pregnantUntil?`<div class="note">A child is expected in ${p.pregnantUntil-sim.day} days. ${esc(p.first)} does not work during pregnancy. Assign another person to cover the role.</div>`:''}<div class="row"><span>Home</span><strong>${home?esc(sim.buildingName(home)):'No bed assigned'}</strong></div>${mate?`<div class="row"><span>${p.married?'Married to':'Partner'}</span><button class="linkbtn" data-act="person:${mate.id}">${esc(mate.first)}</button></div>`:''}
 <label for="person-job">A role in the community</label><select id="person-job" data-change="job:${p.id}" ${!sim.available(p)?'disabled':''}><option value="" ${!p.job?'selected':''}>General work & helping around camp</option><option value="builder" ${p.job==='builder'?'selected':''}>Builder · focus on construction</option>${sim.buildings.filter(b=>b.built&&BUILD[b.type].skill).map(b=>`<option value="${b.id}" ${p.job===b.id?'selected':''}>${sim.buildingName(b)}${sim.people.some(q=>q.job===b.id&&q.id!==p.id)?' · replace current worker':''}</option>`).join('')}</select><p class="smallprint">Skills stay with a person when their job changes. Paused workplaces free people to help with other work.</p><div class="section-title">What ${esc(p.first)} has learned</div>${skills.slice(0,7).map(k=>{let n=sim.skill(p,k);return `<div class="skill"><div><span>${SKILL_NAMES[k]}</span><small>${n.toFixed(1)} · ${sim.rank(p,k)}</small></div><div class="progressline"><i style="width:${n*10}%"></i></div></div>`;}).join('')}<div class="section-title">A life on the island</div>${p.history.slice(0,12).map(e=>`<div class="entry"><time>Day ${e.day}</time><h4>${esc(e.text)}</h4></div>`).join('')}<button class="secondary" data-act="follow:${p.id}">${ico('eye')} Find ${esc(p.first)} on the island</button>`;}
function buildingPanel(b){if(!b)return '<p>Nothing here yet.</p>';let d=BUILD[b.type],worker=sim.people.find(p=>p.job===b.id),up=d.up;let html=`<div class="card-art">${ico(d.icon)}</div><p>${esc(d.desc)}</p>`;
 if(!b.built)return html+`<div class="row"><span>Under construction</span><strong>${Math.round(b.progress/d.labor*100)}%</strong></div><div class="progressline"><i style="width:${b.progress/d.labor*100}%"></i></div><p class="note">Reserved materials are already paid. Unassigned villagers and Builders work on this plan. Close the panel to let them continue.</p><button class="secondary danger" data-act="cancelbuild:${b.id}">Cancel plan & return materials</button>`;
 if(d.skill){html+=`<div class="section-title">Daily work</div><label>Assigned person</label><select data-change="worker:${b.id}"><option value="">No permanent worker</option>${sim.adults.map(p=>`<option value="${p.id}" ${worker?.id===p.id?'selected':''} ${!sim.available(p)?'disabled':''}>${esc(p.first)} · ${SKILL_NAMES[d.skill]} ${sim.skill(p,d.skill).toFixed(1)}${!sim.available(p)?' · unavailable':''}</option>`).join('')}</select>${worker?`<button class="item" style="width:100%;text-align:left" data-act="person:${worker.id}">${avatar(worker)}<div class="item-main"><strong>${esc(worker.first)}</strong><small>${esc(worker.status)}</small></div>${ico('arrow')}</button>`:'<div class="note">No one works here yet. Choose a person above.</div>'}<button class="secondary" data-act="workpause:${b.id}">${b.paused?'Resume this workplace':'Pause this workplace'}</button>`;}
 if(b.type==='workshop')html+=`<label>Make at this Workshop</label><select data-change="recipe:${b.id}">${['planks','rope','tools'].map(k=>`<option value="${k}" ${b.recipe===k?'selected':''}>${RECIPES[k].name}</option>`).join('')}</select>${costHTML(RECIPES[b.recipe].cost)}<p class="smallprint">One batch at a time. Crafting pauses when materials run out or storage is full. Toolmaking keeps six copper fittings aside for the first vessel.</p>`;
 if(b.type==='quarry')html+=`<label>Work the outcrop</label><select data-change="quarry:${b.id}"><option value="stone" ${b.mode==='stone'?'selected':''}>Quarry stone</option><option value="copper" ${b.mode==='copper'?'selected':''} ${sim.learned('copperwork')?'':'disabled'}>Mine copper · ${Math.floor(sim.s.oreLeft??40)} ore left</option></select>`;
 if(b.type==='field')html+=`<div class="row"><span>${sim.season===3?'Resting for winter':'Growing toward harvest'}</span><strong>${Math.round(b.growth/14*100)}%</strong></div><div class="progressline"><i style="width:${b.growth/14*100}%"></i></div><p class="smallprint">A farmer tends once a day, harvests when ready, and helps the camp between visits. Replanting seed is kept aside.</p>`;
 if(b.type==='smoker')html+=costHTML(RECIPES.preserve.cost)+`<p class="smallprint">Makes 4 preserved food per batch. Fresh food is eaten first.</p>`;
 if(b.type==='house'||b.type==='shelter'){let members=sim.occupancy(b);html+=`<div class="section-title">${b.type==='house'?'Our household':'Temporary shelter'} · ${members.length}/${sim.beds(b)} beds${sim.reservedBeds(b)?' · 1 reserved for baby':''}</div>${members.map(p=>`<button class="item" style="width:100%;text-align:left" data-act="person:${p.id}">${avatar(p)}<div class="item-main"><strong>${esc(p.first)}</strong><small>${sim.life(p)} · ${esc(p.profession)}</small></div>${ico('arrow')}</button>`).join('')}`;
 if(sim.freeBeds(b)>0)html+=`<label>Move someone here</label><select data-change="home:${b.id}"><option value="">Choose a person</option>${sim.people.filter(p=>p.home!==b.id).map(p=>`<option value="${p.id}">${esc(p.first+' '+p.last)}</option>`).join('')}</select>`;
 if(b.type==='house'){html+=`<div class="section-title">Family plans</div><p class="smallprint">Adult housemates grow close over shared evenings. An eligible couple needs a spare bed, good health, and food security. Pregnancy takes 90 days and pauses the mother's work.</p><button class="secondary" data-act="family:${b.id}">${ico('heart')} ${b.family?'Open to a child · tap to wait':'Wait for now · tap to open family plans'}</button>`;}}
 if(b.type==='hearth')html+='<button class="primary" data-act="knowledge">Gather our ideas</button>';
 if(b.type==='boatyard')html+='<button class="primary" data-act="voyage">The first voyage</button>';
 html+=`<button class="secondary" data-act="relocate:${b.id}">${ico('rotate')} Move this building</button>`;
 if(up&&!b.up)html+=`<div class="section-title">A little more possibility</div><h3 style="font:21px var(--serif);margin:4px 0">${up.name}</h3><p class="smallprint">${up.desc}</p>${costHTML(up.cost)}<button class="primary" data-act="upgrade:${b.id}" ${sim.learned(up.tech)&&sim.canPay(up.cost)?'':'disabled'}>${sim.learned(up.tech)?'Improve this place':'Learn '+TECH[up.tech].name}</button>`;
 return html;
}
function knowledgePanel(){let cats=['All','Home','Food','Craft','Community','Stewardship','Seafaring'];let html=`<div class="row"><span>${ico('spark')} Shared insight</span><strong>${sim.s.insight}<small style="font-weight:400;color:#939680"> + ${sim.s.pendingInsight} to share</small></strong></div><p>People discover. The community remembers.<br>Bring new ideas to the fire after sunset.</p>${!sim.night?`<button class="secondary" data-act="meet" ${sim.has('hearth')?'':'disabled'}>${ico('fire')} Gather at the Hearth tonight</button><p class="smallprint">Advances the actual simulation to this evening; people keep working and using supplies.</p>`:''}<div class="tabs" style="margin-top:14px">${cats.map(c=>`<button class="chip ${c===UI.techCategory?'active':''}" data-act="techcat:${c}">${c==='Seafaring'?'Sea':c}</button>`).join('')}</div>`;
 let entries=Object.entries(TECH).filter(([k,t])=>UI.techCategory==='All'||t.branch===UI.techCategory);entries.sort((a,b)=>Number(sim.learned(a[0]))-Number(sim.learned(b[0])));
 for(let[id,t]of entries){let known=sim.learned(id),err=known?'':sim.researchReason(id);html+=`<div class="tech ${known?'known':''}"><div class="row"><h3>${t.name}</h3><span class="badge">${known?'Learned ✓':ico('spark')+' '+t.cost}</span></div><p>${t.desc}</p>${known?'':`<p class="smallprint">${esc(err||'Ready to share with the community.')}</p><button class="primary" data-act="research:${id}" ${err?'disabled':''}>Learn ${ico('arrow')}</button>`}</div>`;}
 return html;
}
function supplyPanel(){let need=sim.foodDemand(),winterFood=sim.people.reduce((n,p)=>{let b=sim.getB(p.job);return n+(sim.available(p)&&b?.built?(b.type==='hunt'?2.5*.8:b.type==='fish'?(b.up?3.5:2.5)*.75:0):0);},0),reserve=Math.ceil(30*Math.max(0,need-winterFood)*1.2);return `<div class="row"><span>People to feed</span><strong>${need.toFixed(1)} food / day</strong></div><div class="row"><span>Meals in reserve</span><strong>${(sim.food/Math.max(1,need)).toFixed(1)} days</strong></div><div class="stock-grid">${Object.entries(GOODS).map(([k,[name,icon]])=>`<div class="stock">${ico(icon)}<div><strong>${Math.floor(sim.s.stock[k]*10)/10}</strong><small>${name}</small></div></div>`).join('')}</div><div class="section-title">The next winter</div><div class="note">Estimated preserved food target: <strong>${reserve}</strong><br>Based on 30 days, the people here, and a cautious estimate for staffed hunting and fishing. It is a planning estimate, not guaranteed output.</div><div class="row"><span>Storage used</span><strong>${Math.floor(sim.usedStorage())} / ${sim.stockCap()}</strong></div>${sim.learned('planning')?`<div class="section-title">Our stock targets</div>${[['wood','Wood'],['fresh','Fresh food'],['food','Preserved food']].map(([k,n])=>`<label>${n}</label><input type="number" min="5" max="300" value="${sim.s.policies[k]}" data-change="target:${k}">`).join('')}`:`<p class="smallprint">Shared Responsibility unlocks editable stock targets. Work is already repeatable; targets tell your people when they have enough.</p>`}<p class="smallprint">This is prototype balancing. Fresh food lasts 6 days, or 9 in a Storehouse. Water access and food shortages reduce wellbeing before any other consequence. There is no random death in this build.</p>`;}
function journalPanel(){return `<div class="tabs"><button class="chip active" data-act="journal">Our story</button><button class="chip" data-act="goals">Community goals</button></div>${sim.s.logs.map(e=>`<div class="entry"><time>Year ${Math.floor((e.day-1)/120)+1} · ${BALANCE.seasonNames[Math.floor((e.day-1)/30)%4]} ${((e.day-1)%30)+1}</time><h4>${esc(e.title)}</h4><p>${esc(e.text)}</p></div>`).join('')}`;}
function goalsPanel(){return GOALS.map(g=>`<div class="tech ${g.test(sim)?'known':''}"><div class="row"><h3>${g.title}</h3><span class="badge">${g.test(sim)?'✓':ico('spark')+' '+g.reward}</span></div><p>${g.desc}</p>${!g.test(sim)?`<button class="secondary" data-act="goal:${g.id}">${g.label} ${ico('arrow')}</button>`:''}</div>`).join('');}
function voyagePanel(){let boat=sim.s.boat,stage=boat.stage;return `<div class="card-art">${ico('sail')}</div><h3 style="font:24px var(--serif);margin:10px 0">What lies beyond home?</h3><p>The first boat is the work of an entire community. A builder becomes a shipwright. A fisher learns the sea. A harvest becomes provisions.</p>${!sim.has('boatyard')?`<div class="note">Discover the lookout and copper outcrop. Learn Carpentry, Copperworking, Shorecraft, Navigation and Preservation, then Boatbuilding.</div><button class="primary" data-act="knowledge">Visit the Hearth</button><button class="secondary" data-act="preview:boatyard" ${sim.learned('boatbuilding')?'':'disabled'}>Place a Boatyard</button>`:''}${stage==='none'&&sim.has('boatyard')?`<div class="section-title">Lay the keel</div>${costHTML(BOAT_COST)}<div class="note">A builder needs Construction 3 and Carpentry 2. The project takes 12 shipwright labour-days; work and travel determine its actual duration.</div><button class="primary" data-act="startboat">Begin the vessel</button>`:''}${stage==='building'?`<div class="row"><span>Keel → hull → rigging → sail</span><strong>${Math.floor(boat.progress/BALANCE.boatWork*100)}%</strong></div><div class="progressline"><i style="width:${boat.progress/BALANCE.boatWork*100}%"></i></div><p class="note">Your shipwright is working at the Boatyard. Keep food and water secure while the vessel takes shape.</p>`:''}${stage==='ready'?`<div class="section-title">A name for our vessel</div><input id="boatname" type="text" maxlength="32" value="${esc(boat.name)}" data-change="boatname"><div class="section-title">Two people for the first voyage</div>${sim.adults.filter(p=>sim.available(p)).map(p=>`<div class="crew"><input type="checkbox" id="crew-${p.id}" name="crew" value="${p.id}"><label for="crew-${p.id}">${esc(p.first+' '+p.last)}<small>${p.profession} · Seamanship ${sim.skill(p,'seamanship').toFixed(1)}</small></label></div>`).join('')}<p class="smallprint">One person needs Seamanship 1. Leave at least three working adults behind. Crew members stop doing their jobs at home.</p><div class="section-title">Supplies for the crossing</div>${costHTML(VOYAGE_COST)}<button class="primary" data-act="launch">Set sail ${ico('sail')}</button>`:''}${stage==='sailing'?`<div class="note">${esc(boat.name)} is following the horizon. The voyage takes two game days.</div><button class="primary" data-act="watchboat">Watch the voyage</button>`:''}${stage==='arrived'?`<div class="note"><strong>A new shore.</strong><br>Your people reached the second island. This prototype ends at discovery; settlement and trade between islands are the next chapter.</div><button class="primary" data-act="ending">Remember the first voyage</button>`:''}`;}
function settingsPanel(){return `<p><strong>Tidefolk · Beyond the Familiar Shore</strong><br>Playable concept v0.2.0</p><label for="daypace">How long should a day feel?</label><select id="daypace" data-change="daypace">${[[360,'Gentle — 6 minutes'],[600,'Unhurried — 10 minutes'],[900,'Leisurely — 15 minutes']].map(([v,n])=>`<option value="${v}" ${sim.daySeconds===v?'selected':''}>${n}</option>`).join('')}</select><div class="note">At 1×, a full day lasts ${sim.daySeconds/60} real minutes. Use 2× or 4× when you choose. Dawn, daylight and dusk blend gradually. Seasons still last 30 days, and planning pauses the clock.</div><button class="primary" data-act="save">${ico('save')} Save our story</button><button class="secondary" data-act="export">Export save file</button><button class="secondary" data-act="import">Import a save file</button><button class="secondary" data-act="mainmenu">Main menu</button><button class="secondary danger" data-act="newconfirm">Start again</button><div class="section-title">A larger island</div><p>Explore five new areas beyond the home shore. A named adult walks the trail, surveys the land, and opens it to gathering and construction. Resources must still be carried home.</p><p class="smallprint">Existing 0.1 saves are upgraded without removing people or buildings. Exported saves now use version 2; older builds cannot read them. An original version-1 browser save is backed up locally before upgrading.</p><p class="smallprint">No offline decay or cloud save. Island Two remains a discovery endpoint. ${UI.storageOK?'Your story is saved in this browser. Keep an exported backup.':'Browser saving is unavailable: export your story before leaving.'}</p>`;}
function islandChart(){
 const pts=Array.from({length:90},(_,i)=>{let a=i/90*Math.PI*2;return `${100+Math.cos(a)*radiusAt(a)*2},${117+Math.sin(a)*radiusAt(a)*.82*2}`;}).join(' ');
 return `<div class="island-chart"><svg viewBox="0 0 200 151" role="img" aria-label="Island chart showing six regions from the southern home shore to the far northern headland"><polygon points="${pts}" fill="#e2d4b5" stroke="#f5eddb" stroke-width="3"/>${REGIONS.map(r=>{let known=sim.explored(r.id),x=100+r.x*2,y=117+r.z*2;return `<g data-act="region:${r.id}" style="cursor:pointer" role="button" aria-label="${r.name}"><circle cx="${x}" cy="${y}" r="${r.id==='home'?18:15}" fill="${known?r.color:'#c7d0c7'}" opacity=".8"/><text x="${x}" y="${y+3}" text-anchor="middle" font-size="8" fill="#405d55">${known?'✓':'?'}</text></g>`;}).join('')}<text x="100" y="13" text-anchor="middle" font-size="6" letter-spacing="2" fill="#567e7a">NORTH</text></svg><span>First Light Island · ${sim.s.world.explored.length} / ${REGIONS.length} areas explored</span></div>`;
}
function explorePanel(){return `<p>The beach is only the beginning. Choose an uncharted area to send a scout.</p>${islandChart()}<button class="secondary" data-act="overview">${ico('compass')} See the whole island</button><div class="region-list">${[...REGIONS.slice(1),REGIONS[0]].map(r=>{let known=sim.explored(r.id),scout=sim.scoutFor(r.id),ready=r.requires.every(id=>sim.explored(id));return `<button class="region-card" data-act="region:${r.id}"><span class="region-icon" style="background:${r.color}">${ico(known?r.icon:scout?'people':'compass')}</span><span><strong>${r.name}</strong><small>${known?'Explored · inspect resources':scout?`${esc(scout.first)} is on the trail`:ready?'Unexplored · send a scout':'Beyond the next trail'}</small></span><span>${ico(known?'check':'arrow')}</span></button>`;}).join('')}</div>`;}
function regionPanel(id){let r=sim.region(id);if(!r)return '<p>No such trail.</p>';let known=sim.explored(id),scout=sim.scoutFor(id),reason=sim.scoutReason(id);let nodes=sim.s.world.nodes.filter(n=>regionAt(n.x,n.z)===id);let who=sim.s.world.explorationLog?.find(q=>q.region===id);return `<div class="card-art">${ico(r.icon)}</div><p>${esc(r.hint)}</p>${known?`<div class="note">${who?`${esc(who.name)} opened this trail on Day ${who.day}.`:'This is the shore where our story began.'} You can gather supplies and place buildings here.</div><button class="primary" data-act="focusregion:${id}">Visit ${r.name} ${ico('compass')}</button><div class="section-title">Resources & landmarks</div>${nodes.map(n=>`<button class="region-card" data-act="node:${n.id}"><span>${ico(n.icon)}</span><span><strong>${esc(n.name)}</strong><small>${n.kind==='cache'?`${n.left} gathering trips left`:n.found?'Discovered':'Inspect this place'}</small></span>${ico('arrow')}</button>`).join('')}<p class="smallprint">${sim.s.world.trees.filter(t=>t.wood>0&&regionAt(t.x,t.z)===id).length} mature trees in this area.</p>`:scout?`<div class="note">${esc(scout.first)}: ${esc(scout.status)}. Scouts rest at night and resume the trail in the morning.</div><button class="primary" data-act="watchscout:${id}">Follow ${esc(scout.first)}</button><button class="secondary" data-act="cancelscout:${id}">Recall scout</button>`:`<div class="note">A scout must walk here and survey the area before its resources are revealed. This does not spend materials or grant instant supplies.</div><button class="primary" data-act="scout:${id}" ${reason?'disabled':''}>Explore this area ${ico('compass')}</button>${reason?`<p class="smallprint">${esc(reason)}</p>`:''}`}<button class="secondary" data-act="explore">All island areas</button>`;}

function renderPanel(){if(!UI.panel)return;let {kind,id}=UI.panel,body='',title='',kicker='The little things that become a life';
 if(kind==='build'){title='Make a place';body=buildPanel();kicker='Built by hand';}if(kind==='people'){title='Our people';body=personList();kicker=sim.people.length+' lives on this island';}
 if(kind==='person'){let p=sim.people.find(p=>p.id===id);title=p?.first||'A life';body=personPanel(p);kicker='A person, not a number';}
 if(kind==='building'){let b=sim.getB(id);title=b?sim.buildingName(b):'A place';body=buildingPanel(b);kicker=b?.built?'A part of our home':'Taking shape';}
 if(kind==='node'){let n=sim.s.world.nodes.find(n=>n.id===id);title=n?.name||'The island';body=nodePanel(n);kicker='The island has something to teach us';}
 if(kind==='knowledge'){title='Around the Hearth';body=knowledgePanel();kicker=sim.night?'The evening council':'Ideas for tonight';}
 if(kind==='supplies'){title='What sustains us';body=supplyPanel();kicker='A little foresight goes a long way';}if(kind==='journal'){title='Our island story';body=journalPanel();kicker='Remember how it all began';}
 if(kind==='explore'){title='Beyond the familiar shore';body=explorePanel();kicker='Explore First Light Island';}if(kind==='region'){title=sim.region(id)?.name||'The island';body=regionPanel(id);kicker='One island, many discoveries';}
 if(kind==='goals'){title='Things worth doing';body=goalsPanel();kicker='Community goals';}if(kind==='voyage'){title='The first voyage';body=voyagePanel();kicker='Beyond the familiar shore';}if(kind==='settings'){title='A moment to pause';body=settingsPanel();kicker='Tidefolk · concept build';}
 $('#panel-title').textContent=title;$('#panel-kicker').textContent=kicker;let scroll=$('#panel-body').scrollTop;$('#panel-body').innerHTML=body;$('#panel-body').scrollTop=scroll;document.querySelectorAll('.navbtn').forEach(b=>b.classList.toggle('active',b.dataset.act===kind));icons();
}
function goalAction(id){let g=GOALS.find(g=>g.id===id);if(!g)return;let a=g.action;
 if(a==='opening'){if(!sim.has('shelter'))preview('shelter');else{UI.selected={kind:'node',id:'spring'};openPanel('node','spring');}}else if(a==='seeds'){if(!sim.s.flags.seeds){UI.selected={kind:'node',id:'seeds'};openPanel('node','seeds');}else if(!sim.learned('agriculture'))openPanel('knowledge');else preview('field');}
 else if(a==='fish'){if(!sim.s.flags.fishing)openPanel('node','fishing');else if(!sim.learned('fishing'))openPanel('knowledge');else preview('fish');}
 else if(a.startsWith('node:')){let nid=a.split(':')[1];UI.selected={kind:'node',id:nid};openPanel('node',nid);}else if(a.startsWith('build:'))preview(a.split(':')[1]);else openPanel(a);
}
// Preserve live touch targets across HUD updates, including moving map markers.
function patchTree(target, source){
 const incoming=Array.from(source.childNodes);
 incoming.forEach((next,i)=>{
  const old=target.childNodes[i];
  if(!old){target.appendChild(next.cloneNode(true));return;}
  if(old.nodeType!==next.nodeType||old.nodeName!==next.nodeName){old.replaceWith(next.cloneNode(true));return;}
  if(next.nodeType===3){if(old.nodeValue!==next.nodeValue)old.nodeValue=next.nodeValue;return;}
  if(next.nodeType===1){patchAttributes(old,next);patchTree(old,next);}
 });
 while(target.childNodes.length>incoming.length)target.lastChild.remove();
}
function patchAttributes(target,source){
 for(const a of Array.from(target.attributes))if(!source.hasAttribute(a.name))target.removeAttribute(a.name);
 for(const a of source.attributes)if(target.getAttribute(a.name)!==a.value)target.setAttribute(a.name,a.value);
}
function stableHTML(target,html){
 if(target._tideHTML===html)return;
 const template=document.createElement('template');template.innerHTML=html;
 patchTree(target,template.content);target._tideHTML=html;
}
function stableMarkers(html){
 const target=$('#markers');if(target._tideHTML===html)return;
 const template=document.createElement('template');template.innerHTML=html;
 const existing=new Map(Array.from(target.children).map(el=>[el.dataset.act,el]));
 for(const next of template.content.children){
  const old=existing.get(next.dataset.act);
  if(old){patchAttributes(old,next);patchTree(old,next);existing.delete(next.dataset.act);}
  else target.appendChild(next.cloneNode(true));
 }
 for(const old of existing.values())old.remove();
 target._tideHTML=html;
}
function paintHUD(){let s=sim.s;$('#date').textContent=BALANCE.seasonNames[sim.season]+' · Day '+sim.seasonDay;$('#year').textContent='Year '+sim.year+' · '+(s.paused?'A moment to plan':s.time>.76?'The evening Hearth':s.time<.26?'A quiet morning':'A day on the island');let hour=Math.floor(s.time*24),minute=Math.floor(s.time*1440)%60,clock=String(hour).padStart(2,'0')+':'+String(minute).padStart(2,'0'),phase=s.time<.23?'Night':s.time<.30?'Dawn':s.time<.50?'Morning':s.time<.72?'Afternoon':s.time<.86?'Dusk':'Night';$('#clock').textContent=clock;$('#year').textContent='Year '+sim.year+' · '+clock+' · '+(s.paused?'Paused':phase);$('#calendar').style.setProperty('--day-progress',s.time);$('#speedbar').title='Full day: '+sim.daySeconds/60+' minutes at 1×';$('#stage').textContent=sim.stage+' · '+sim.people.length+' people';
 let rs=[['food','Food',sim.food],['wood','Wood',s.stock.wood],[sim.learned('stonework')?'stone':'fiber',sim.learned('stonework')?'Stone':'Thatch',sim.learned('stonework')?s.stock.stone:s.stock.fiber],['insight','Insight',s.insight]];
 stableHTML($('#resources'),rs.map(([k,n,v])=>`<button class="resource" data-act="${k==='insight'?'knowledge':'supplies'}">${ico(k==='insight'?'spark':GOODS[k][1])}<span><strong>${Math.floor(v)}</strong><small>${n}</small></span></button>`).join(''));
 document.querySelectorAll('[data-act^="speed:"]').forEach(b=>b.classList.toggle('active',Number(b.dataset.act.split(':')[1])===s.speed&&!s.paused));stableHTML($('#pausebtn'),ico(s.paused?'play':'pause'));$('#soundbtn').classList.toggle('active',!!UI.sound);
 if(s.started){for(let g of GOALS)if(g.test(sim)&&!s.awards[g.id])sim.award(g.id,g.title,g.reward);}
 let g=GOALS.find(g=>!sim.s.awards[g.id])||GOALS[GOALS.length-1],done=GOALS.filter(g=>s.awards[g.id]).length;stableHTML($('#objective'),`<div class="eyebrow">${ico('leaf')} ${sim.stage} · ${done} / ${GOALS.length}</div><h2>${g.title}</h2><p>${g.desc}</p><button class="linkbtn" data-act="goal:${g.id}">${g.label} ${ico('arrow')}</button><div class="progressline"><i style="width:${done/GOALS.length*100}%"></i></div>`);
 $('#objective').style.display=UI.panel||UI.ghost||UI.pathMode?'none':'';$('#demoBadge').hidden=!s.demo;
}
function paintMarkers(){let nodes=sim.s.world.nodes.filter(n=>sim.knownAt(n.x,n.z)&&!n.found&&(n.kind==='cache'?n.left>0:n.id==='wreck'?n.left>0:['spring','seeds','fishing'].includes(n.id)||sim.day>5));let str='';for(let n of nodes){let p=view.project(n.x,groundY(n.x,n.z)+1.4,n.z);if(p.x<15||p.x>view.w-15||p.y<150||p.y>view.h-190)continue;str+=`<button class="marker" style="left:${p.x}px;top:${p.y}px" data-act="node:${n.id}" aria-label="${esc(n.name)}">${ico(n.icon)}</button>`;}
 if(sim.s.pendingArrival){let a=sim.s.pendingArrival,p=view.project(a.x,2,a.z);str+=`<button class="marker arrival" style="left:${p.x}px;top:${p.y}px" data-act="people" aria-label="A survivor is waiting">${ico('people')}</button>`;}
 if(view.zoom>1.3||UI.selected?.kind==='person')for(let c of sim.people){if(UI.selected?.kind==='person'&&UI.selected.id!==c.id&&view.zoom<1.4)continue;let p=view.project(c.x,1.95,c.z);if(p.y<150||p.y>view.h-165)continue;str+=`<button class="marker person" style="left:${p.x}px;top:${p.y}px" data-act="person:${c.id}">${esc(c.first)}</button>`;}
 for(const r of REGIONS.slice(1))if(!sim.explored(r.id)&&r.requires.every(id=>sim.explored(id))){let p=view.project(r.x,2.4,r.z);if(p.x>28&&p.x<view.w-28&&p.y>170&&p.y<view.h-175)str+=`<button class="marker trail" style="left:${p.x}px;top:${p.y}px" data-act="region:${r.id}" aria-label="Explore ${r.name}">${ico('compass')}<small>${r.name}</small></button>`;}
 stableMarkers(str);$('#markers').style.display=UI.ghost||UI.pathMode||!sim.s.started?'none':'';
}
class IslandAudio{constructor(){let A=window.AudioContext||window.webkitAudioContext;this.ctx=new A();let b=this.ctx.createBuffer(1,this.ctx.sampleRate*4,this.ctx.sampleRate),d=b.getChannelData(0),r=rand(7),last=0;for(let i=0;i<d.length;i++){last=(last+.02*(r()*2-1))/1.02;d[i]=last;}let source=this.ctx.createBufferSource();source.buffer=b;source.loop=true;let filter=this.ctx.createBiquadFilter();filter.type='lowpass';filter.frequency.value=550;this.gain=this.ctx.createGain();this.gain.gain.value=.32;source.connect(filter).connect(this.gain).connect(this.ctx.destination);source.start();}
 note(){if(this.ctx.state!=='running')this.ctx.resume();let o=this.ctx.createOscillator(),g=this.ctx.createGain(),t=this.ctx.currentTime;o.type='sine';o.frequency.value=[261.63,293.66,329.63,392,440][Math.floor(Math.random()*5)];g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(.04,t+.02);g.gain.exponentialRampToValueAtTime(.0001,t+1.5);o.connect(g).connect(this.ctx.destination);o.start();o.stop(t+1.6);}
 close(){this.ctx.close();}}
function demo(){save();let t=new TideSim();t.s.started=true;t.s.demo=true;t.s.day=66;t.s.time=.43;t.s.known=Object.keys(TECH);t.s.flags={spring:true,seeds:true,fishing:true,stone:true,copper:true,lookout:true,herbs:true,first_hearth:true,first_shelter:true,harvest:true,salvaged:true};t.s.world.nodes.forEach(n=>n.found=true);t.s.world.explored=REGIONS.map(r=>r.id);for(let k in t.s.stock)t.s.stock[k]=50;t.s.stock.fresh=0;t.add('fresh',20);t.s.stock.wood=90;t.s.insight=8;
 [['Ada','Rowan','f','#b2995e'],['Noah','Bennett','m','#819787'],['June','Hale','f','#b57c65'],['Finn','Ash','m','#859f92']].forEach(a=>t.addPerson(a[0],a[1],a[2],27,a[3],'A new beginning',0,3));
 let layout=[['hearth',0,1],['shelter',-4.6,5.2],['house',-3.3,.3],['house',3.5,.2],['house',3.7,-3.7],['house',-3.2,-4.1],['field',-7.3,4.8],['field',-7.5,8.6],['store',.2,-3.6],['woodpost',6.6,-3.1],['workshop',7.0,1.0],['water',-3.3,3.7],['fish',9.7,5.8],['signal',1.6,10],['smoker',5.2,5.1],['healer',-6.7,-.2],['bench',0,3.6],['lamp',1.7,3.5],['lamp',-1.5,-1.8],['quarry',3.2,-7.3]];
 t.s.buildings=[];for(let[type,x,z]of layout){let b={id:'b'+t.s.nextId++,type,x,z,rot:0,built:true,progress:BUILD[type].labor,up:['woodpost','store','fish'].includes(type),growth:type==='field'?12:0,tended:66,recipe:'planks',mode:'stone',family:false,paused:false};t.s.buildings.push(b);t.s.world.trees.forEach(q=>{if(Math.hypot(q.x-x,q.z-z)<BUILD[type].size+.8)q.wood=0;});}
 let houses=t.s.buildings.filter(b=>b.type==='house');t.people.forEach((p,i)=>{p.home=houses[Math.floor(i/2)].id;p.x=houses[Math.floor(i/2)].x;p.z=houses[Math.floor(i/2)].z+1.8;for(let k of ['construction','carpentry','seamanship'])p.skills[k]=3;});
 ['woodpost','field','hunt','workshop','fish','field','water','quarry'].forEach((type,i)=>{let b=t.buildings.find(b=>b.type===type&&!t.people.some(p=>p.job===b.id));if(b)t.assign(t.people[i].id,b.id);});
 t.s.paths=[[-7,5,-4,3,0,3,0,1,0,-3],[-3,0,0,1,3.5,0,7,1,9,5],[-3,-4,0,-3,3,-4,6,-3],[-7,8,-7,5]].map(a=>{let out=[];for(let i=0;i<a.length;i+=2)out.push({x:a[i],z:a[i+1]});return out;});
 setupSim(t);sim.s.paused=false;UI.selected=null;closePanel(false);hideModal();view.cx=0;view.cz=0;view.zoom=1.15;sim.dirty=true;showToast('A glimpse of what could be','This sample village is separate from your saved story.','leaf');}
function ending(){modal(`<div class="welcome"><div class="logoicon">${ico('sail')}</div><div class="eyebrow">The first voyage</div><h2>A new shore.</h2><p>Four castaways once stood beside a broken boat.<br>Now, aboard <strong>${esc(sim.s.boat.name)}</strong>, your people have found land beyond the horizon.</p><p>There is copper in these hills.<br>And a whole new chapter waiting to begin.</p><div class="note">First-island prototype complete.<br>Second-island settlement and trade come later.</div><button class="primary" data-act="returnhome">Look back at our island</button><button class="secondary" data-act="export">Keep a copy of our story</button></div>`);}
function act(action){let [a,...rest]=action.split(':'),id=rest.join(':');
 if(a==='explore'){openPanel('explore');return;}
 if(a==='region'){openPanel('region',id);return;}
 if(a==='scout'){let msg=sim.orderScout(id);if(msg){error(msg);renderPanel();}else{closePanel();sim.s.paused=false;save();}return;}
 if(a==='cancelscout'){sim.cancelScout(id);renderPanel();save();return;}
 if(a==='watchscout'){let p=sim.scoutFor(id);if(p){view.cx=p.x;view.cz=p.z;view.zoom=1.6;UI.selected={kind:'person',id:p.id};closePanel();}return;}
 if(a==='focusregion'||a==='focusnode'){let r=a==='focusregion'?sim.region(id):sim.s.world.nodes.find(n=>n.id===id);if(r){view.cx=r.x;view.cz=r.z;view.zoom=1.15;view.camera();closePanel();}return;}
 if(a==='overview'){view.cx=0;view.cz=-14;view.zoom=.58;view.camera();closePanel();return;}
 if(a==='begin'){startFresh();return;}if(a==='continue'){let s=safeLoad();if(s){setupSim(new TideSim(s));sim.s.started=true;sim.s.paused=false;hideModal();}return;}
 if(a==='newconfirm'){modal(`<div class="welcome compact"><h2>Another beginning?</h2><p>Starting again replaces the story saved in this browser. Export it first to keep a copy.</p><button class="primary" data-act="export">Export current story</button><button class="secondary danger" data-act="begin">Begin a new story</button><button class="secondary" data-act="dismissmodal">Keep this island</button></div>`);return;}
 if(a==='dismissmodal'){hideModal();return;}if(a==='demo'){demo();return;}if(a==='mainmenu'){save();welcome();return;}
 if(a==='close'){closePanel();return;}if(a==='pause'){sim.s.paused=!sim.s.paused;if(UI.panel)UI.wasRunning=!sim.s.paused;return;}if(a==='speed'){sim.s.speed=Number(id);sim.s.paused=false;UI.wasRunning=true;return;}
 if(a==='zoom'){view.zoom=clamp(view.zoom*(Number(id)>0?1.2:1/1.2),.38,3.5);return;}if(a==='rotate'){view.yaw+=Math.PI/4;return;}if(a==='recenter'){view.cx=0;view.cz=0;view.zoom=1;return;}
 if(a==='photo'){closePanel();document.body.classList.add('photo');return;}if(a==='sound'){try{if(UI.sound){UI.sound.close();UI.sound=null;}else UI.sound=new IslandAudio();}catch(e){error('Sound is unavailable in this browser.');}return;}
 if(a==='category'){UI.category=id;renderPanel();return;}if(a==='techcat'){UI.techCategory=id;renderPanel();return;}if(a==='togglelocked'){UI.showLocked=!UI.showLocked;renderPanel();return;}
 if(a==='preview'){preview(id);return;}if(a==='cancelplace'){UI.ghost=null;UI.pathMode=false;$('#placement').hidden=true;if(UI.wasRunning)sim.s.paused=false;return;}
 if(a==='turnplace'){if(UI.ghost)UI.ghost.rot+=Math.PI/2;return;}if(a==='relocate'){let b=sim.getB(id);if(b){preview(b.type);UI.ghost={type:b.type,x:b.x,z:b.z,rot:b.rot,moveId:b.id};paintPlacement();}return;}
 if(a==='place'){if(!UI.ghost)return;if(UI.ghost.moveId){let g=UI.ghost,msg=sim.moveBuilding(g.moveId,g.x,g.z,g.rot);if(msg){error(msg);return;}UI.ghost=null;$('#placement').hidden=true;sim.s.paused=false;save();return;}let r=sim.orderBuild(UI.ghost.type,UI.ghost.x,UI.ghost.z,UI.ghost.rot);if(r.error){error(r.error);return;}UI.ghost=null;$('#placement').hidden=true;sim.s.paused=false;save();return;}
 if(a==='path'){if(!UI.panel)UI.wasRunning=!sim.s.paused;closePanel(false);UI.pathMode=true;sim.s.paused=true;UI.ghost=null;$('#placement').hidden=false;paintPlacement();return;}if(a==='endpath'){UI.pathMode=false;$('#placement').hidden=true;sim.s.paused=!UI.wasRunning;save();return;}
 if(a==='node'){UI.selected={kind:'node',id};openPanel('node',id);return;}if(a==='person'){UI.selected={kind:'person',id};openPanel('person',id);return;}if(a==='building'){UI.selected={kind:'building',id};openPanel('building',id);return;}
 if(a==='follow'){let p=sim.people.find(p=>p.id===id);if(p){view.cx=p.x;view.cz=p.z;view.zoom=2;UI.selected={kind:'person',id};closePanel();}return;}
 if(a==='investigate'){let msg=sim.orderNode(id);if(msg)error(msg);else{closePanel();sim.s.paused=false;showToast('On the way','Someone is heading there. Watch them bring something back.','compass');}save();return;}
 if(a==='welcome'){error(sim.welcome());renderPanel();save();return;}if(a==='upgrade'){error(sim.upgrade(id));renderPanel();save();return;}if(a==='cancelbuild'){sim.cancelBuild(id);closePanel();save();return;}
 if(a==='workpause'){let b=sim.getB(id);b.paused=!b.paused;sim.people.filter(p=>p.job===b.id).forEach(p=>p.task=null);renderPanel();save();return;}if(a==='family'){let b=sim.getB(id);b.family=!b.family;renderPanel();save();return;}
 if(a==='research'){let msg=sim.research(id);error(msg);if(!msg&&UI.sound)UI.sound.note();renderPanel();save();return;}if(a==='needtech'){UI.techCategory=TECH[id]?.branch||'All';openPanel('knowledge');return;}
 if(a==='meet'){sim.meetTonight();for(let g of GOALS)if(g.test(sim)&&!sim.s.awards[g.id])sim.award(g.id,g.title,g.reward);renderPanel();save();return;}
 if(a==='goal'){goalAction(id);return;}if(a==='startboat'){error(sim.startBoat());renderPanel();save();return;}
 if(a==='launch'){let ids=[...document.querySelectorAll('input[name="crew"]:checked')].map(e=>e.value);let msg=sim.launch(ids);if(msg)error(msg);else{closePanel();sim.s.paused=false;sim.s.speed=4;save();}return;}
 if(a==='watchboat'){closePanel();sim.s.paused=false;return;}if(a==='ending'){ending();return;}if(a==='returnhome'){view.cx=0;view.cz=0;view.zoom=1;hideModal();closePanel();sim.s.paused=false;return;}
 if(a==='save'){save();showToast(UI.storageOK?'Our story is saved':'Export a backup',UI.storageOK?'You can return to this island on this browser.':'Local storage is not available here.','save');return;}
 if(a==='export'){let blob=new Blob([JSON.stringify(sim.toJSON(),null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`tidefolk-day-${sim.day}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),10000);return;}
 if(a==='import'){$('#importfile').click();return;}if(a==='nothing')return;
 if(['build','people','knowledge','supplies','journal','settings','goals','voyage'].includes(a)){if(UI.panel?.kind===a)closePanel();else openPanel(a);return;}
}
document.addEventListener('click',e=>{let b=e.target.closest('[data-act]');if(b){act(b.dataset.act);paintHUD();}});
document.addEventListener('change',e=>{let op=e.target.dataset.change;if(!op)return;let [a,id]=op.split(':'),v=e.target.value;
 if(a==='daypace'){let seconds=Number(v);if(BALANCE.dayLengths.includes(seconds))sim.s.settings.daySeconds=seconds;}
 if(a==='job')error(sim.assign(id,v));if(a==='worker'){if(v)error(sim.assign(v,id));else sim.people.filter(p=>p.job===id).forEach(p=>{p.job=null;p.task=null;});}
 if(a==='recipe'){sim.getB(id).recipe=v;sim.people.filter(p=>p.job===id).forEach(p=>p.task=null);}if(a==='quarry'){sim.getB(id).mode=v;sim.people.filter(p=>p.job===id).forEach(p=>p.task=null);}if(a==='home'&&v)error(sim.setHome(v,id));if(a==='target')sim.s.policies[id]=clamp(Number(v)||5,5,300);if(a==='boatname')sim.s.boat.name=v.trim().slice(0,32)||'The Hope';save();renderPanel();});
$('#importfile').addEventListener('change',async e=>{let f=e.target.files[0];if(!f)return;try{if(f.size>4e6)throw Error('Save file is too large.');let s=TideSim.validate(JSON.parse(await f.text()));setupSim(new TideSim(s));sim.s.started=true;sim.s.paused=true;closePanel(false);hideModal();save();showToast('Your island is here','The story was imported. Press play when you are ready.','save');}catch(e){error(e.message);}finally{$('#importfile').value='';}});
function pointerControls(){let canvas=$('#world'),points=new Map(),gesture=null,stroke=[],pinch=0;
 canvas.addEventListener('pointerdown',e=>{if(document.body.classList.contains('photo')){document.body.classList.remove('photo');return;}if(!$('#modal').hidden)return;canvas.setPointerCapture(e.pointerId);points.set(e.pointerId,{x:e.clientX,y:e.clientY});if(points.size===1){gesture={x:e.clientX,y:e.clientY,lastX:e.clientX,lastY:e.clientY,moved:false};stroke=[];if(UI.pathMode){let p=view.ground(e.clientX,e.clientY);if(landRatio(p.x,p.z)<.88&&sim.knownAt(p.x,p.z))stroke.push(p);}}else if(points.size===2){let a=[...points.values()];pinch=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y);if(gesture)gesture.moved=true;}});
 canvas.addEventListener('pointermove',e=>{if(!points.has(e.pointerId)||!gesture)return;let old=points.get(e.pointerId);points.set(e.pointerId,{x:e.clientX,y:e.clientY});if(points.size===2){let a=[...points.values()],d=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y);if(pinch>0)view.zoom=clamp(view.zoom*d/pinch,.38,3.5);pinch=d;return;}
  let dx=e.clientX-gesture.lastX,dy=e.clientY-gesture.lastY;if(Math.hypot(e.clientX-gesture.x,e.clientY-gesture.y)>7)gesture.moved=true;
  if(UI.pathMode){let p=view.ground(e.clientX,e.clientY);if(landRatio(p.x,p.z)<.89&&sim.knownAt(p.x,p.z)&&(!stroke.length||dist(p,stroke[stroke.length-1])>.35)){stroke.push(p);view.previewPath=stroke;}}else if(gesture.moved)view.pan(dx,dy);gesture.lastX=e.clientX;gesture.lastY=e.clientY;});
 const end=e=>{points.delete(e.pointerId);if(points.size)return;if(!gesture)return;if(UI.pathMode){if(stroke.length>1){sim.s.paths.push(stroke.slice(0,150));sim.s.paths=sim.s.paths.slice(-120);sim.dirty=true;save();}stroke=[];view.previewPath=null;}else if(!gesture.moved){let p=view.ground(e.clientX,e.clientY);if(UI.ghost){UI.ghost.x=p.x;UI.ghost.z=p.z;paintPlacement();}else{let candidates=[];for(let c of sim.people){let pt=view.project(c.x,.55+.7,c.z);candidates.push({kind:'person',id:c.id,d:Math.hypot(pt.x-e.clientX,pt.y-e.clientY),limit:20});}for(let b of sim.buildings){let pt=view.project(b.x,.55+.6,b.z);candidates.push({kind:'building',id:b.id,d:Math.hypot(pt.x-e.clientX,pt.y-e.clientY),limit:Math.max(25,BUILD[b.type].size*view.px)});}candidates=candidates.filter(c=>c.d<c.limit).sort((a,b)=>a.d-b.d);if(candidates[0])act(candidates[0].kind+':'+candidates[0].id);else{UI.selected=null;closePanel();}}}gesture=null;};
 canvas.addEventListener('pointerup',end);canvas.addEventListener('pointercancel',()=>{points.clear();gesture=null;stroke=[];view.previewPath=null;});canvas.addEventListener('wheel',e=>{e.preventDefault();view.zoom=clamp(view.zoom*Math.exp(-e.deltaY*.001),.38,3.5);},{passive:false});
}
document.addEventListener('visibilitychange',()=>{if(document.hidden){save();if(UI.sound)UI.sound.ctx.suspend().catch(()=>{});}else if(UI.sound)UI.sound.ctx.resume().catch(()=>{});});window.addEventListener('pagehide',save);document.addEventListener('keydown',e=>{if(e.target.matches('input,select'))return;if(e.key==='Escape'){UI.ghost=null;UI.pathMode=false;$('#placement').hidden=true;closePanel();}if(e.key===' '){e.preventDefault();act('pause');}});
try{
 setupSim(new TideSim());view=new IslandView($('#world'));icons();pointerControls();welcome();let last=performance.now();
 function frame(t){let dt=Math.min((t-last)/1000,.1);last=t;if(!document.hidden){sim.advance(dt);view.render(sim,t/1000,UI.selected,UI.ghost);if(t-UI.lastPaint>350){paintHUD();paintMarkers();UI.lastPaint=t;}if(t>UI.toastUntil)$('#toast').classList.remove('show');if(t-UI.saveAt>10000){save();UI.saveAt=t;}
  if(sim.s.boat.stage==='sailing'){let b=sim.buildings.find(b=>b.type==='boatyard');if(b){let k=clamp((sim.s.boat.travel||0)/2,0,1);view.cx+=(b.x+k*30-view.cx)*.025;view.cz+=(b.z+k*18-view.cz)*.025;}}
  if(sim.s.boat.stage==='arrived'&&!UI.endShown){UI.endShown=true;save();ending();}
 }
 requestAnimationFrame(frame);}
 requestAnimationFrame(frame);window.tidefolk={get sim(){return sim;},view,UI,act,save,version:'0.2.0'};
}catch(e){$('#fatal').hidden=false;$('#fatal').textContent='Tidefolk could not open the island: '+e.message;console.error(e);}
