import assert from 'node:assert/strict';
import fs from 'node:fs';
import {Game,GUIDE} from '../engine.js';
import {decodeWorld} from '../world.js';
import {BASES,CRAFT,MODULES,TECHS,OPERATIONS,NARRATIVES,PROJECTS,RESOURCES} from '../data.js';
import {EVENTS,HISTORY,DYNAMIC} from '../events.js';
const {defs}=decodeWorld(JSON.parse(fs.readFileSync(new URL('../vendor/countries-50m.json',import.meta.url))));
let passed=0;
const test=(name,fn)=>{fn();passed++;console.log('PASS',name);};
const fixture=()=>new Game(defs,{seed:'QA: the quiet century'});
const finishJobs=g=>{const last=Math.max(g.s.day,...g.s.jobs.map(j=>j.finish));g.advance(last-g.s.day,{autoResolve:true});};
function invariant(g){for(const[k,v]of Object.entries(g.s.resources))assert.ok(Number.isFinite(v)&&v>=0&&v<=g.capacity(k)+1e-6,`${k} invalid ${v}`);for(const v of Object.values(g.s.metrics))assert.ok(Number.isFinite(v)&&v>=0&&v<=100);for(const a of g.s.craft)if(a.busy)assert.ok(g.s.jobs.some(j=>j.id===a.busy),'orphaned craft assignment');for(const a of g.s.agents)if(a.busy)assert.ok(g.s.jobs.some(j=>j.id===a.busy),'orphaned interface assignment');assert.ok(g.commandUsed()<=g.command());assert.equal(new Set(g.s.jobs.map(j=>j.id)).size,g.s.jobs.length);}
function cleanSave(g){const s=JSON.parse(g.export()).state;delete s.notices;delete s.speed;return s;}

test('world data and content references',()=>{assert.equal(defs.length,241);assert.equal(new Set(defs.map(d=>d.id)).size,defs.length);for(const id of ['840','156','643','250','710','682','392','528'])assert.ok(defs.some(d=>d.id===id));for(const t of Object.values(TECHS))if(t.pre)assert.ok(TECHS[t.pre]);assert.equal(Object.keys(TECHS).length,48);assert.equal(Object.keys(BASES).length,8);assert.equal(Object.keys(CRAFT).length,8);assert.equal(Object.keys(NARRATIVES).length,12);assert.equal(Object.keys(EVENTS).length,63);});
test('new game matches resource-constrained start',()=>{const g=fixture();assert.equal(g.year,1945);assert.equal(g.s.bases.length,1);assert.equal(g.s.craft.length,3);assert.equal(g.s.resources.exotic,30);assert.equal(g.s.resources.capital,0);assert.equal(g.command(),3);invariant(g);});
test('initial loop observes, surveys and mines without debug resources',()=>{const g=fixture();assert.ok(g.launch('observe','840').ok);finishJobs(g);assert.equal(g.s.stats.observe,1);assert.ok(GUIDE[g.s.guide].test(g.s));assert.ok(g.claimGuide().ok);assert.ok(g.launch('survey','840').ok);finishJobs(g);assert.ok(g.country('840').surveyed);assert.ok(g.claimGuide().ok);assert.ok(g.launch('mine','840').ok);finishJobs(g);assert.ok(g.s.stats.mine);assert.ok(g.claimGuide().ok);invariant(g);});
test('research prerequisites, affordability and slot locking',()=>{const g=fixture();assert.ok(g.researchPreview('human2').blocked.length);assert.ok(g.research('human1').ok);assert.ok(g.researchPreview('stealth1').blocked.length);finishJobs(g);assert.ok(g.tech('human1'));assert.ok(g.researchPreview('human1').blocked.length);invariant(g);});
test('first company creates actual market access and income',()=>{const g=fixture();assert.ok(!g.trade('common',1,true).ok);g.launch('observe','840');finishJobs(g);g.claimGuide();g.launch('survey','840');finishJobs(g);g.claimGuide();g.launch('mine','840');finishJobs(g);g.claimGuide();g.research('human1');finishJobs(g);g.claimGuide();assert.ok(g.launch('front','840').ok);finishJobs(g);g.claimGuide();assert.ok(g.legal('840'));const capital=g.s.resources.capital;g.advance(5,{autoResolve:true});assert.ok(g.s.resources.capital>capital);const before=g.s.resources.common;assert.ok(g.trade('common',2,true).ok);assert.equal(g.s.resources.common,before+2);assert.ok(g.s.footprint>0);assert.ok(!g.trade('exotic',1,true).ok);assert.ok(!g.trade('rare',-5,true).ok);invariant(g);});
test('operations cancel and return fraction, not free resources',()=>{const g=fixture(),old=g.s.resources.energy;g.launch('observe','840');const j=g.s.jobs[0];g.cancelJob(j.id);assert.equal(g.s.jobs.length,0);assert.ok(!g.s.craft.some(a=>a.busy));assert.ok(g.s.resources.energy<old);invariant(g);});
test('module sockets and duplicate cap enforced',()=>{const g=fixture();g.gain({common:100,rare:50,nuclear:40,energy:100,exotic:20});assert.ok(g.buildModule('base_home','power').ok);assert.ok(g.buildModule('base_home','power').ok);assert.ok(g.modulePreview('base_home','power').blocked.length);finishJobs(g);assert.equal(g.s.bases[0].modules.power,3);invariant(g);});
test('save restore preserves active jobs and deterministic simulation',()=>{const g=fixture();g.launch('observe','840');g.research('human1');g.advance(20);const h=Game.restore(g.export(),defs);assert.deepEqual(cleanSave(g),cleanSave(h));g.advance(3000,{autoResolve:true});h.advance(3000,{autoResolve:true});assert.deepEqual(cleanSave(g),cleanSave(h));invariant(h);});
test('save importer rejects broken format, country table and resource numbers',()=>{const g=fixture();assert.throws(()=>Game.restore('{bad',defs));assert.throws(()=>Game.restore({format:'other'},defs));let raw=JSON.parse(g.export());raw.state.resources.exotic=-1;assert.throws(()=>Game.restore(raw,defs));raw=JSON.parse(g.export());delete raw.state.countries['840'];assert.throws(()=>Game.restore(raw,defs));});
test('hard public evidence survives narrative and containment',()=>{const g=fixture();g.s.researched.push('cognitive1');g.gain({influence:50,intel:50});g.addEvidence('Public artifact','840',20,'artifact',true,'hardware');g.addEvidence('Weak report','840',3,'witness',true);g.contain(99);assert.ok(g.s.evidence.find(e=>e.name==='Public artifact').strength===20);g.narrativeAction('balloons','seed');g.advance(200,{autoResolve:true});g.narrativeAction('balloons','contaminate');assert.ok(g.s.metrics.evidence>=20);assert.ok(g.s.noiseUses>0);assert.ok(g.s.pattern>0);});
test('treaty choices bind benefits and store memories',()=>{const g=fixture(),c=g.country('840');c.contact=3;c.trust=100;g.gain({intel:100,influence:100});for(let tries=0;tries<6&&!g.treaty(c.id);tries++){g.propose(c.id,['resources','noninterference'],'intel');if(!g.treaty(c.id))g.advance(200,{autoResolve:true});}assert.ok(g.treaty(c.id));const rare=g.s.resources.rare;g.advance(30,{autoResolve:true});assert.ok(g.s.resources.rare>rare);const t=g.treaty(c.id);g.breakTreaty(t.id);assert.ok(!g.treaty(c.id));assert.ok(c.memory.some(x=>x.includes('ended')));});
test('interface has a career, can act, cancel, and retain agency',()=>{const g=fixture();g.s.researched.push('bio1');g.s.bases[0].modules.bio=1;const c=g.country('840');c.insight=80;g.gain({influence:50,intel:60,bio:20});assert.ok(g.recruit('adviser','840','industry').ok);finishJobs(g);const a=g.s.agents[0];assert.equal(a.phase,'career');g.advance(a.careerDays,{autoResolve:true});assert.equal(a.phase,'active');assert.ok(g.agentAction(a.id,'promote').ok);const task=g.s.jobs.find(j=>j.agent===a.id);g.cancelJob(task.id);assert.equal(a.busy,null);assert.ok(g.agentAction(a.id,'promote').ok);finishJobs(g);assert.ok(a.access>25);invariant(g);});
test('history and event queues stay bounded through a complete unattended century',()=>{for(const seed of ['weather balloon','Roswell','ordinary bureaucracy']){const g=new Game(defs,{seed});g.advance(40000,{autoResolve:true});assert.ok(g.s.ended);assert.equal(g.s.ended.id,'expelled');assert.ok(g.s.eventQueue.length<=3);assert.ok(g.s.history.length>30);invariant(g);}});
test('each of six final-project paths resolves to its own ending',()=>{for(const id of Object.keys(PROJECTS)){const g=fixture();g.s.day=Math.floor((Date.UTC(2037,0,1)-Date.UTC(1945,0,1))/86400000);g.s.fired=[...HISTORY];g.s.researched=Object.keys(TECHS);g.s.stats={treaties:6,relief:8};g.s.doctrine={welfare:95,coercion:30,autonomy:20,intervention:20};g.s.open=id==='occupation';g.s.metrics.panic=5;for(const k of Object.keys(RESOURCES))g.s.resources[k]=g.capacity(k);const countries=['840','156','643','250','710','682'];for(const [i,cid]of countries.entries()){const c=g.country(cid);Object.assign(c,{contact:5,trust:95,leverage:95,dependence:95,infiltration:90,knowledge:20,hostility:0,insight:100,surveyed:true});g.s.treaties.push({id:'fixture_t'+i,country:cid,clauses:['noninterference'],active:true,expiry:g.s.day+6000});g.s.bases.push({...g.s.bases[0],id:'fixture_b'+i,country:cid});g.s.fronts.push({id:'fixture_f'+i,name:'Fixture firm',country:cid,cover:90,level:5});g.s.agents.push({id:'fixture_a'+i,name:'Fixture interface',country:cid,institution:'media',method:'adviser',phase:'active',access:95,cover:95,adaptation:95,influence:90,competence:90,attachment:2,loyalty:100,suspicion:0,busy:null,autonomous:true});}for(const n of Object.values(g.s.narratives)){n.active=true;n.reach=80;n.truth=0;n.panic=0;}assert.ok(g.projectConditions(id).every(c=>c.ok),id);assert.ok(g.startProject(id).ok,id);g.advance(PROJECTS[id].days,{autoResolve:true});assert.equal(g.s.projectReady,id);assert.ok(!g.s.ended,'must await explicit commitment');assert.ok(g.finalize().ok,id);assert.equal(g.s.ended.id,id);}});
test('every mandatory event remains resolvable with zero resources and no craft',()=>{for(const id of Object.keys(EVENTS)){const g=fixture();for(const k of Object.keys(g.s.resources))g.s.resources[k]=0;g.s.craft=[];g.raise(id,{country:'840'});const v=g.eventView(),choice=v.choices.find(c=>!c.blocked.length);assert.ok(choice,id);assert.ok(g.choose(choice.id).ok,id);assert.equal(g.s.eventQueue.length,0);}});
test('last installation evacuation gives an explicit loss',()=>{const g=fixture();g.evacuate('base_home');assert.equal(g.s.ended.id,'expelled');});
console.log(`\n${passed} simulation suites passed. ${defs.length} entities; ${Object.keys(TECHS).length} research nodes; ${Object.keys(EVENTS).length} events (${HISTORY.length} historical, ${DYNAMIC.length} dynamic).`);
export {defs,invariant};
