'use strict';
const {chromium,webkit,devices}=require('playwright');
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict'),crypto=require('node:crypto'),zlib=require('node:zlib');
const root=process.env.GAME_DIR,out=process.env.REPORT_DIR;fs.mkdirSync(out,{recursive:true});
const files=['index.html','style.css','data.js','sim.js','world.js','ui.js'];
const reportFile=path.join(out,'report.json');
const report=process.env.HOST_ONLY?JSON.parse(fs.readFileSync(reportFile)):{version:'0.2.0',testedAt:new Date().toISOString(),browsers:[]};
const write=()=>fs.writeFileSync(reportFile,JSON.stringify(report,null,2));
const legacy=JSON.parse(zlib.gunzipSync(Buffer.from(fs.readFileSync(process.env.LEGACY_FIXTURE,'utf8').trim(),'base64')));
const server=http.createServer((req,res)=>{let name=new URL(req.url,'http://local').pathname.split('/').pop()||'index.html';if(!files.includes(name)){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',({'.html':'text/html','.js':'application/javascript','.css':'text/css'})[path.extname(name)]);res.end(fs.readFileSync(path.join(root,name)));});
async function test(engine,name,opts,touch){
 const r={name,checks:[],errors:[]};report.browsers.push(r);
 const browser=await engine.launch({headless:true,...(engine===chromium?{args:['--enable-webgl','--use-angle=swiftshader','--enable-unsafe-swiftshader']}:{})});
 const context=await browser.newContext(opts),page=await context.newPage();page.setDefaultTimeout(20000);page.on('pageerror',e=>r.errors.push(e.message));
 const click=async selector=>{let e=page.locator(selector).first();if(touch)await e.tap();else await e.click();};
 const shot=async suffix=>page.screenshot({path:path.join(out,name+'-'+suffix+'.png')});
 try{
  await page.goto('http://127.0.0.1:8787/',{waitUntil:'load'});await page.waitForFunction(()=>!!window.tidefolk);assert.equal(await page.evaluate(()=>tidefolk.version),'0.2.0');assert.equal(await page.locator('#fatal').isVisible(),false);r.webgl=await page.evaluate(()=>!!tidefolk.view.gl);await shot('welcome');
  await click('[data-act="begin"]');assert.equal(await page.evaluate(()=>tidefolk.sim.people.length),4);assert.equal(await page.evaluate(()=>tidefolk.sim.daySeconds),360);assert.equal(await page.evaluate(()=>tidefolk.sim.s.world.explored.length),1);await shot('opening');
  await page.evaluate(()=>{window.qaTarget=document.querySelector('#resources button');});await page.waitForTimeout(800);assert.ok(await page.evaluate(()=>qaTarget===document.querySelector('#resources button')));r.checks.push('Startup, six-minute default, stable HUD targets');
  for(const panel of ['people','build','knowledge','supplies','journal','settings','explore']){await click('[data-act="'+panel+'"]');assert.ok(await page.locator('#panel').isVisible());assert.ok(await page.evaluate(()=>tidefolk.sim.s.paused));await click('[data-act="close"]');}
  r.checks.push('All seven panels accessible through mouse/touch');
  await click('[data-act="explore"]');await shot('explore-chart');await click('.region-list [data-act="region:pinewood"]');assert.ok(await page.locator('[data-act="scout:pinewood"]').isDisabled());await click('[data-act="close"]');
  let result=await page.evaluate(()=>{let s=tidefolk.sim;s.s.paused=true;let msg=s.orderNode('wreck');s.runDays(1);return msg;});assert.equal(result,'');
  await click('[data-act="build"]');await click('[data-act="preview:hearth"]');let pt=await page.evaluate(()=>tidefolk.view.project(0,.55,1));if(touch)await page.touchscreen.tap(pt.x,pt.y);else await page.mouse.click(pt.x,pt.y);assert.ok(await page.locator('[data-act="place"]').isEnabled());await click('[data-act="place"]');await page.evaluate(()=>tidefolk.sim.runDays(1));assert.ok(await page.evaluate(()=>tidefolk.sim.has('hearth')));
  r.checks.push('Hearth built through earned salvage and native ground placement');
  await click('[data-act="explore"]');await click('.region-list [data-act="region:pinewood"]');await click('[data-act="scout:pinewood"]');assert.ok(await page.evaluate(()=>!!tidefolk.sim.scoutFor('pinewood')));await page.evaluate(()=>{tidefolk.sim.runDays(3);tidefolk.sim.s.paused=true;});assert.ok(await page.evaluate(()=>tidefolk.sim.explored('pinewood')));
  await click('[data-act="explore"]');await click('.region-list [data-act="region:pinewood"]');await shot('woodland-discovered');await click('[data-act="focusregion:pinewood"]');await page.waitForTimeout(400);await shot('woodland-world');
  r.checks.push('A named scout opens the wood through native Explore controls');
  await click('[data-act="explore"]');await click('.region-list [data-act="region:ridge"]');await click('[data-act="scout:ridge"]');await page.evaluate(()=>{tidefolk.sim.runDays(4);tidefolk.sim.s.paused=true;});assert.ok(await page.evaluate(()=>tidefolk.sim.explored('ridge')));
  await click('[data-act="explore"]');await click('.region-list [data-act="region:ridge"]');await click('[data-act="node:ridge_stone"]');await click('[data-act="investigate:ridge_stone"]');await page.evaluate(()=>{tidefolk.sim.runDays(3);tidefolk.sim.s.paused=true;});assert.ok(await page.evaluate(()=>tidefolk.sim.s.stock.stone>=5));assert.equal(await page.evaluate(()=>tidefolk.sim.s.world.nodes.find(n=>n.id==='ridge_stone').left),19);
  r.checks.push('New-region stone gathered and physically delivered, patch stock decreases');
  await click('[data-act="settings"]');await page.locator('#daypace').selectOption('600');assert.equal(await page.evaluate(()=>tidefolk.sim.daySeconds),600);await shot('slower-days-setting');await click('[data-act="close"]');await page.evaluate(()=>tidefolk.save());
  const expected=await page.evaluate(()=>({ids:tidefolk.sim.people.map(p=>p.id),explored:tidefolk.sim.s.world.explored,trees:tidefolk.sim.s.world.trees.length}));
  await page.reload();await page.waitForFunction(()=>!!window.tidefolk);await click('[data-act="continue"]');assert.deepEqual(await page.evaluate(()=>tidefolk.sim.s.world.explored),expected.explored);assert.equal(await page.evaluate(()=>tidefolk.sim.daySeconds),600);assert.equal(await page.evaluate(()=>tidefolk.sim.s.world.trees.length),expected.trees);
  r.checks.push('Exploration and slower-day preference persist across native save/reload');
  await click('[data-act="settings"]');const dp=page.waitForEvent('download');await click('[data-act="export"]');const d=await dp;const exportPath=path.join(out,name+'-save-v2.json');await d.saveAs(exportPath);assert.equal(JSON.parse(fs.readFileSync(exportPath)).version,2);
  await page.locator('#importfile').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from('{"version":999}')});await page.waitForTimeout(100);assert.deepEqual(await page.evaluate(()=>tidefolk.sim.people.map(p=>p.id)),expected.ids);
  await page.locator('#importfile').setInputFiles({name:'legacy-v1.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(legacy))});await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>tidefolk.sim.s.version),2);assert.deepEqual(await page.evaluate(()=>tidefolk.sim.people.map(p=>p.id)),legacy.people.map(p=>p.id));assert.deepEqual(await page.evaluate(()=>tidefolk.sim.buildings.map(b=>[b.id,b.x,b.z])),legacy.buildings.map(b=>[b.id,b.x,b.z]));
  r.checks.push('Version-2 export, invalid import rejection, real v1-save migration without losing buildings');
  await page.evaluate(()=>{tidefolk.act('mainmenu');tidefolk.save();});const saved=await page.evaluate(()=>localStorage.getItem('tidefolk.firsthearth.v1'));await click('[data-act="demo"]');await page.evaluate(()=>{tidefolk.save();tidefolk.act('overview');tidefolk.sim.s.paused=true;});assert.equal(await page.evaluate(()=>localStorage.getItem('tidefolk.firsthearth.v1')),saved);await page.waitForTimeout(800);await shot('expanded-island');
  const zoom=await page.evaluate(()=>tidefolk.view.zoom);await click('[data-act="zoom:1"]');assert.ok(await page.evaluate(()=>tidefolk.view.zoom)>zoom);
  await page.evaluate(()=>{tidefolk.act('focusregion:pinewood');});const count=await page.evaluate(()=>tidefolk.sim.s.paths.length);await click('[data-act="build"]');await click('[data-act="path"]');let points=await page.evaluate(()=>[tidefolk.view.project(-2,.55,-15),tidefolk.view.project(1,.55,-15)]);await page.mouse.move(points[0].x,points[0].y);await page.mouse.down();await page.mouse.move(points[1].x,points[1].y,{steps:8});await page.mouse.up();await click('[data-act="endpath"]');assert.ok(await page.evaluate(()=>tidefolk.sim.s.paths.length)>count);
  r.checks.push('Sample-save isolation, broader camera, pointer path in the new woodland');
  r.layout=await page.evaluate(()=>({width:innerWidth,height:innerHeight,scrollWidth:document.documentElement.scrollWidth}));assert.ok(r.layout.scrollWidth<=r.layout.width+1);assert.deepEqual(r.errors,[]);r.passed=true;
 }catch(e){r.passed=false;r.failure=String(e.stack).slice(0,3000);await shot('failure').catch(()=>{});}
 finally{await browser.close();write();}
}
async function hosting(){report.commit=process.env.RELEASE_SHA;const base='https://raw.githack.com/Michaelwmdegroot/First/'+report.commit+'/tidefolk-v01/';report.hosting={url:base+'index.html',files:[]};for(const name of files){try{const r=await fetch(base+name,{signal:AbortSignal.timeout(30000)}),data=Buffer.from(await r.arrayBuffer()),local=fs.readFileSync(path.join(root,name));report.hosting.files.push({name,status:r.status,type:r.headers.get('content-type'),sameBytes:data.equals(local),sha256:crypto.createHash('sha256').update(local).digest('hex')});}catch(e){report.hosting.files.push({name,error:e.message});}}report.hosting.passed=report.hosting.files.every(r=>r.status===200&&r.sameBytes);write();if(!report.hosting.passed)process.exitCode=1;}
(async()=>{if(process.env.HOST_ONLY){await hosting();console.log(JSON.stringify(report,null,2));return;}await new Promise(resolve=>server.listen(8787,'127.0.0.1',resolve));await test(chromium,'desktop',{viewport:{width:1440,height:960}},false);await test(chromium,'android',{...devices['Pixel 7']},true);await test(webkit,'iphone',{...devices['iPhone 13']},true);server.close();write();console.log(JSON.stringify(report,null,2));if(!report.browsers.every(r=>r.passed))process.exitCode=1;})().catch(e=>{console.error(e);server.close();write();process.exitCode=1;});