import {Game,GUIDE} from './engine.js';
import {loadWorld} from './world.js';
import {Globe} from './globe.js';
import {FallbackGlobe} from './globe-fallback.js';
import {AudioEngine} from './audio.js';
import {icon,mascot,portrait,esc} from './icons.js';
import {VERSION,START,DAY,clamp,RESOURCES,PHYSICAL,BLOCS,blocName,BASES,MODULES,CRAFT,OPERATIONS,INFILTRATION,INSTITUTIONS,CLAUSES,TREES,TECHS,NARRATIVES,CHARACTERS,ENDINGS,PROJECTS} from './data.js';
import {EVENTS,HISTORY,DYNAMIC} from './events.js';

const $=id=>document.getElementById(id), SAVE='alien-invader-browser-save-v1';
const audio=new AudioEngine();
const screens={world:['Planet Earth','globe','Operations, opportunities, and 241 very human jurisdictions.'],bases:['Hidden infrastructure','home','Small installations. Planet-sized plans.'],fleet:['The little fleet','ufo','Assign missions, not flight controls. Every craft is a scarce asset.'],agents:['Human resources','agent','Build a cover, a career, and possibly a conscience.'],diplomacy:['Secret handshakes','chat','Partners are useful. Independent partners are complicated.'],economy:['Perfectly normal business','trade','A quiet invasion still needs a procurement department.'],research:['Extraordinary engineering','flask','Unlock better tools before humanity learns how to find them.'],narratives:['The conversation','eye','Believing, knowing, and proving are three different problems.'],archive:['The very classified archive','folder','Your decisions leave stories, witnesses, and sometimes receipts.'],endgame:['The shape of the future','trophy','Decide what a successful invasion actually means.']};
const tabs={world:[['ops','Operations'],['countries','Countries'],['layers','Map layers']],bases:[['owned','Your bases'],['build','Build a base']],fleet:[['owned','Your fleet'],['build','Fabricate']],agents:[['owned','Your interfaces'],['recruit','Create an identity']],diplomacy:[['negotiate','Negotiate'],['agreements','Agreements'],['relations','World relations']],economy:[['market','Resources & market'],['companies','Front companies']],research:[['trees','Research trees']],narratives:[['stories','Narratives'],['people','People'],['exposure','Exposure'],['blue','Blue Veil']],archive:[['chronicle','Your history'],['evidence','Evidence'],['log','Activity log']],endgame:[['projects','Final projects'],['endings','Possible futures']]};
const layers={political:['Political','Partners are mint, adversaries coral, and the selected country gold. Uncontacted countries use their scenario region color.'],network:['The Network','Green regions contain your bases, companies, agents, or active accords.'],resources:['Resources','Gold-tinted countries have a completed resource survey.'],sensors:['Human sensors','Pale green is sparse coverage; coral is dense coverage.'],intelligence:['Intelligence','Teal is high intelligence confidence; pale is unknown.'],exposure:['Exposure','Coral indicates local suspicion. Classified knowledge is included only at high intelligence confidence.'],economy:['Economy','Gold marks front companies; green marks authorized procurement.'],technology:['Human research','Purple indicates advanced human counter-research; undiscovered programs remain pale.']};
const ui={screen:null,tab:null,selected:'840',base:'base_home',search:'',bloc:'all',tree:'all',institution:'industry',method:'adviser',clauses:['resources','noninterference'],offer:'intel',modal:null,title:true};
let game,world,globe,lastFrame=0,accumulator=0,lastHUD=0,lastDrawer=0,eventSeen=null,endingSeen=false,saveWarning=false;
const fmt=n=>Math.abs(n)>=10000?`${(n/1000).toFixed(1)}k`:Math.abs(n)>=1000?Math.round(n).toLocaleString('en-US'):Number(n).toFixed(n>0&&n<1?1:0);
const dur=d=>d>=730?`${(d/365).toFixed(1)} years`:d>=365?`${(d/365).toFixed(1)} year`:`${Math.max(0,Math.ceil(d))} days`;
const date=d=>new Date(START+d*DAY).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'});
const resValue=(k,v)=>k==='capital'?`$${fmt(v)}m`:fmt(v);
const sname=id=>game?.country(id)?.name||'Open ocean';
const region=id=>blocName(id,game.year,game.s.formed);
const badge=(text,kind='')=>`<span class="badge ${kind}">${esc(text)}</span>`;
const meter=(v,color='')=>`<div class="meter" ${color?`style="--bar:${color}"`:''}><span style="width:${clamp(v)}%"></span></div>`;
const btn=(label,action,attrs='',kind='secondary',disabled=false)=>`<button class="button ${kind}" data-action="${action}" ${attrs} ${disabled?'disabled':''}>${label}</button>`;
const attr=(name,value)=>`data-${name}="${esc(value)}"`;
function costs(obj={},reward=false){return `<div class="costs ${reward?'rewards':''}">${Object.entries(obj).filter(([,v])=>v!==0).map(([k,v])=>`<span title="${esc(RESOURCES[k]?.name||k)}" class="${!reward&&game.s.resources[k]<v?'missing':''}">${icon(RESOURCES[k]?.icon||'spark',14)}${reward&&v>0?'+':''}${esc(resValue(k,v))} ${esc(k==='capital'?'':RESOURCES[k]?.short||k)}</span>`).join('')}</div>`;}
function blocked(p){return p.blocked?.length?`<p class="block-reason">${icon('lock',12)} ${esc(p.blocked[0])}${p.blocked.length>1?` <span title="${esc(p.blocked.join(' · '))}">(+${p.blocked.length-1})</span>`:''}</p>`:'';}
function info(text,kind='',ico='help'){return `<div class="info-strip ${kind}">${icon(ico,21)}<div>${text}</div></div>`;}
function empty(title,text,button=''){return `<div class="empty">${icon('orbit',35)}<h3>${esc(title)}</h3><p>${esc(text)}</p>${button}</div>`;}
function tile(ico,title,sub='',cls=''){return `<div class="card-header"><div class="tile-icon ${cls}">${icon(ico,23)}</div><div><h3>${esc(title)}</h3>${sub?`<span class="sub">${esc(sub)}</span>`:''}</div></div>`;}
function selector(){return `<div class="toolbar country-selector"><label>${icon('globe',16)} Target <select class="field" data-setting="selected" aria-label="Target country">${world.defs.map(c=>`<option value="${esc(c.id)}" ${ui.selected===c.id?'selected':''}>${esc(c.name)}</option>`).join('')}</select></label>${badge(region(game.country(ui.selected).bloc),'purple')}</div>`;}
const stat=(label,value,bar=null,color='')=>`<div class="stat-row"><span>${esc(label)}</span><strong>${esc(value)}</strong></div>${bar!==null?meter(bar,color):''}`;
const previewButton=(kind,id,label,extra='')=>btn(`${label} ${icon('chevron',14)}`,'preview',`${attr('kind',kind)} ${attr('id',id)} ${extra}`,'secondary small');
const titleOfJob=j=>j.kind==='op'?OPERATIONS[j.subtype].name:j.kind==='research'?TECHS[j.subtype].name:j.kind==='base'?BASES[j.subtype].name:j.kind==='module'?MODULES[j.subtype].name:j.kind==='craft'?CRAFT[j.subtype].name:j.kind==='agent'?'Biological interface':j.kind==='agent_action'?'Interface assignment':j.kind==='blueveil'?'Project Blue Veil':j.kind==='project'?PROJECTS[j.subtype].name:'Emergency salvage';

function toast(text,kind='success'){const el=document.createElement('div');el.className=`toast ${kind}`;el.innerHTML=`${icon(kind==='warning'?'alert':'check',18)}<span>${esc(text)}</span>`;$('toast-stack').appendChild(el);while($('toast-stack').children.length>3)$('toast-stack').firstChild.remove();setTimeout(()=>{el.classList.add('out');setTimeout(()=>el.remove(),280);},4200);}
function notices(){if(!game)return;const q=game.s.notices.splice(0);for(const n of q)toast(n.text,n.type);if(q.length)audio.play(q.some(x=>x.type==='warning')?'warning':'success');}
function persist(silent=true,rotate=false){if(!game?.s.started)return false;try{if(rotate){const old=localStorage.getItem(SAVE);if(old){localStorage.setItem(SAVE+'-backup2',localStorage.getItem(SAVE+'-backup1')||old);localStorage.setItem(SAVE+'-backup1',old);}}game.s.lastSave=game.s.day;localStorage.setItem(SAVE,game.export());if(!silent)toast('Campaign saved on this browser.');return true;}catch{if(!saveWarning||!silent){toast('Browser storage is unavailable. Export a save from Settings.','warning');saveWarning=true;}return false;}}
function hasSave(){try{return !!localStorage.getItem(SAVE);}catch{return false;}}
function download(name,text,type='application/json'){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),3000);}
function apply(result,close=true){notices();if(!result?.ok)return;if(close){closeModal();closeDrawer();}renderAll();persist(true);}
function select(id,focus=true){if(!game.country(id))return;ui.selected=id;if(focus)globe?.focus(id);renderHUD();if(ui.screen)renderDrawer();}
function pause(){if(game)game.s.speed=0;accumulator=0;}
function setSpeed(speed){if(!game||ui.title)return;if(game.s.ended){showEnding();return;}if(game.s.eventQueue.length){showEvent();return;}if(ui.modal)return;game.s.speed=speed;game.s.started=true;accumulator=0;renderHUD();audio.play();}
function enterGame(){ui.title=false;document.body.classList.remove('title-mode');closeModal();closeDrawer();globe?.focus(ui.selected,true);renderAll();audio.play('start');persist(true);}
function openDrawer(screen,tab=null){if(!game||ui.title||!screens[screen])return;pause();ui.screen=screen;ui.tab=tab||tabs[screen][0][0];$('drawer').hidden=false;$('drawer-scrim').hidden=false;renderDrawer();renderHUD();$('drawer-close').focus({preventScroll:true});}
function closeDrawer(){ui.screen=null;ui.tab=null;$('drawer').hidden=true;$('drawer-scrim').hidden=true;renderNav();}
function showModal(kind,html,data={}){pause();ui.modal={kind,...data};$('modal-body').innerHTML=html;$('modal').hidden=false;$('modal-scrim').hidden=false;const first=$('modal').querySelector('input,select,button:not(:disabled)');setTimeout(()=>first?.focus({preventScroll:true}),20);renderHUD();}
function closeModal(force=false){if(!force&&ui.modal?.kind==='event'&&game?.s.eventQueue.length)return;ui.modal=null;$('modal').hidden=true;$('modal-scrim').hidden=true;eventSeen=null;}
function modalHead(eye,title,closable=true){return `<div class="modal-head"><div><span class="eyebrow">${esc(eye)}</span><h2>${esc(title)}</h2></div>${closable?`<button class="icon-btn" data-action="close-modal" aria-label="Close">${icon('close',19)}</button>`:''}</div>`;}
function renderNav(){if(!$('nav-rail'))return;$('nav-rail').innerHTML=Object.entries(screens).map(([id,[title,ico]])=>`<button class="nav-item ${ui.screen===id?'active':''}" data-action="open" data-screen="${id}" title="${esc(title)}" aria-label="${esc(title)}" ${ui.screen===id?'aria-current="page"':''}>${icon(ico,23)}<span>${{world:'Earth',bases:'Bases',fleet:'Fleet',agents:'Agents',diplomacy:'Contact',economy:'Market',research:'Research',narratives:'Stories',archive:'Archive',endgame:'Future'}[id]}</span></button>`).join('');}
function renderHUD(){if(!game)return;const s=game.s,c=game.country(ui.selected)||game.country('840'),control=game.control(),rates=game.rates();
 $('sound-button').innerHTML=icon(s.settings.sound?'sound':'mute',18);$('sound-button').setAttribute('aria-label',s.settings.sound?'Mute sound':'Enable sound');document.body.classList.toggle('reduced-motion',s.settings.reducedMotion);audio.set(s.settings.sound,s.settings.music);audio.intensity=s.metrics.evidence;
 $('top-resources').innerHTML=['energy','intel','influence','capital','exotic'].map(k=>`<button class="resource-pip" data-action="open" data-screen="economy" title="${esc(RESOURCES[k].name)}: ${resValue(k,s.resources[k])}. ${rates[k]>=0?'+':''}${(rates[k]*30).toFixed(1)} per 30 days. Capacity ${fmt(game.capacity(k))}." style="--rcolor:${RESOURCES[k].color}">${icon(RESOURCES[k].icon,22)}<span><strong>${resValue(k,s.resources[k])}</strong><small>${esc(RESOURCES[k].short)}</small></span></button>`).join('')+`<button class="resource-pip command" data-action="open" data-screen="world" title="Active command slots / total slots">${icon('command',21)}<span><strong>${game.commandUsed()} / ${game.command()}</strong><small>COMMAND</small></span></button>`;
 $('era-title').textContent=game.era.name;$('era-description').textContent=game.era.desc||'A small beginning. A very big secret.';
 $('world-eyebrow').textContent=`SOL SYSTEM / PLANET 03 · ${game.year}–2045`;
 const g=GUIDE[s.guide];$('directive').innerHTML=g?`<div class="directive-top"><span class="eyebrow">YOUR NEXT SMALL STEP</span><span class="directive-badge">${s.guide+1} / ${GUIDE.length}</span></div><h3>${esc(g.title)}</h3><p>${esc(g.text)}</p>${g.test(s)?costs(g.reward,true):''}${btn(g.test(s)?`${icon('spark',15)} Claim supply cache`:`${icon('arrow',15)} ${esc(g.goal)}`,g.test(s)?'claim-guide':'guide','','primary wide')}`:`${mascot(64)}<div class="directive-top"><span class="eyebrow">THE LONG GAME</span>${badge(`${Math.round(control.total)}%`)}</div><h3>A very quiet takeover.</h3><p>Expand across regions. Choose your final project before the end of 2045.</p>${btn('Plan the future '+icon('arrow',14),'open','data-screen="endgame"','secondary wide')}`;
 const contact=['Uncontacted','Suspected presence','Backchannel','Limited contact','Secret accord','Strategic partner'][c.contact]||'Unknown';
 $('country-panel').innerHTML=`<span class="eyebrow">${esc(region(c.bloc))}</span><div class="country-head"><div class="country-symbol">${icon(game.treaty(c.id)?'chat':'globe',26)}</div><h2>${esc(c.name)}</h2></div>${badge(contact,game.treaty(c.id)?'':'neutral')}<div class="detail-desktop"><div class="divider"></div><p>${esc(BLOCS[c.bloc].tag||'An independent strategic actor')}</p>${stat('Intelligence coverage',Math.round(c.insight)+'%',c.insight)}${stat('Relationship',Math.round(c.trust)+(c.trust>=45?' · cooperative':''))}${stat('Classified knowledge',game.knowledge(c))}${stat('Sensor pressure',Math.round(game.sensor(c))+'%',game.sensor(c),'#ceb17c')}${stat('Hostility',Math.round(c.hostility)+'%',c.hostility,'#d39a87')}<div class="divider"></div><div class="tags">${badge(c.surveyed?'Site surveyed':'Unsurveyed',c.surveyed?'':'neutral')}${badge(game.legal(c.id)?'Market access':'No legal cover',game.legal(c.id)?'gold':'neutral')}</div></div><div class="country-actions">${btn(`Plan operation ${icon('arrow',15)}`,'open','data-screen="world"','primary')}${btn(`Secret diplomacy ${icon('chat',15)}`,'open','data-screen="diplomacy"','secondary')}${btn(`Choose country ${icon('globe',15)}`,'open','data-screen="world" data-tab="countries"','secondary')}</div>`;
 const exposure=s.open?'Open presence':s.metrics.evidence>=55?'Institutional crisis':s.metrics.evidence>=25?'Credible mystery':s.metrics.belief>=20?'Contested':'Folklore';
 $('world-status').innerHTML=`${badge(`${Math.round(control.total)}% control`)} ${badge(`Evidence ${Math.round(s.metrics.evidence)}%`,s.metrics.evidence>=55?'red':'gold')} <span>${esc(exposure)}</span>`;
 $('time-panel').innerHTML=`<div class="calendar">${date(s.day)}<small>${s.speed?`${s.pace*s.speed} DAYS / SECOND`:'PAUSED · SPACE TO RESUME'}</small></div><div class="time-controls"><button class="play-control" data-action="play" aria-label="${s.speed?'Pause':'Resume'}">${icon(s.speed?'pause':'play',15)}</button>${[1,2,4,8].map(n=>`<button data-action="speed" data-speed="${n}" class="${s.speed===n?'active':''}" aria-label="Speed ${n} times">${n}×</button>`).join('')}</div>`;
 $('operation-strip').innerHTML=s.jobs.length?s.jobs.slice(0,5).map(j=>`<button class="job-chip" data-action="job" data-id="${esc(j.id)}"><strong>${esc(titleOfJob(j))}</strong><small><span>${esc(j.country?sname(j.country):'Network queue')}</span><span>${dur(j.finish-s.day)}</span></small>${meter((s.day-j.start)/j.duration*100,j.kind==='research'?'#ae9fcf':'#95b48d')}</button>`).join('')+(s.jobs.length>5?btn(`+${s.jobs.length-5}`,'queue','','secondary small'):''):`<button class="idle-chip" data-action="open" data-screen="world">${icon('ufo',24)}<span>No active missions.<br>Your fleet is ready when you are.</span></button>`;
 $('layer-button').innerHTML=`${icon('layers',15)} ${esc(layers[globe?.layer||'political'][0])} ${icon('chevron',12)}`;
 if(globe)globe.update(game,ui.selected,ui.title);
}
function renderAll(){renderNav();renderHUD();if(ui.screen)renderDrawer();notices();}
function tabButtons(){return tabs[ui.screen].map(([id,name])=>`<button class="tab ${ui.tab===id?'active':''}" data-action="tab" data-tab="${id}">${esc(name)}</button>`).join('');}
function renderDrawer(){if(!ui.screen)return;const scroll=$('drawer-body').scrollTop;const [title,,desc]=screens[ui.screen];$('drawer-title').textContent=title;$('drawer-description').textContent=desc;$('drawer-tabs').innerHTML=tabButtons();$('drawer-eyebrow').textContent=`NETWORK MANAGEMENT / ${game.year}`;
 const renderers={world:worldPanel,bases:basePanel,fleet:fleetPanel,agents:agentPanel,diplomacy:diplomacyPanel,economy:economyPanel,research:researchPanel,narratives:narrativePanel,archive:archivePanel,endgame:endgamePanel};$('drawer-body').innerHTML=renderers[ui.screen]();$('drawer-body').scrollTop=scroll;renderNav();}
function worldPanel(){const c=game.country(ui.selected);if(ui.tab==='countries'){const query=ui.search.toLowerCase();const cs=game.countries().filter(c=>(ui.bloc==='all'||c.bloc===ui.bloc)&&c.name.toLowerCase().includes(query));return `<div class="toolbar"><input class="field search-field" data-input="country-search" aria-label="Search countries" placeholder="Find a country or territory…" value="${esc(ui.search)}"><select class="field" data-setting="bloc" aria-label="Filter strategic region"><option value="all">All regions</option>${Object.keys(BLOCS).map(k=>`<option value="${k}" ${ui.bloc===k?'selected':''}>${esc(region(k))}</option>`).join('')}</select></div><div class="section-heading"><h3>Where next?</h3><small>${cs.length} countries & territories</small></div><div id="country-results">${cs.map(c=>`<button class="list-row country-row" data-action="select-country" data-id="${esc(c.id)}"><span class="tile-icon" style="background:${BLOCS[c.bloc].color}55">${icon('globe',20)}</span><div><strong>${esc(c.name)}</strong><small>${esc(region(c.bloc))} · Intel ${Math.round(c.insight)}%</small></div>${badge(game.treaty(c.id)?'Partner':c.hostility>=65?'Hostile':c.contact>=2?'Contact':'Unknown',c.hostility>=65?'red':game.treaty(c.id)?'':'neutral')}${icon('chevron',15)}</button>`).join('')||empty('No matching location','Try a shorter name or another region.')}</div><p class="note">Geography uses a fixed modern cartographic baseline. Regional personalities and capacities are fictional scenario abstractions, not rankings of real populations.</p>`;}
 if(ui.tab==='layers')return `<div class="grid">${Object.entries(layers).map(([id,[name,desc]])=>`<article class="card">${tile('layers',name,globe?.layer===id?'CURRENT VIEW':'MAP OVERLAY')}<p>${esc(desc)}</p>${btn(`Use ${esc(name.toLowerCase())}`,'set-layer',attr('id',id),globe?.layer===id?'primary small':'secondary small')}</article>`).join('')}</div>`;
 return selector()+info(`Operations automatically assign an available compatible craft. You have <strong>${game.command()-game.commandUsed()} free command slots</strong>. Planning pauses time; launching resumes it.`)+`<div class="grid">${Object.entries(OPERATIONS).map(([id,d])=>{const p=game.opPreview(id,c.id);return `<article class="card">${tile(d.icon,d.name,`${dur(p.days)} · ${p.asset?p.asset.name:d.craft?'Craft required':'Human channel'}`)}<p>${esc(d.desc)}</p>${costs(p.cost)}<div class="progress-label"><span>Detection estimate</span><strong>${p.range?.join('–')||'?'}%</strong></div>${meter(p.risk,'#c7af7a')}${blocked(p)}<div class="card-actions">${previewButton('op',id,'Plan operation')}</div></article>`;}).join('')}</div>`;}
function basePanel(){const s=game.s;if(ui.tab==='build')return selector()+info(`Fabrication: <strong>${game.buildersUsed()} / ${game.builders()} slots in use</strong>. Ground installations need a surveyed site. Ocean sites use an offshore logistics location.`)+`<div class="grid">${Object.entries(BASES).map(([id,d])=>{const p=game.buildPreview(id,ui.selected);return `<article class="card">${tile(d.icon,d.name,`${dur(p.days)} · ${d.slots} module sockets`)}<p>${esc(d.desc)}</p>${costs(p.cost)}<p class="note">Baseline signature ${d.signature}. ${Object.entries(d.yield).map(([k,v])=>`${RESOURCES[k].short} +${(v*30).toFixed(1)}/month`).join(' · ')}</p>${blocked(p)}${previewButton('base',id,'Plan installation')}</article>`;}).join('')}</div>`;
 if(!s.bases.length)return empty('No active infrastructure','Your network has no active installation.');if(!s.bases.some(b=>b.id===ui.base))ui.base=s.bases[0].id;const b=s.bases.find(b=>b.id===ui.base),def=BASES[b.type],used=Object.values(b.modules).reduce((a,b)=>a+b,0);return `<div class="toolbar"><label>Installation <select class="field" data-setting="base">${s.bases.map(b=>`<option value="${b.id}" ${ui.base===b.id?'selected':''}>${esc(b.name)} · ${esc(sname(b.country))}</option>`).join('')}</select></label>${btn(icon('plus',14)+' New base','tab','data-tab="build"','secondary small')}</div><div class="card">${tile(def.icon,b.name,`${def.name} · logistics ${sname(b.country)}`)}<div class="mini-stats"><div class="mini-stat"><strong>${used} / ${def.slots}</strong><small>Module sockets</small></div><div class="mini-stat"><strong>${Math.round(b.search)}%</strong><small>Human search progress</small></div><div class="mini-stat"><strong>${Math.round(b.health)}%</strong><small>Structural integrity</small></div></div>${stat('Detection signature',game.baseSignature(b).toFixed(1),game.baseSignature(b)*3,'#cdbb7b')}<div class="card-actions">${btn('Locate on Earth','locate-base',attr('id',b.id),'secondary small')}${btn('Evacuate installation','confirm-evacuate',attr('id',b.id),'danger small')}</div></div><div class="section-heading" style="margin-top:24px"><h3>Make yourself at home.</h3><small>${game.builders()-game.buildersUsed()} fabrication slots free</small></div><div class="grid">${Object.entries(MODULES).map(([id,d])=>{const p=game.modulePreview(b.id,id);return `<article class="card">${tile(d.icon,d.name,`Installed level ${b.modules[id]||0} / 3 · ${dur(p.days)}`)}<p>${esc(d.desc)}</p>${costs(p.cost)}${blocked(p)}<div class="card-actions">${previewButton('module',id,b.modules[id]?'Upgrade module':'Add module',attr('base',b.id))}</div></article>`;}).join('')}</div>`;}
function fleetPanel(){const s=game.s;if(ui.tab==='build')return info(`Exotic Substrate cannot be bought on human markets. Build with care. <strong>${game.builders()-game.buildersUsed()} fabrication slots</strong> available.`)+`<div class="grid">${Object.entries(CRAFT).map(([id,d])=>{const p=game.craftPreview(id);return `<article class="card">${tile(d.icon,d.name,`${dur(p.days)} · stealth ${Math.round(d.stealth*100)}%`,'purple')}<p>${esc(d.desc)}</p>${costs(p.cost)}${blocked(p)}<div class="card-actions">${previewButton('craft',id,'Fabricate craft')}</div></article>`;}).join('')}</div>`;
 return `<div class="mini-stats"><div class="mini-stat"><strong>${s.craft.length}</strong><small>Network craft</small></div><div class="mini-stat"><strong>${s.craft.filter(a=>!a.busy).length}</strong><small>Ready for tasking</small></div><div class="mini-stat"><strong>${s.stats.losses||0}</strong><small>Losses remembered</small></div></div>${s.craft.length?`<div class="grid">${s.craft.map(a=>{const d=CRAFT[a.type],j=s.jobs.find(j=>j.id===a.busy);return `<article class="card">${tile(d.icon,a.name,d.name,'purple')}${badge(j?'On assignment':'Ready',j?'purple':'')}${stat('Integrity',`${Math.round(a.health)}%`,a.health)}<p>${j?`${esc(titleOfJob(j))} in ${esc(sname(j.country))}. Returning in ${dur(j.finish-s.day)}.`:esc(d.desc)}</p><div class="card-actions">${j?btn('Assignment','job',attr('id',j.id),'secondary small'):btn('Send on mission','open','data-screen="world"','primary small')}${btn('Repair · 3 metal, 1 rare, 8 energy','repair',attr('id',a.id),'secondary small',!!a.busy||a.health>=100)}${btn('Recycle','confirm-recycle',attr('id',a.id),'secondary small',!!a.busy)}</div></article>`;}).join('')}</div>`:empty('Your hangar is very quiet','Fabricate a Scout Orb or recover materials from a local debris cache.') }<div class="section-heading" style="margin-top:20px"><h3>A useful safety net</h3></div>${info('Emergency salvage uses your Recovery Bay, not a fleet slot. It provides a modest material cache every two years. A power core continues producing energy when supplies are low.')}<div class="card-actions">${btn(icon('plus',16)+' Fabricate a craft','tab','data-tab="build"','primary')}${btn('Emergency salvage · 12 Energy','emergency','','secondary')}</div>`;}
function agentPanel(){const s=game.s;if(ui.tab==='recruit')return selector()+`<div class="toolbar"><label>Institution <select class="field" data-setting="institution">${Object.entries(INSTITUTIONS).map(([id,n])=>`<option value="${id}" ${ui.institution===id?'selected':''}>${n}</option>`).join('')}</select></label></div>`+info('An interface needs a Bio-Lab, a researched human-compatible body, and an observed target. Fabrication is followed by a real cover career; promotion and policy actions unlock after that career.')+`<div class="grid">${Object.entries(INFILTRATION).map(([id,d])=>{const p=game.agentPreview(id,ui.selected,ui.institution);return `<article class="card">${tile('agent',d.name,d.tag,'purple')}<p>${esc(d.desc)}</p><p class="note">Fabrication ${dur(p.days)} + career ${dur(p.careerDays)}.</p><div class="stats-two">${stat('Cover',d.cover+'%')}${stat('Starting access',d.access+'%')}${stat('Suspicion',d.suspicion+'%')}${stat('Human attachment',d.attachment+'%')}</div>${costs(p.cost)}${blocked(p)}<div class="card-actions">${previewButton('agent',id,'Create interface')}</div></article>`;}).join('')}</div>`;
 return info('Human attachment builds better social cover, but coercive orders can strain loyalty. A long-lived colleague may eventually ask you to treat humanity differently.')+(s.agents.length?`<div class="grid">${s.agents.map(a=>`<article class="card"><div class="card-header">${portrait(a.name,52)}<div><h3>${esc(a.name)}</h3><span class="sub">${esc(INSTITUTIONS[a.institution])} · ${esc(sname(a.country))}</span></div></div>${badge(a.phase==='active'?'Embedded':'Building a career',a.phase==='active'?'':'purple')}${a.autonomous?' '+badge('Trusted autonomy','gold'):''}${a.phase==='career'?`<div class="progress-label"><span>Cover career</span><strong>${dur(a.careerDays-a.progress)} remaining</strong></div>${meter(a.progress/a.careerDays*100,'#b1a0cd')}`:''}<div class="stats-two">${stat('Access',Math.round(a.access)+'%')}${stat('Cover',Math.round(a.cover)+'%')}${stat('Loyalty',Math.round(a.loyalty)+'%')}${stat('Attachment',Math.round(a.attachment)+'%')}${stat('Suspicion',Math.round(a.suspicion)+'%')}${stat('Adaptation',Math.round(a.adaptation)+'%')}</div><p class="note">${a.busy?'Currently assigned.':INFILTRATION[a.method].name}</p><div class="card-actions">${btn('Seek promotion','agent-action',`${attr('id',a.id)} data-kind="promote"`,'secondary small',a.phase!=='active'||!!a.busy)}${btn('Steer policy','agent-action',`${attr('id',a.id)} data-kind="policy"`,'primary small',a.phase!=='active'||!!a.busy)}${btn('Recall','confirm-recall',attr('id',a.id),'secondary small',!!a.busy)}</div></article>`).join('')}</div>`:empty('Your next colleague is not quite born.','Create a biological interface, choose an institution and let a human life begin.',btn('Create an identity','tab','data-tab="recruit"','primary')));}
function diplomacyPanel(){const s=game.s,c=game.country(ui.selected);if(ui.tab==='relations'){return info('A partnership with one member does not grant control over its region. Strength and friction describe fictional institutional incentives. Human research remains private until you establish enough intelligence access.')+`<div class="grid">${Object.entries(BLOCS).map(([id,b])=>{const cs=game.countries().filter(c=>c.bloc===id),known=cs.filter(c=>c.contact>=2),allies=cs.filter(c=>game.treaty(c.id));return `<article class="card">${tile('flag',region(id),`${cs.length} locations · ${allies.length} accords`)}<p>${esc(b.desc)}</p><p><strong>Opportunity:</strong> ${esc(b.strength)}</p><p><strong>Friction:</strong> ${esc(b.friction)}</p><div class="tags">${badge(`Technology appetite ${b.appetite}`,'gold')}${badge(`Sovereignty sensitivity ${b.sovereignty}`,'purple')}</div>${known.length?`<div class="divider"></div>${known.slice(0,6).map(c=>`<div class="stat-row"><button class="text-button" data-action="negotiate-country" data-id="${esc(c.id)}">${esc(c.name)}</button><span>Trust ${Math.round(c.trust)}</span></div>`).join('')}`:'<p class="note">No established backchannels.</p>'}${btn('Explore this region','filter-bloc',attr('id',id),'secondary small')}</article>`;}).join('')}</div>`;}
 if(ui.tab==='agreements')return s.treaties.length?`<div class="grid">${[...s.treaties].reverse().map(t=>{const c=game.country(t.country);return `<article class="card">${tile('chat',c.name,`Expires ${date(t.expiry)}`)}${badge(t.active?'Active secret accord':'Inactive',t.active?'':'neutral')}<div class="divider"></div><div class="tags">${t.clauses.map(k=>badge(CLAUSES[k].name)).join('')}</div><div class="stats-two">${stat('Trust',Math.round(c.trust))}${stat('Dependency',Math.round(c.dependence)+'%')}</div><div class="card-actions">${btn('Renew · 12 Influence + 8 Intel','renew',attr('id',t.id),'secondary small',t.active&&t.expiry-s.day>730)}${btn('End agreement','confirm-break',attr('id',t.id),'danger small',!t.active)}</div></article>`;}).join('')}</div>`:empty('No secret handshakes. Yet.','Observe, open a backchannel, cultivate trust, then make an offer.',btn('Open negotiations','tab','data-tab="negotiate"','primary'));
 const p=game.proposalPreview(c.id,ui.clauses,ui.offer),t=game.treaty(c.id);return selector()+`<div class="card">${tile('chat',c.name,region(c.bloc))}<p>${esc(BLOCS[c.bloc].desc)}</p><div class="mini-stats"><div class="mini-stat"><strong>${Math.round(c.trust)}</strong><small>Trust · −100 to +100</small></div><div class="mini-stat"><strong>${c.contact} / 5</strong><small>Contact level</small></div><div class="mini-stat"><strong>${game.knowledge(c)}</strong><small>Knowledge estimate</small></div></div><div class="card-actions">${previewButton('op','observe','Observe')}${previewButton('op','contact','Open a backchannel')}${previewButton('op','cultivate','Cultivate trust')}${previewButton('op','reassure','Reassure')}</div>${c.memory.length?`<p class="note">They remember: ${esc(c.memory[0])}</p>`:''}</div>${t?info(`<strong>An accord is already active.</strong> ${t.clauses.map(k=>esc(CLAUSES[k].name)).join(' · ')}. Renew or end it in Agreements.`):`<div class="section-heading" style="margin-top:24px"><h3>Build a secret accord.</h3><small>Choose 1–4 clauses</small></div><div class="grid">${Object.entries(CLAUSES).map(([id,d])=>`<label class="clause"><input type="checkbox" data-clause="${id}" ${ui.clauses.includes(id)?'checked':''}><span><strong>${esc(d.name)}</strong><small>${esc(d.desc)}</small></span></label>`).join('')}</div><div class="toolbar" style="margin-top:18px"><label>Your offer <select class="field" data-setting="offer"><option value="intel" ${ui.offer==='intel'?'selected':''}>Useful intelligence</option><option value="capital" ${ui.offer==='capital'?'selected':''}>Human capital</option><option value="sample" ${ui.offer==='sample'?'selected':''}>A technology sample</option></select></label></div><div class="card"><div class="split-heading"><h3>A mutually useful secret.</h3>${badge(p.chance+'% acceptance','gold')}</div>${costs(p.cost)}<p>Offers consume resources even when declined. A sample improves the offer, but accelerates human research and worries your other partners.</p>${blocked(p)}<div class="card-actions">${btn('Send proposal '+icon('arrow',15),'propose','','primary',p.blocked.length>0)}</div></div>`}`;}
function economyPanel(){const s=game.s,rates=game.rates();if(ui.tab==='companies')return info('Front companies unlock lawful market orders and earn capital daily. Expanding increases income and economic leverage; diversifying records lowers financial trace.')+(s.fronts.length?`<div class="grid">${s.fronts.map(f=>`<article class="card">${tile('factory',f.name,`${sname(f.country)} · scale ${f.level} / 5`,'gold')}${stat('Procurement cover',Math.round(f.cover)+'%',f.cover)}<p>${esc(f.name)} is a thoroughly unremarkable human company. Please do not examine the ownership structure too closely.</p><div class="card-actions">${btn(`Expand · $${f.level*25}m + ${f.level*5} Influence`,'upgrade-front',attr('id',f.id),'primary small',f.level>=5)}${btn('Clean records · $12m + 8 Intel','front-cover',attr('id',f.id),'secondary small')}</div></article>`).join('')}</div>`:empty('No human bank account. Quite inconvenient.','Research Legal Identities, survey a country, and establish a front. Your first firm starts with a small sale of precious metals.'))+`<div class="divider"></div>${selector()}${previewButton('op','front','Establish a front company')}`;
 return `<div class="resource-grid">${Object.entries(RESOURCES).map(([k,r])=>`<div class="resource-card"><div class="top">${icon(r.icon,19)}${esc(r.name)}</div><strong>${resValue(k,s.resources[k])}</strong><small>${rates[k]>=0?'+':''}${(rates[k]*30).toFixed(1)} / month · capacity ${fmt(game.capacity(k))}</small><div style="margin-top:10px">${meter(s.resources[k]/game.capacity(k)*100,r.color)}</div></div>`).join('')}</div><div class="section-heading"><h3>The human market</h3>${badge(game.legal()?'Procurement unlocked':'Legal access required',game.legal()?'':'gold')}</div>${info('Buy and sell prices include a spread. Large orders raise your market footprint and local prices. Capital is denominated in millions of abstract campaign dollars. Exotic Substrate is never sold here.')}<div class="card">${Object.keys(s.prices).map(k=>`<div class="market-row"><strong>${icon(RESOURCES[k].icon,17)}${esc(RESOURCES[k].short)}</strong><span>$${game.marketPrice(k,true).toFixed(2)}m<small>sell $${game.marketPrice(k,false).toFixed(2)}m</small></span><input class="field" type="number" id="order-${k}" value="5" min="1" max="100" step="1" aria-label="${esc(RESOURCES[k].name)} order quantity">${btn('Buy','trade',`${attr('id',k)} data-buy="1"`,'primary small',!game.legal())}${btn('Sell','trade',`${attr('id',k)} data-buy="0"`,'secondary small',!game.legal())}</div>`).join('')}${stat('Market footprint',`${Math.round(s.footprint)} / 200`,s.footprint/2,'#ceb77a')}<p class="note">Footprint slowly falls as records age. Research Procurement Cover or invest in front-company cover to keep purchases ordinary.</p></div><div class="card-actions">${previewButton('op','mine','Acquire by mining')}${previewButton('op','salvage','Reclaim Exotic Substrate')}${btn('Emergency salvage','emergency','','secondary small')}</div>`;}
function researchPanel(){const s=game.s;const treeList=ui.tree==='all'?TREES:TREES.filter(t=>t.id===ui.tree);return `<div class="mini-stats"><div class="mini-stat"><strong>${s.researched.length} / ${Object.keys(TECHS).length}</strong><small>Discoveries</small></div><div class="mini-stat"><strong>${s.jobs.filter(j=>j.kind==='research').length} / ${game.tech('information3')?2:1}</strong><small>Research capacity</small></div><div class="mini-stat"><strong>${game.year}</strong><small>Human era</small></div></div><div class="toolbar"><label>Discipline <select class="field" data-setting="tree"><option value="all">All research trees</option>${TREES.map(t=>`<option value="${t.id}" ${ui.tree===t.id?'selected':''}>${esc(t.name)}</option>`).join('')}</select></label></div>${ui.tree==='all'?`<div class="grid">${treeList.map(t=>{const nodes=Object.values(TECHS).filter(n=>n.tree===t.id),next=nodes.find(n=>!game.tech(n.id));return `<article class="card">${tile(t.icon,t.name,`${nodes.filter(n=>game.tech(n.id)).length} / 6 discoveries`,'purple')}<p>${next?`Next: <strong>${esc(next.name)}</strong><br>${esc(next.desc)}`:'A complete discipline. A little less uncertainty.'}</p><div class="tier-track">${nodes.map(n=>`<span class="tier-dot ${game.tech(n.id)?'done':''}" title="${esc(n.name)}"></span>`).join('')}</div><div class="card-actions">${btn('Explore discipline','research-tree',attr('id',t.id),'secondary small')}${next?previewButton('research',next.id,'Research next'):badge('Complete')}</div></article>`;}).join('')}</div>`:`<div class="grid">${Object.values(TECHS).filter(t=>t.tree===ui.tree).map(t=>{const p=game.researchPreview(t.id),complete=game.tech(t.id),j=s.jobs.find(j=>j.kind==='research'&&j.subtype===t.id);return `<article class="card ${complete?'complete-card':p.blocked.length?'locked-card':''}"><div class="card-header"><span class="ordinal">0${t.tier}</span><div><h3>${esc(t.name)}</h3><span class="sub">Available ${t.year} · ${dur(p.days)}</span></div></div><p>${esc(t.desc)}</p>${complete?badge('Researched'):j?`<div class="progress-label"><span>Researching</span><span>${dur(j.finish-s.day)}</span></div>${meter((s.day-j.start)/j.duration*100,'#b1a0cd')}`:`${costs(p.cost)}${blocked(p)}<div class="card-actions">${previewButton('research',t.id,'Review research')}</div>`}</article>`;}).join('')}</div>`}`;}
function exposureGraph(){const nodes=game.s.evidence.filter(e=>!e.contained).slice(-14),positions=nodes.map((e,i)=>({e,x:47+(i%7)*91,y:52+Math.floor(i/7)*80}));return `<svg class="evidence-graph" viewBox="0 0 650 185" role="img" aria-label="Evidence connections by shared location or signature">${positions.flatMap((a,i)=>positions.slice(i+1).filter(b=>a.e.country===b.e.country||a.e.tag===b.e.tag).map(b=>`<path d="M${a.x} ${a.y} Q325 92 ${b.x} ${b.y}" fill="none" stroke="#aab9a0" stroke-width="1" opacity=".5"/>`)).join('')}${positions.map(({e,x,y},i)=>`<g><circle cx="${x}" cy="${y}" r="${7+Math.min(e.strength,9)}" fill="${e.public?'#dca88b':'#aba1c9'}" stroke="#fffdf2" stroke-width="3"/><text x="${x}" y="${y+29}" text-anchor="middle" font-size="9" fill="#687c64">${esc(e.type)} ${i+1}</text><title>${esc(e.name)}</title></g>`).join('')}${!nodes.length?'<text x="325" y="96" text-anchor="middle" fill="#68816c" font-size="13">No uncontained evidence. A beautifully empty file.</text>':''}</svg>`;}
function narrativePanel(){const s=game.s;if(ui.tab==='exposure')return `<div class="mini-stats">${[['belief','Belief'],['evidence','Hard evidence'],['coherence','Coherence']].map(([k,n])=>`<div class="mini-stat"><strong>${Math.round(s.metrics[k])}%</strong><small>${n}</small></div>`).join('')}</div>${info('Public belief can climb while proof stays weak. Contamination fragments an explanation, but does not delete a published artifact or authenticated video. Repeated noise teaches investigators what to look for.')}<div class="card">${stat('Global panic',`${Math.round(s.metrics.panic)}%`,s.metrics.panic,'#d69d86')}${stat('Public trust in NHI',`${Math.round(s.metrics.trust)}%`,s.metrics.trust)}${stat('Pattern signature',`${Math.round(s.pattern)}%`,s.pattern,'#baabd0')}${stat('Financial footprint',`${Math.round(s.footprint)} / 200`,s.footprint/2,'#cfb36f')}<p class="note">${s.open?'Your presence is established. Diplomacy and legitimacy still offer a future.':'Disclosure pressure becomes critical when public Evidence and Coherence both reach 65%.'}</p></div><div class="section-heading" style="margin-top:22px"><h3>The threads humans can pull</h3></div>${exposureGraph()}${btn('Inspect the archive','open','data-screen="archive" data-tab="evidence"','secondary')}`;
 if(ui.tab==='people')return info('These are fictional satirical characters. They are not claims about real people. Each becomes active in its own era. Interventions have a one-year cooldown.')+`<div class="grid">${CHARACTERS.map(ch=>{const active=game.year>=ch.year;return `<article class="card ${!active?'locked-card':''}"><div class="card-header">${portrait(ch.name,52)}<div><h3>${esc(ch.name)}</h3><span class="sub">${esc(ch.role)}</span></div></div><p>${esc(ch.desc)}</p><div class="tags">${badge('Reach '+ch.reach,'gold')}${badge('Credibility '+ch.credibility,'purple')}${badge(active?'Active':`From ${ch.year}`,active?'':'neutral')}</div><div class="card-actions">${btn('Monitor','character',`${attr('id',ch.id)} data-kind="monitor"`,'secondary small',!active)}${btn('Contact','character',`${attr('id',ch.id)} data-kind="contact"`,'secondary small',!active)}${btn('Misdirect','character',`${attr('id',ch.id)} data-kind="misdirect"`,'secondary small',!active)}</div></article>`;}).join('')}</div>`;
 if(ui.tab==='blue'){const p=game.bluePreview();return `<div class="card">${tile('eye','Project Blue Veil','LATE-GAME NARRATIVE OPERATION','purple')}<p>A fabricated public revelation, orchestrated through your orbital systems and human channels. It can redirect skepticism, prepare contact, or manufacture a common threat.</p>${costs(p.cost)}<p class="note">365 days · 2 Command slots · orbital base · media agent or level-3 front. Every version can backfire a year later.</p>${blocked(p)}</div><div class="grid" style="margin-top:15px">${[['debunk','A convincing fake','Stage an event, then debunk it. Reduce coherence while belief and panic rise. The manipulation leaves a detectable pattern.'],['contact','A softer landing','Prepare the world for contact. Trust rises, along with belief and coherence. Panic falls, but manipulation can later be uncovered.'],['threat','One common enemy','Push governments together. You may earn leverage at the cost of panic and more militarization.']].map(([id,n,d])=>`<article class="card"><h3>${n}</h3><p>${d}</p>${previewButton('blue',id,'Review operation')}</article>`).join('')}</div>`;}
 return info('Narratives persist and spread over time. Low truth overlap can obscure real activity; strong overlap can connect the dots. Intervening again becomes less effective and increases your pattern signature.')+`<div class="grid">${Object.entries(NARRATIVES).map(([id,d])=>{const n=s.narratives[id],p=game.narrativePreview(id,n.active?'amplify':'seed');return `<article class="card ${game.year<d.year?'locked-card':''}">${tile(d.icon,d.name,n.active?`Reach ${Math.round(n.reach)}% · ${n.uses} interventions`:`Appears from ${d.year}`)}<p>${esc(d.desc)}</p><div class="tags">${badge(`Truth overlap ${Math.round(n.truth)}%`,n.truth>55?'red':'neutral')}${badge(`Virality ${Math.round(n.virality)}`,'purple')}</div>${n.active?`<div class="progress-label"><span>Reach</span><strong>${Math.round(n.reach)}%</strong></div>${meter(n.reach)}<div class="card-actions">${[['amplify','Amplify'],['contaminate','Contaminate'],['coopt','Co-opt'],['debunk','Debunk']].map(([a,label])=>previewButton('narrative',id,label,attr('kind2',a))).join('')}</div>`:`${blocked(p)}<div class="card-actions">${previewButton('narrative',id,'Seed narrative','data-kind2="seed"')}</div>`}</article>`;}).join('')}</div>`;}
function archivePanel(){const s=game.s;if(ui.tab==='evidence')return info('Hard public evidence cannot simply be erased. Containment can reclaim classified records and diminish weak witness reports. Lines connect records with a shared location or signature; the Network sees the archive it has generated, while human research estimates still require intelligence.')+exposureGraph()+`<div class="grid">${[...s.evidence].reverse().slice(0,80).map(e=>`<article class="card evidence-node ${e.public&&!['report','witness'].includes(e.type)?'public-hard':''}"><h3>${esc(e.name)}</h3><span class="sub">${date(e.day)} · ${esc(sname(e.country))}</span><div class="tags" style="margin-top:12px">${badge(e.contained?'Contained':e.public?'Public':'Classified',e.contained?'':e.public?'red':'purple')}${badge(e.type,'neutral')}${badge(`${e.strength.toFixed(1)} strength`,'gold')}</div><p class="note">Signature: ${esc(e.tag)}</p></article>`).join('')}</div>`;
 if(ui.tab==='log')return s.logs.map(l=>`<div class="timeline-item"><span class="eyebrow">${date(l.day)} · ${esc(l.type)}</span><p>${esc(l.text)}</p></div>`).join('');
 return s.history.length?`${info('This is your history, not a predetermined timeline. Event echoes preserve strategic pressure when the familiar incident does not fit your decisions.')}<div>${s.history.map(h=>`<article class="timeline-item"><span class="eyebrow">${date(h.day)}${h.country?' · '+esc(sname(h.country)):''}</span><strong>${esc(h.title)}</strong><p>${esc(h.body)}</p><small>Your decision: ${esc(h.choice)}</small></article>`).join('')}</div>`:empty('History is still waiting.','The first public incidents arrive as the century unfolds. You decide what they become.');}
function endgamePanel(){const s=game.s,c=game.control();if(ui.tab==='endings')return `<div class="grid">${Object.entries(ENDINGS).map(([id,d])=>`<article class="card">${tile(d.icon,d.name,d.tag,'purple')}<p>${esc(d.text)}</p>${badge(PROJECTS[id]?'Final project':'Consequence of failure',PROJECTS[id]?'':'gold')}</article>`).join('')}</div>`;
 return `<div class="mini-stats"><div class="mini-stat"><strong>${Math.round(c.total)}%</strong><small>Global control index</small></div><div class="mini-stat"><strong>${c.regions}</strong><small>Strategic regions reached</small></div><div class="mini-stat"><strong>${2045-game.year}</strong><small>Full years remaining</small></div></div>${info('A campaign ends when you complete a final project and commit to its future, or when time runs out after 2045. High public awareness alone is not defeat. One powerful ally cannot give you a planetary victory.')}<div class="card"><h3>Quiet progress.</h3>${Object.entries(c.pieces).map(([k,v])=>stat(k[0].toUpperCase()+k.slice(1),Math.round(v)+'%',v)).join('')}<div class="divider"></div>${stat('Human welfare',Math.round(s.doctrine.welfare)+'%')}${stat('Coercion',Math.round(s.doctrine.coercion)+'%')}${stat('Trusted regions',c.trusted)}${stat('Hostile coalition members',s.coalition.length)}</div><div class="section-heading" style="margin-top:23px"><h3>How should this story end?</h3></div><div class="grid">${Object.entries(PROJECTS).map(([id,d])=>{const checks=game.projectConditions(id),j=s.jobs.find(j=>j.kind==='project'&&j.subtype===id);return `<article class="card">${tile(ENDINGS[id].icon,d.name,`${dur(d.days)} · FINAL PROJECT`,'purple')}<p>${esc(d.desc)}</p><div class="checklist">${checks.map(ch=>`<div class="check-item ${ch.ok?'done':''}">${icon(ch.ok?'check':'minus',15)}${esc(ch.text)}</div>`).join('')}</div>${costs(d.cost)}${s.projectReady===id?btn('Commit to this future','finalize','','primary wide'):j?`<div class="progress-label"><span>Final project underway</span><strong>${dur(j.finish-s.day)}</strong></div>${meter((s.day-j.start)/j.duration*100)}`:`<div class="card-actions">${previewButton('project',id,'Review final project')}</div>`}</article>`;}).join('')}</div>`;}
function showPreview(kind,id,extra={}){let p,def,title,details='',confirm='Confirm assignment';const c=game.country(ui.selected);
 if(kind==='op'){def=OPERATIONS[id];p=game.opPreview(id,c.id);title=def.name;confirm='Launch operation';details=`<div class="mini-stats"><div class="mini-stat"><strong>${dur(p.days)}</strong><small>Mission duration</small></div><div class="mini-stat"><strong>${p.range?.join('–')}%</strong><small>Detection estimate</small></div><div class="mini-stat"><strong>1</strong><small>Command slot</small></div></div>${info(esc(p.reason||''),'warning','scan')}<p><strong>Assigned:</strong> ${esc(p.asset?p.asset.name+' · '+CRAFT[p.asset.type].name:def.craft?'No compatible craft available':'Human channel; no craft required')}</p><p class="note">Expected yield</p>${costs(p.reward,true)}<p class="note">Clean success, success with trace, partial recovery, or asset loss. A detected operation may create evidence that matters decades later.</p>`;}
 if(kind==='base'){def=BASES[id];p=game.buildPreview(id,c.id);title=def.name;confirm='Build installation';details=`<p class="note">Construction ${dur(p.days)} · ${def.slots} module sockets · baseline signature ${def.signature}. Location: ${esc(c.name)}${['orbital','lunar'].includes(id)?' logistics jurisdiction; the installation itself is off-world.':'.'}</p>`;}
 if(kind==='module'){def=MODULES[id];p=game.modulePreview(extra.base||ui.base,id);title=def.name;confirm='Install module';details=`<p class="note">Construction ${dur(p.days)} · next module level ${p.level+1}. Each level consumes one socket.</p>`;}
 if(kind==='craft'){def=CRAFT[id];p=game.craftPreview(id);title=def.name;confirm='Fabricate craft';details=`<p class="note">Fabrication ${dur(p.days)}. The craft consumes a small daily energy upkeep and can be assigned only to compatible missions.</p>`;}
 if(kind==='research'){def=TECHS[id];p=game.researchPreview(id);title=def.name;confirm='Begin research';details=`<p class="note">Research ${dur(p.days)} · ${TREES.find(t=>t.id===def.tree).name}, tier ${def.tier}.</p>`;}
 if(kind==='agent'){def=INFILTRATION[id];p=game.agentPreview(id,c.id,ui.institution);title=def.name;confirm='Create interface';details=`<p class="note">Destination: ${esc(INSTITUTIONS[ui.institution])} in ${esc(c.name)}. Fabrication takes ${dur(p.days)}, then a ${dur(p.careerDays)} cover career. Policy and promotion unlock when embedded.</p>${info(id==='replacement'?'Immediate high office has a cost: weak cover, elevated suspicion, and +8 Coercion.':'Human attachment grows over time. That can improve trust and change the interface’s priorities.','purple','agent')}`;}
 if(kind==='narrative'){def=NARRATIVES[id];p=game.narrativePreview(id,extra.kind2);title=extra.kind2[0].toUpperCase()+extra.kind2.slice(1)+': '+def.name;confirm='Shape the narrative';const texts={seed:'Create a persistent rumor. Belief increases; low-truth stories reduce coherence.',amplify:'Reach and belief rise. A high-truth story increases coherence; a low-truth story fragments it. Panic can rise.',contaminate:'Reduce truth overlap and coherence. Increase belief, panic, polarization and long-term pattern detection. Repeated interventions have diminishing returns.',coopt:'Redirect the interpretation. Reduce truth overlap and coherence; slightly improve public trust.',debunk:'Reduce reach, belief and panic. Debunking a well-supported true story can backfire and increase coherence.'};details=info(esc(texts[extra.kind2]),'purple','eye')+'<p class="note">180-day cooldown per narrative. Hard evidence is not deleted.</p>';}
 if(kind==='blue'){def={icon:'eye',desc:'A fabricated global event assembled from orbital projection, human media access and controlled sightings.'};p=game.bluePreview();title='Blue Veil: '+{debunk:'stage & debunk',threat:'a common threat',contact:'prepare contact'}[id];confirm='Begin Blue Veil';details=`<p class="note">${dur(p.days)} · 2 Command slots. A 45% chance of delayed investigative backlash. This is a fictional game mechanic, not a claim about real events.</p>`;}
 if(kind==='project'){def=PROJECTS[id];p={cost:def.cost,days:def.days,blocked:[...game.projectConditions(id).filter(ch=>!ch.ok).map(ch=>ch.text),...game.shortages(def.cost)]};if(game.s.jobs.some(j=>j.kind==='project')||game.s.projectReady)p.blocked.push('A final project is already underway');title=def.name;confirm='Begin final project';details=`<p class="note">${dur(p.days)}. Meet the conditions, complete the project, then commit to your ending before 2046.</p>`;}
 if(!p||!def)return;const html=modalHead(kind==='op'?`MISSION PLAN / ${c.name}`:'NETWORK PLANNING',title)+`<p>${esc(def.desc||'')}</p>${details}<div class="divider"></div><span class="eyebrow" style="margin-bottom:10px">RESOURCE COMMITMENT</span>${costs(p.cost)}${p.blocked.length?`<div class="checklist">${[...new Set(p.blocked)].map(b=>`<div class="check-item">${icon('minus',14)}${esc(b)}</div>`).join('')}</div>`:''}<div class="modal-actions">${btn('Back to planning','close-modal','','secondary')}${btn(confirm+' '+icon('arrow',15),'confirm-preview','','primary',p.blocked.length>0)}</div>`;
 showModal('preview',html,{previewKind:kind,id,country:c.id,base:extra.base||ui.base,institution:ui.institution,kind2:extra.kind2});}
function confirmPreview(){const m=ui.modal;if(m?.kind!=='preview')return;const actions={op:()=>game.launch(m.id,m.country),base:()=>game.buildBase(m.id,m.country),module:()=>game.buildModule(m.base,m.id),craft:()=>game.buildCraft(m.id),research:()=>game.research(m.id),agent:()=>game.recruit(m.id,m.country,m.institution),narrative:()=>game.narrativeAction(m.id,m.kind2),blue:()=>game.blueVeil(m.id),project:()=>game.startProject(m.id)};const action=actions[m.previewKind];if(action)apply(action());}
function effectText(e={}){const names={belief:'Belief',coherence:'Coherence',evidence:'Evidence',panic:'Panic',trust:'Trust',knowledge:'Government knowledge',hostility:'Hostility',dependence:'Dependency',leverage:'Leverage',insight:'Intel coverage',suspicion:'Suspicion',pattern:'Pattern',footprint:'Footprint',welfare:'Welfare',coercion:'Coercion',autonomy:'Autonomy',humanResearch:'Human research',attachment:'Attachment',loyalty:'Loyalty',baseSearch:'Base search'};return Object.entries(e).filter(([k,v])=>names[k]&&typeof v==='number').map(([k,v])=>`${names[k]} ${v>0?'+':''}${v}`).join(' · ');}
function showEvent(){const v=game.eventView();if(!v)return;if(eventSeen===v.uid&&ui.modal?.kind==='event')return;closeModal(true);eventSeen=v.uid;persist(true,true);audio.play('event');const html=`<span class="event-class">${v.type==='history'?'A CHAPTER IN YOUR CENTURY':'NETWORK INCIDENT'} · ${date(game.s.day)}</span><div class="modal-head" style="margin-top:15px"><div><h2>${esc(v.title)}</h2></div>${mascot(67,'worried')}</div><p>${esc(v.body)}</p><div class="event-choices">${v.choices.map(ch=>`<button class="event-choice" data-action="event-choice" data-id="${esc(ch.id)}" ${ch.blocked.length?'disabled':''}><strong>${esc(ch.label)}</strong><p>${esc(ch.text)}</p>${effectText(ch.effects)?`<div class="choice-effects">${esc(effectText(ch.effects))}</div>`:''}${costs(ch.cost)}${ch.blocked.length?`<div class="choice-effects">${esc(ch.blocked.join(' · '))}</div>`:''}</button>`).join('')}</div><p class="note">Time is paused. Immediate effects are shown; the long-term history remains yours to discover.</p>`;showModal('event',html,{uid:v.uid});eventSeen=v.uid;}
function showEnding(){if(!game.s.ended)return;const ending=ENDINGS[game.s.ended.id];pause();endingSeen=true;closeModal(true);showModal('ending',`<div class="ending-hero">${mascot(112)}<span class="eyebrow">${ending.tag} / ${game.year}</span><h2>${esc(ending.name)}</h2><p>${esc(ending.text)}</p></div><div class="mini-stats"><div class="mini-stat"><strong>${Math.round(game.s.ended.control)}%</strong><small>Final control</small></div><div class="mini-stat"><strong>${game.s.stats.decisions||0}</strong><small>Decisions made</small></div><div class="mini-stat"><strong>${game.s.researched.length}</strong><small>Discoveries</small></div></div><p class="note">Campaign seed: ${esc(game.s.seed)}. Your archive and save remain available.</p><div class="modal-actions">${btn('Export campaign','export','','secondary')}${btn('View the archive','ending-archive','','secondary')}${btn('Another little invasion','new-game','','primary')}</div>`);persist(true,true);}
function showNewGame(){showModal('new',modalHead('A CENTURY. A SMALL PLANET.','Make yourself at home.')+`<p>Start in 1945 with a hidden ocean node, two Scout Orbs, a Recovery Craft, and a very finite supply of extraordinary material. The first directive will guide you.</p><div class="modal-fields"><label class="wide">Campaign seed<input id="new-seed" class="field" value="Pale Blue Dot" maxlength="70" autocomplete="off"></label><label>Humanity<select id="new-difficulty" class="field"><option value="story">Story · curious neighbors</option><option value="standard" selected>Standard · watchful world</option><option value="hard">Paranoid · difficult neighbors</option></select></label><label>Base simulation pace<select id="new-pace" class="field"><option value="1">Unhurried · 1 day/sec</option><option value="6" selected>Balanced · 6 days/sec</option><option value="18">Quick · 18 days/sec</option></select></label></div>${info('You can pause at any moment and adjust speed during play. Incidents pause automatically. Switching tabs or putting your device to sleep also pauses the campaign.')}<p class="note">Original alternate-history fiction. Colorful presentation; strategic choices. No tactical combat. ${hasSave()?'A new campaign replaces the active autosave. Export your old campaign first to keep it permanently.':''}</p><div class="modal-actions">${btn('Not just yet','close-modal','','secondary')}${btn('Begin a quiet invasion '+icon('arrow',15),'begin','','primary')}</div>`);}
function showSettings(){showModal('settings',modalHead('YOUR COMMAND CONSOLE','A moment to think.')+`<label class="toggle-row"><span>Interface sounds<small>Original synthesized feedback, no sampled music.</small></span><input type="checkbox" data-option="sound" ${game.s.settings.sound?'checked':''}></label><label class="toggle-row"><span>Ambient music<small>A gentle procedural soundscape.</small></span><input type="checkbox" data-option="music" ${game.s.settings.music?'checked':''}></label><label class="toggle-row"><span>Reduced motion<small>Stops decorative orbit and cloud animation.</small></span><input type="checkbox" data-option="reducedMotion" ${game.s.settings.reducedMotion?'checked':''}></label><label class="toggle-row"><span>Base pace<small>Speed buttons multiply this rate.</small></span><select class="field" data-setting="pace"><option value="1" ${game.s.pace===1?'selected':''}>1 day/sec</option><option value="6" ${game.s.pace===6?'selected':''}>6 days/sec</option><option value="18" ${game.s.pace===18?'selected':''}>18 days/sec</option></select></label><div class="card-actions">${btn(icon('save',16)+' Save now','quick-save','','primary',!game.s.started)}${btn(icon('download',16)+' Export save','export','','secondary',!game.s.started)}${btn(icon('upload',16)+' Import save','import','','secondary')}${btn('Restore backup','restore-backup','','secondary')}${btn(icon('fullscreen',16)+' Full screen','fullscreen','','secondary')}</div><p class="note">Autosaves stay in this browser on this domain. Export a save before changing device, clearing site data, or moving between raw.githack and rawcdn.githack. Two rolling backup snapshots are retained when browser storage permits.</p><div class="modal-actions">${btn('Main menu','home','','secondary')}${btn('Return to Earth','close-modal','','primary')}</div>`);}
function showHelp(){showModal('help',modalHead('FIELD GUIDE / FIRST CONTACT','It is a management game.')+`<div class="long-text"><h3>One useful decision at a time.</h3><p><strong>Observe → survey → extract → research → establish a front → expand.</strong> Click a country on the globe or find it in Earth → Countries. Click <strong>Plan operation</strong> to inspect costs, expected rewards, craft assignment and detection risk.</p><h3>Your first ten directives</h3><p>The card beside the globe teaches the full loop. Completed directives grant a supply cache when you claim it. Research can run alongside operations. Every new base and agent creates opportunities and traces.</p><h3>Time is yours.</h3><p><strong>Space:</strong> pause / resume. <strong>1, 2, 3, 4:</strong> set 1×, 2×, 4×, 8× speed. <strong>Escape:</strong> close a planning panel. <strong>Ctrl/Cmd + S:</strong> save. Drag the globe to rotate and scroll to zoom. Everything can also be operated with labeled buttons.</p><h3>The strange economy</h3><p>Energy regenerates from power cores. Scout and extraction operations produce intelligence and materials. Markets need a company or a resource accord. Capital is shown in millions of scenario dollars. Exotic Substrate comes from salvage, recovery, or late research—not a bank account.</p><h3>The future has conditions.</h3><p>Visit <strong>Future</strong> to track six final projects. Complete and commit to one before the end of 2045. Diplomacy, institutional infiltration and economic control offer different paths. Public disclosure changes the challenge; it does not automatically end the campaign.</p><h3>Every human story is not proof.</h3><p>Belief, evidence and coherence are separate. Narrative noise cannot delete a public artifact or authenticated recording. Excessive manipulation raises long-term pattern detection.</p><h3>Planning never spends resources.</h3><p>Review cards before confirming. Disabled options state their missing requirements. You can cancel an active task from the bottom ribbon and reclaim part of its investment. A failed event choice still leaves a playable route forward.</p></div><div class="modal-actions">${btn('Understood. Very quietly.','close-modal','','primary')}</div>`);}
function showAbout(){showModal('about',modalHead('ALIEN INVADER SIMULATOR','An original small invasion.')+`<p>A browser-native strategy adaptation of <em>Alien Invader Simulator — GDD v1.0</em>. You administer an old non-human observation network through a century of human complications.</p><div class="divider"></div><p>This is alternate-history fiction and dry satire. Characters are invented transformations, and events are fictional interpretations of UFO folklore—not factual allegations.</p><p class="note">Original procedural globe scenery, characters, icons and sound. Rendering: Three.js (MIT). Cartography: World Atlas / Natural Earth, public-domain data. No affiliation with Nintendo or any console platform.</p><p class="note">Browser Edition 1.0: 241 cartographic entities, fixed modern borders, 48 research nodes, 63 event definitions (33 historical, 20 dynamic, 10 special), 12 narratives, 8 base types and 6 selectable final projects. This edition compresses logistics and historical borders; it is not a certified console build.</p><div class="modal-actions">${btn('Back to Earth','close-modal','','primary')}</div>`);}
function showJob(id){const j=game.s.jobs.find(j=>j.id===id);if(!j){toast('That task has already finished.');return;}showModal('job',modalHead('NETWORK TASK',titleOfJob(j))+`<p>${esc(j.country?sname(j.country):'Network infrastructure')} · ${dur(j.finish-game.s.day)} remaining.</p><div class="progress-label"><span>${date(j.start)}</span><span>${date(j.finish)}</span></div>${meter((game.s.day-j.start)/j.duration*100)}<p class="note">Canceling returns ${j.kind==='op'?'25':'50'}% of the original investment and releases the assigned asset. Completed time is lost.</p><div class="modal-actions">${btn('Cancel task','cancel-job',attr('id',id),'danger')}${btn('Keep working','close-modal','','primary')}</div>`,{id});}
function confirm(title,text,action,id,cost={}){showModal('confirm',modalHead('A CONSEQUENTIAL LITTLE DECISION',title)+`<p>${esc(text)}</p><div style="margin-top:16px">${costs(cost)}</div><div class="modal-actions">${btn('Keep things as they are','close-modal','','secondary')}${btn('Confirm','confirmed',`${attr('kind',action)} ${attr('id',id)}`,'primary')}</div>`);}
async function handleAction(e){const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const a=b.dataset.action,d=b.dataset;if(!game&&a!=='reload')return;if(a!=='sound')audio.play();try{
 switch(a){
 case'new-game':showNewGame();break;
 case'begin':{const seed=$('new-seed').value.trim()||'Pale Blue Dot',difficulty=$('new-difficulty').value,pace=Number($('new-pace').value);persist(true,true);const settings={...game.s.settings};game=new Game(world.defs,{seed,difficulty,pace});game.s.settings=settings;game.s.started=true;ui.selected='840';ui.base='base_home';endingSeen=false;eventSeen=null;enterGame();toast('Welcome, Administrator. Select a country and observe.');break;}
 case'continue':try{const saved=localStorage.getItem(SAVE);if(!saved)throw new Error('No saved campaign was found.');game=Game.restore(saved,world.defs);endingSeen=false;enterGame();toast('Campaign restored. Time is paused.');}catch(error){toast(error.message,'warning');}break;
 case'home':pause();persist(true);closeModal(true);closeDrawer();ui.title=true;document.body.classList.add('title-mode');$('continue-button').hidden=!hasSave();renderHUD();break;
 case'open':openDrawer(d.screen,d.tab);break;
 case'close-drawer':closeDrawer();break;
 case'close-modal':closeModal();break;
 case'tab':ui.tab=d.tab;renderDrawer();$('drawer-body').scrollTop=0;break;
 case'play':setSpeed(game.s.speed?0:1);break;
 case'speed':setSpeed(Number(d.speed));break;
 case'preview':showPreview(d.kind,d.id,{base:d.base,kind2:d.kind2});break;
 case'confirm-preview':confirmPreview();break;
 case'guide':{const g=GUIDE[game.s.guide];if(!g)break;if(g.action)showPreview('op',g.action);else{if(game.s.guide===3)ui.tree='human';if(game.s.guide===5&&!game.tech('bio1')){ui.tree='bio';openDrawer('research');}else openDrawer(g.tab,game.s.guide===4?'companies':game.s.guide===6?'recruit':null);}break;}
 case'claim-guide':apply(game.claimGuide(),false);break;
 case'layers':openDrawer('world','layers');break;
 case'set-layer':globe?.setLayer(d.id);closeDrawer();renderHUD();break;
 case'zoom-in':globe?.zoom(-1);break;case'zoom-out':globe?.zoom(1);break;case'focus':globe?.focus(ui.selected);break;
 case'select-country':select(d.id);closeDrawer();break;
 case'negotiate-country':select(d.id);openDrawer('diplomacy');break;
 case'filter-bloc':ui.bloc=d.id;ui.search='';openDrawer('world','countries');break;
 case'research-tree':ui.tree=d.id;renderDrawer();$('drawer-body').scrollTop=0;break;
 case'locate-base':{const base=game.s.bases.find(x=>x.id===d.id);if(base){select(base.country);closeDrawer();}break;}
 case'job':showJob(d.id);break;
 case'queue':showModal('queue',modalHead('ALL ACTIVE ASSIGNMENTS','A busy little network.')+game.s.jobs.map(j=>`<button class="list-row" data-action="job" data-id="${j.id}">${icon('clock',22)}<div><strong>${esc(titleOfJob(j))}</strong><small>${dur(j.finish-game.s.day)} remaining</small></div>${icon('chevron',17)}</button>`).join(''));break;
 case'cancel-job':apply(game.cancelJob(d.id));break;
 case'emergency':confirm('Recover local feedstock?','Send autonomous salvage drones from a Recovery Bay. This takes 120 days and can be used once every two years.','emergency','',{energy:12});break;
 case'repair':apply(game.repairCraft(d.id),false);break;
 case'confirm-recycle':confirm('Recycle this craft?','The idle craft is removed. You reclaim approximately 60% of physical materials, but not its invested energy.','recycle',d.id);break;
 case'confirm-evacuate':confirm('Abandon this installation?','The base, its modules and its unfinished module work will be lost. If this is your last base, the campaign ends.','evacuate',d.id);break;
 case'confirm-recall':confirm('Bring your colleague home?','This interface leaves its human role permanently. Its cover career and institutional access are lost.','recall',d.id);break;
 case'confirm-break':confirm('End this secret accord?','Your partner loses trust, grows more hostile and remembers the decision. All treaty benefits stop.','break',d.id);break;
 case'confirmed':{const f={recycle:()=>game.recycleCraft(d.id),evacuate:()=>{game.evacuate(d.id);return{ok:true};},recall:()=>game.agentAction(d.id,'recall'),break:()=>game.breakTreaty(d.id),emergency:()=>game.emergency()};if(f[d.kind])apply(f[d.kind]());break;}
 case'agent-action':confirm(d.kind==='promote'?'Seek a promotion?':'Steer institutional policy?',d.kind==='promote'?'An eight-month assignment raises access by 18, but attracts scrutiny. A one-year cooldown follows.':'A six-month assignment creates leverage and dependency. Its extra benefit depends on the institution; it also increases suspicion and pattern signature.',d.kind==='promote'?'agent-promote':'agent-policy',d.id,d.kind==='promote'?{intel:12,influence:game.tech('human4')?9:12}:{intel:8,influence:10});break;
 case'propose':apply(game.propose(ui.selected,ui.clauses,ui.offer),false);break;
 case'renew':apply(game.renewTreaty(d.id),false);break;
 case'trade':{const input=$('order-'+d.id);const quantity=Number(input?.value);apply(game.trade(d.id,quantity,d.buy==='1'),false);break;}
 case'upgrade-front':apply(game.upgradeFront(d.id),false);break;
 case'front-cover':apply(game.frontCover(d.id),false);break;
 case'character':{const cost=d.kind==='monitor'?{intel:10}:d.kind==='contact'?{intel:15,influence:12}:{intel:8,influence:15};const text=d.kind==='monitor'?'Monitor sources: returns 5 Intel and reduces Coherence by 2.':d.kind==='contact'?'Careful contact: public Trust +6, Belief +5 and Coherence +3.':'Misdirection: Coherence −6, Belief +4 and Pattern +4. Repeated noise has long-term consequences.';showModal('character',modalHead('A VERY PUBLIC CONVERSATION',CHARACTERS.find(c=>c.id===d.id).name)+`<p>${text} A one-year cooldown follows.</p><div style="margin-top:15px">${costs(cost)}</div><div class="modal-actions">${btn('Cancel','close-modal','','secondary')}${btn('Make contact with the story','character-confirm',`${attr('id',d.id)} ${attr('kind',d.kind)}`,'primary',!game.sufficient(cost))}</div>`);break;}
 case'character-confirm':apply(game.characterAction(d.id,d.kind));break;
 case'event-choice':{const r=game.choose(d.id);if(r.ok){closeModal(true);eventSeen=null;persist(true,true);renderAll();if(game.s.eventQueue.length)showEvent();else toast('Decision recorded. Press Space or ▶ to continue.');}else notices();break;}
 case'finalize':{const r=game.finalize();if(r.ok){closeModal(true);showEnding();}else notices();break;}
 case'ending-archive':closeModal(true);openDrawer('archive');break;
 case'settings':showSettings();break;case'help':showHelp();break;case'about':showAbout();break;
 case'sound':game.s.settings.sound=!game.s.settings.sound;audio.set(game.s.settings.sound,game.s.settings.music);if(game.s.settings.sound)audio.play('click');renderHUD();persist(true);break;
 case'quick-save':persist(false);break;
 case'export':download(`Alien-Invader-${game.year}-${game.s.seed.replace(/[^a-z0-9-]/gi,'_').slice(0,30)}.json`,game.export());toast('Portable campaign save exported.');break;
 case'import':$('save-import').click();break;
 case'restore-backup':{const raw=localStorage.getItem(SAVE+'-backup1');if(!raw){toast('No backup snapshot is available yet.','warning');break;}const restored=Game.restore(raw,world.defs);game=restored;enterGame();toast('Previous autosave restored. Time is paused.');break;}
 case'fullscreen':if(document.fullscreenElement)await document.exitFullscreen();else if(document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen();else toast('Use your browser’s full-screen command on this device.');break;
 case'reload':location.reload();break;
 }
 if(a==='confirmed'&&['agent-promote','agent-policy'].includes(d.kind))apply(game.agentAction(d.id,d.kind==='agent-promote'?'promote':'policy'));
 }catch(error){console.error(error);toast('That action could not complete: '+error.message,'warning');} }
document.addEventListener('click',handleAction);
document.addEventListener('change',e=>{if(!game)return;const el=e.target;try{
 if(el.dataset.clause){const k=el.dataset.clause;if(el.checked&&!ui.clauses.includes(k)){if(ui.clauses.length>=4){el.checked=false;toast('An agreement can contain at most four clauses.','warning');return;}ui.clauses.push(k);}if(!el.checked)ui.clauses=ui.clauses.filter(x=>x!==k);renderDrawer();}
 const setting=el.dataset.setting;if(setting==='selected'){select(el.value);return;}if(['base','institution','offer','tree','bloc'].includes(setting)){ui[setting]=el.value;renderDrawer();}if(setting==='pace'){game.s.pace=Number(el.value);accumulator=0;renderHUD();persist(true);}
 if(el.dataset.option){game.s.settings[el.dataset.option]=el.checked;renderHUD();persist(true);}
 }catch(error){toast(error.message,'warning');}});
let searchTimer;document.addEventListener('input',e=>{if(e.target.dataset.input!=='country-search')return;ui.search=e.target.value;clearTimeout(searchTimer);searchTimer=setTimeout(()=>{const pos=e.target.selectionStart;renderDrawer();const input=document.querySelector('[data-input="country-search"]');input?.focus({preventScroll:true});input?.setSelectionRange(pos,pos);},140);});
$('save-import').addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file)return;try{if(file.size>8_000_000)throw new Error('Save file is too large. Maximum 8 MB.');const restored=Game.restore(await file.text(),world.defs);persist(true,true);game=restored;endingSeen=false;eventSeen=null;enterGame();toast('Imported campaign restored. Time is paused.');}catch(error){toast(error.message,'warning');}e.target.value='';});
$('drawer-scrim').addEventListener('click',()=>closeDrawer());$('modal-scrim').addEventListener('click',()=>closeModal());
document.addEventListener('keydown',e=>{const typing=['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName);if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();persist(false);return;}if(e.key==='Escape'){if(ui.modal)closeModal();else closeDrawer();return;}if(typing)return;
 if(e.key==='Tab'&&ui.modal){const els=[...$('modal').querySelectorAll('button:not(:disabled),input,select,a[href]')].filter(n=>n.offsetParent!==null);if(els.length){const first=els[0],last=els[els.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}return;}
 if(e.code==='Space'){e.preventDefault();if(!ui.modal)setSpeed(game?.s.speed?0:1);}if(!ui.modal&&['1','2','3','4'].includes(e.key)){e.preventDefault();setSpeed({1:1,2:2,3:4,4:8}[e.key]);}if(!ui.modal&&!ui.screen&&e.key.startsWith('Arrow')){e.preventDefault();globe?.rotate(e.key==='ArrowLeft'?-.15:e.key==='ArrowRight'?.15:0,e.key==='ArrowUp'?-.1:e.key==='ArrowDown'?.1:0);}});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&game?.s.started){pause();persist(true);renderHUD();}});window.addEventListener('pagehide',()=>{pause();persist(true);});
function frame(t){requestAnimationFrame(frame);if(!game)return;const elapsed=lastFrame?Math.min((t-lastFrame)/1000,.15):0;lastFrame=t;
 if(!ui.title&&!ui.modal&&!document.hidden&&game.s.speed&&!game.s.ended){accumulator+=elapsed*game.s.pace*game.s.speed;const n=Math.min(120,Math.floor(accumulator));if(n){const actual=game.advance(n);accumulator-=actual;if(actual<n)accumulator=0;}}
 if(game.s.eventQueue.length&&!ui.title&&(!ui.modal||ui.modal.kind==='event'))showEvent();if(game.s.ended&&!endingSeen&&!ui.title)showEnding();
 // Paused planning is stable DOM: never replace a button under the pointer.
 // All actions explicitly redraw affected screens; the clock only refreshes changed HUD state.
 if(t-lastHUD>500){const key=[game.s.day,game.s.speed,game.s.jobs.length,ui.title,ui.selected].join(':');if(key!==frame.hudKey){renderHUD();frame.hudKey=key;}notices();lastHUD=t;if(game.s.started&&game.s.day-game.s.lastSave>=365)persist(true,true);}
}
async function boot(){try{world=await loadWorld();game=new Game(world.defs);game.s.settings.reducedMotion=matchMedia('(prefers-reduced-motion: reduce)').matches;
 $('brand-alien').innerHTML=mascot(43);$('help-button').innerHTML=icon('help',19);$('settings-button').innerHTML=icon('settings',19);$('drawer-close').innerHTML=icon('close',20);$('zoom-in').innerHTML=icon('plus',16);$('zoom-out').innerHTML=icon('minus',16);$('focus-button').innerHTML=icon('scan',16);$('quick-save-button').innerHTML=icon('save',19);
 try{globe=new Globe($('globe'),world,id=>{if(ui.title)return;select(id,false);},id=>{ui.base=id;openDrawer('bases');});}catch(error){console.warn('Using compatibility globe:',error.message);globe=new FallbackGlobe($('globe'),world,id=>{if(!ui.title)select(id,false);},id=>{ui.base=id;openDrawer('bases');});}
 $('continue-button').hidden=!hasSave();$('new-game-button').disabled=false;$('new-game-button').innerHTML=`Begin your invasion ${icon('arrow',18)}`;$('boot').hidden=true;document.body.classList.remove('is-loading');renderAll();requestAnimationFrame(frame);window.__AIS_READY__=true;
 if(new URLSearchParams(location.search).has('test'))window.__AIS_TEST__={get game(){return game;},get world(){return world;},get ui(){return ui;},get globe(){return globe;},Game,advance(days,options={}){pause();const result=game.advance(days,options);renderAll();return result;},refresh(){renderAll();},setGame(g){game=g;endingSeen=false;closeModal(true);enterGame();},open:openDrawer,preview:showPreview};
 }catch(error){console.error(error);$('boot').classList.add('error');$('boot').innerHTML=`${icon('alert',36)}<strong>The Network could not reach Earth.</strong><span>${esc(error.message)}</span><button class="button primary" data-action="reload">Try again</button>`;}}
boot();
