import {VERSION,START,DAY,END,clamp,RESOURCES,PHYSICAL,BLOCS,UNITED_NATIONS,blocFor,ERAS,BASES,MODULES,CRAFT,OPERATIONS,INFILTRATION,INSTITUTIONS,CLAUSES,TECHS,NARRATIVES,CHARACTERS,AGENT_NAMES,COMPANY_NAMES,PROJECTS} from './data.js';
import {EVENTS,HISTORY,DYNAMIC} from './events.js';
const clone=o=>JSON.parse(JSON.stringify(o));
const hash=s=>{let h=2166136261;for(const x of String(s))h=Math.imul(h^x.charCodeAt(0),16777619);return h>>>0;};
const sum=(a,f=x=>x)=>a.reduce((v,x)=>v+f(x),0);
const yearDay=y=>Math.floor((Date.UTC(y,0,1)-START)/DAY);
const metricKeys=['belief','coherence','panic','trust'];
const countryKeys=['trust','suspicion','dependence','infiltration','knowledge','hostility','leverage','insight'];
const MATERIAL_PRICE={common:1.2,precious:7,rare:4.5,nuclear:9,bio:2};
export const GUIDE=[
 {title:'Say hello. Very quietly.',text:'Select a country and send a Scout Orb to Observe. Time starts when you launch.',goal:'Complete 1 observation',test:s=>(s.stats.observe||0)>0,reward:{intel:10,influence:5},tab:'world',action:'observe'},
 {title:'A place for our plans',text:'Survey resources in an observed country. A surveyed site unlocks mining and base construction.',goal:'Survey 1 resource site',test:s=>(s.stats.survey||0)>0,reward:{common:8,energy:15},tab:'world',action:'survey'},
 {title:'The invasion needs gold',text:'Send your Recovery Craft on Quiet extraction. The same ship can later reclaim lost hardware.',goal:'Complete 1 extraction',test:s=>(s.stats.mine||0)>0,reward:{precious:3,rare:4},tab:'world',action:'mine'},
 {title:'Become legally ordinary',text:'Research Legal Identities in Human Systems. Your first company starts by selling a small gold reserve.',goal:'Research Legal Identities',test:s=>s.researched.includes('human1'),reward:{influence:8,bio:8},tab:'research'},
 {title:'A perfectly normal company',text:'Establish a front company in a surveyed country. It unlocks markets and earns Human Capital each day.',goal:'Establish 1 front company',test:s=>s.fronts.length>0,reward:{capital:20,influence:8},tab:'economy'},
 {title:'Meet the neighbors',text:'Research Human-Compatible Bodies and add a Bio-Lab module to a base.',goal:'Operate a Bio-Lab',test:s=>s.bases.some(b=>b.modules.bio),reward:{bio:8,exotic:3},tab:'bases'},
 {title:'A very human resource',text:'Fabricate an interface and choose its career. An adviser begins useful work in a year; a life-course identity takes longer.',goal:'Create 1 biological interface',test:s=>s.agents.length>0,reward:{influence:15,intel:15},tab:'agents'},
 {title:'A secret handshake',text:'Observe a country, open a backchannel, cultivate trust and negotiate an agreement.',goal:'Sign 1 secret accord',test:s=>s.treaties.some(t=>t.active),reward:{common:15,exotic:3},tab:'diplomacy'},
 {title:'Think a little bigger',text:'Build a second base in a different region. Distributed infrastructure is harder to lose all at once.',goal:'Operate 2 bases',test:s=>s.bases.length>=2,reward:{intel:20,influence:10},tab:'bases'},
 {title:'The century is yours',text:'Finish five research projects. Then choose your own path: hidden control, cooperative contact or something stranger.',goal:'Complete 5 research nodes',test:s=>s.researched.length>=5,reward:{rare:10,exotic:3},tab:'research'}
];
export class Game{
 constructor(defs,opts={}){
  this.defs=defs;const seed=hash(opts.seed||'Pale Blue Dot');
  this.s={version:VERSION,seed:opts.seed||'Pale Blue Dot',rng:seed,day:0,speed:0,pace:opts.pace||6,difficulty:opts.difficulty||'standard',started:false,
   resources:{energy:80,intel:25,influence:5,capital:0,common:32,precious:14,rare:18,nuclear:4,bio:16,exotic:opts.difficulty==='story'?45:opts.difficulty==='hard'?20:30},
   metrics:{belief:3,evidence:1,coherence:5,panic:0,trust:40},doctrine:{welfare:65,coercion:0,autonomy:0,intervention:0},
   countries:{},bases:[],craft:[],agents:[],fronts:[],jobs:[],treaties:[],researched:[],narratives:{},evidence:[],history:[],logs:[],eventQueue:[],scheduled:[],fired:[],
   un:{contact:0,trust:0,dependence:0,suspicion:0,infiltration:0,knowledge:0,hostility:0,legitimacy:0,briefed:false,framework:false,memory:[]},
   stats:{},cooldowns:{},guide:0,pattern:0,footprint:0,noiseUses:0,prices:{...MATERIAL_PRICE},formed:{},coalition:[],open:false,ended:null,projectReady:null,
   idCounter:1,lastDynamic:0,lastHistory:-365,lastSave:0,flags:{},settings:{sound:true,music:true,reducedMotion:false,autoPause:true},acknowledged:[],journal:[],notices:[]};
  for(const d of defs){const bloc=d.bloc||blocFor(d.id),b=BLOCS[bloc],salt=hash(d.id),variance=(salt%17)-8;
   this.s.countries[d.id]={...d,bloc,insight:0,surveyed:false,contact:0,trust:0,suspicion:0,dependence:0,infiltration:0,knowledge:0,hostility:Math.round(b.threat*.1),leverage:0,research:0,artifact:0,
    baseSensor:clamp(b.sensors+variance,8,70),industry:clamp(b.industry+variance,25,98),science:clamp(b.science+variance,20,98),ci:clamp((b.discipline+b.threat)/2+variance,20,95),memory:[],policyUntil:0};}
  this.s.bases.push({id:'base_home',type:'ocean',name:'Pelagic One',country:'840',lat:4,lon:-33,modules:{power:1,fabricator:1,relay:1,recovery:1},search:0,health:100,warned:false});
  this.s.craft.push({id:'craft_1',type:'scout',name:'Pip',busy:null,health:100},{id:'craft_2',type:'scout',name:'Dot',busy:null,health:100},{id:'craft_3',type:'recovery',name:'Tug',busy:null,health:100});
  for(const [id,d]of Object.entries(NARRATIVES))this.s.narratives[id]={id,active:false,reach:0,virality:d.virality,plausibility:d.plausibility,truth:d.truth,panic:d.panic,persistence:d.persistence,polarization:d.polarization,uses:0,last:-9999};
  this.s.evidence.push({id:'e_first',name:'An unconfirmed light',type:'witness',country:'840',strength:1,public:true,tag:'sighting',day:0,contained:false});
  this.log('The Containment Directive is active. Earth has become interesting.','welcome');
 }
 get state(){return this.s;}
 get year(){return new Date(START+this.s.day*DAY).getUTCFullYear();}
 get era(){return [...ERAS].reverse().find(x=>this.year>=x.year)||ERAS[0];}
 get date(){return new Date(START+this.s.day*DAY);}
 id(prefix){return prefix+'_'+this.s.idCounter++;}
 rand(){let t=this.s.rng=(this.s.rng+0x6D2B79F5)>>>0;t=Math.imul(t^(t>>>15),t|1);t^=t+Math.imul(t^(t>>>7),t|61);return((t^(t>>>14))>>>0)/4294967296;}
 factor(){return this.s.difficulty==='story'?.75:this.s.difficulty==='hard'?1.25:1;}
 tech(id){return this.s.researched.includes(id);}
 country(id){return this.s.countries[id]||null;}
 countries(){return Object.values(this.s.countries);}
 treaty(id){return this.s.treaties.find(t=>t.country===id&&t.active&&t.expiry>this.s.day);}
 clause(id,k){return !!this.treaty(id)?.clauses.includes(k);}
 hasModule(k){return this.s.bases.some(b=>b.modules[k]>0);}
 moduleCount(k){return sum(this.s.bases,b=>b.modules[k]||0);}
 command(){return Math.min(16,2+this.moduleCount('relay')+(this.tech('information3')?2:0));}
 commandUsed(){return sum(this.s.jobs.filter(j=>j.kind==='op'||j.kind==='blueveil'),j=>j.command||1);}
 builders(){return Math.min(8,1+this.moduleCount('fabricator'));}
 buildersUsed(){return this.s.jobs.filter(j=>['base','module','craft','agent'].includes(j.kind)).length;}
 capacity(k){if(k==='energy')return 90+this.moduleCount('power')*90+this.s.bases.filter(b=>b.type==='orbital').length*60;if(k==='exotic')return 100+this.moduleCount('storage')*25;return RESOURCES[k].cap+(PHYSICAL.includes(k)?this.moduleCount('storage')*100+(this.tech('fabrication3')?100:0):0);}
 legal(id=null){return this.s.fronts.some(f=>!id||f.country===id)||this.s.treaties.some(t=>t.active&&(!id||t.country===id)&&t.clauses.includes('resources'));}
 sufficient(cost={}){return Object.entries(cost).every(([k,v])=>RESOURCES[k]&&Number.isFinite(v)&&v>=0&&this.s.resources[k]+1e-8>=v);}
 shortages(cost={}){return Object.entries(cost).filter(([k,v])=>this.s.resources[k]+1e-8<v).map(([k,v])=>`${RESOURCES[k].short}: need ${Math.ceil(v-this.s.resources[k])} more`);}
 pay(cost={}){if(!this.sufficient(cost))return false;for(const[k,v]of Object.entries(cost))this.s.resources[k]-=v;return true;}
 gain(values={}){for(const[k,v]of Object.entries(values))if(RESOURCES[k]&&Number.isFinite(v))this.s.resources[k]=clamp(this.s.resources[k]+v,0,this.capacity(k));}
 cost(def,kind='normal',country=null){let cost={...def.cost};for(const k of Object.keys(cost)){
  if(PHYSICAL.includes(k)&&kind==='craft'&&this.tech('fabrication2'))cost[k]=Math.ceil(cost[k]*.85);
  if(PHYSICAL.includes(k)&&kind==='base'&&country&&this.clause(country,'lease'))cost[k]=Math.ceil(cost[k]*.8);
  if(k==='energy'&&kind==='op'&&this.tech('field2'))cost[k]=Math.ceil(cost[k]*.8);
  if(k==='influence'&&kind==='narrative'&&this.tech('cognitive3'))cost[k]=Math.ceil(cost[k]*.8);
 }return cost;}
 duration(days,kind='build'){let f=1;if(this.tech('fabrication1')&&kind==='build')f*=.85;if(kind==='research')f/=1+this.moduleCount('intel')*.06;if(kind==='op'&&this.tech('information2'))f*=.9;return Math.max(7,Math.round(days*f));}
 sensor(c){return clamp(c.baseSensor+this.era.sensor+c.research*.18+(this.s.coalition.includes(c.id)?15:0)-(c.policyUntil>this.s.day?12:0),5,99);}
 knowledge(c){const width=Math.max(3,40-c.insight*.34-(this.tech('information2')?8:0)-(this.clause(c.id,'sensors')?12:0));if(c.insight>=90)return `${Math.round(c.knowledge)}`;return `${Math.max(0,Math.floor((c.knowledge-width)/5)*5)}–${Math.min(100,Math.ceil((c.knowledge+width)/5)*5)}`;}
 require(req,c=null){if(!req)return '';if(req==='survey')return c?.surveyed?'':'Survey this country first';if(req==='insight')return(c?.insight||0)>=20?'':'Observe this country first';if(req==='contact')return(c?.contact||0)>=2?'':'Open a backchannel first';if(req==='artifact')return(c?.artifact||0)>0?'':'No recovered artifact is known here';if(req==='legal')return this.legal()?'':'Establish a front company or resource agreement';return this.tech(req)?'':`Research ${TECHS[req]?.name||req}`;}
 log(text,type='info',country=null){this.s.logs.unshift({id:this.id('log'),day:this.s.day,text,type,country});this.s.logs=this.s.logs.slice(0,350);}
 notice(text,type='success'){this.s.notices.push({id:this.id('notice'),text,type});this.s.notices=this.s.notices.slice(-8);}
 result(ok,msg){if(msg)this.notice(msg,ok?'success':'warning');return {ok,msg};}
 enqueue(kind,subtype,days,extra={}){const j={id:this.id('job'),kind,subtype,start:this.s.day,duration:days,finish:this.s.day+days,...extra};this.s.jobs.push(j);return j;}
 start(){this.s.started=true;if(!this.s.speed)this.s.speed=1;}
 availableCraft(op){const compat={observe:['scout','signal','skimmer','platform'],survey:['scout','surveyor','skimmer','platform'],mine:['recovery','courier','skimmer','surveyor','platform'],sample:['scout','collector','platform'],signals:['signal','platform'],salvage:['recovery','courier','surveyor','platform'],recover:['recovery','platform'],conceal:['scout','signal','platform']};
  return this.s.craft.filter(a=>!a.busy&&a.health>20&&(compat[op]||[]).includes(a.type)).sort((a,b)=>(CRAFT[b.type].special.includes(op)?1:0)-(CRAFT[a.type].special.includes(op)?1:0)||CRAFT[b.type].stealth-CRAFT[a.type].stealth)[0];}
 opPreview(op,id){const d=OPERATIONS[op],c=this.country(id);if(!d||!c)return {blocked:['Select a country'],cost:{},days:0,risk:0};const asset=d.craft?this.availableCraft(op):null,cost=this.cost(d,'op'),blocked=[];
  const req=this.require(d.req,c);if(req)blocked.push(req);if(op==='front'&&this.s.fronts.some(f=>f.country===id))blocked.push('A front company already operates here');if(op==='front'&&!c.surveyed)blocked.push('Survey the local business environment first');
  if(this.commandUsed()>=this.command())blocked.push('All command slots are occupied');if(d.craft&&!asset)blocked.push('No compatible craft is idle');
  if(this.s.jobs.some(j=>j.kind==='op'&&j.subtype===op&&j.country===id))blocked.push('This operation is already running');
  const cooldown=(this.s.cooldowns[op+':'+id]||0)-this.s.day;if(cooldown>0)blocked.push(`Available in ${Math.ceil(cooldown)} days`);
  blocked.push(...this.shortages(cost));const stealth=(asset?CRAFT[asset.type].stealth:0)+(this.tech('stealth1')?.15:0)+(this.tech('stealth3')?.15:0);
  let risk=(d.risk*(.7+this.sensor(c)/70)*(1-clamp(stealth,0,.82))+c.suspicion*.10+this.s.pattern*.055)*this.factor();
  if(this.clause(id,'corridor'))risk*=.75;if(op==='mine'&&this.tech('extraction2'))risk*=.7;if(op==='recover')risk+=c.ci*.13;
  risk=clamp(risk,2,92);const uncertainty=Math.round(Math.max(2,8-c.insight*.055));
  return {cost,days:this.duration(d.days,'op'),risk:Math.round(risk),range:[Math.max(1,Math.round(risk-uncertainty)),Math.min(95,Math.round(risk+uncertainty))],blocked,asset,command:1,reason:`Sensors ${Math.round(this.sensor(c))} · local suspicion ${Math.round(c.suspicion)} · pattern ${Math.round(this.s.pattern)}`,reward:d.reward};
 }
 launch(op,id){const p=this.opPreview(op,id);if(p.blocked.length)return this.result(false,p.blocked[0]);this.pay(p.cost);const j=this.enqueue('op',op,p.days,{country:id,asset:p.asset?.id||null,cost:p.cost,risk:p.risk,roll:this.rand(),command:1});if(p.asset)p.asset.busy=j.id;
  this.start();this.log(`${OPERATIONS[op].name} launched in ${this.country(id).name}.`,'operation',id);return this.result(true,`${OPERATIONS[op].name} is underway`);}
 cancelJob(id){const j=this.s.jobs.find(j=>j.id===id);if(!j)return this.result(false,'This task has already finished');for(const[k,v]of Object.entries(j.cost||{}))this.gain({[k]:v*(j.kind==='op'?.25:.5)});const a=this.s.craft.find(a=>a.id===j.asset);if(a)a.busy=null;const agent=this.s.agents.find(x=>x.id===j.agent);if(agent)agent.busy=null;this.s.jobs=this.s.jobs.filter(x=>x.id!==id);return this.result(true,'Task canceled. Recoverable resources returned.');}
 buildPreview(type,country){const d=BASES[type],c=this.country(country),blocked=[];if(!d||!c)return {blocked:['Select a country'],cost:{}};const req=this.require(d.req,c);if(req)blocked.push(req);
  if(!['ocean','orbital','lunar'].includes(type)&&!c.surveyed)blocked.push('Survey this country first');
  if(this.s.bases.length+this.s.jobs.filter(j=>j.kind==='base').length>=18)blocked.push('Network limit: 18 installations');
  if(this.s.bases.some(b=>b.country===country&&b.type===type)||this.s.jobs.some(j=>j.kind==='base'&&j.country===country&&j.subtype===type))blocked.push('This installation type already exists here');
  if(this.buildersUsed()>=this.builders())blocked.push('All fabrication slots are occupied');const cost=this.cost(d,'base',country);blocked.push(...this.shortages(cost));return {cost,days:this.duration(d.days),blocked};}
 buildBase(type,id){const p=this.buildPreview(type,id);if(p.blocked.length)return this.result(false,p.blocked[0]);this.pay(p.cost);this.enqueue('base',type,p.days,{country:id,cost:p.cost});this.start();return this.result(true,`Building ${BASES[type].name}`);}
 modulePreview(baseId,type){const b=this.s.bases.find(b=>b.id===baseId),d=MODULES[type],blocked=[];if(!b||!d)return {cost:{},blocked:['Installation not found']};
  const level=(b.modules[type]||0)+this.s.jobs.filter(j=>j.kind==='module'&&j.base===baseId&&j.subtype===type).length;
  if(level>=3)blocked.push('Maximum module level reached');if(sum(Object.values(b.modules))+this.s.jobs.filter(j=>j.kind==='module'&&j.base===baseId).length>=BASES[b.type].slots)blocked.push('No free module sockets');
  if(type==='bio'&&!this.tech('bio1'))blocked.push('Research Human-Compatible Bodies');if(type==='logistics'&&!this.tech('human1'))blocked.push('Research Legal Identities');if(this.buildersUsed()>=this.builders())blocked.push('All fabrication slots are occupied');
  const cost=Object.fromEntries(Object.entries(d.cost).map(([k,v])=>[k,Math.ceil(v*(1+level*.35))]));blocked.push(...this.shortages(cost));return {cost,days:this.duration(d.days),blocked,level};}
 buildModule(baseId,type){const p=this.modulePreview(baseId,type);if(p.blocked.length)return this.result(false,p.blocked[0]);this.pay(p.cost);this.enqueue('module',type,p.days,{base:baseId,cost:p.cost});this.start();return this.result(true,`${MODULES[type].name} queued`);}
 craftPreview(type){const d=CRAFT[type],blocked=[];if(!d)return {blocked:['Unknown craft'],cost:{}};const req=this.require(d.req);if(req)blocked.push(req);if(!this.hasModule('fabricator'))blocked.push('A Fabrication Chamber is required');if(this.s.craft.length+this.s.jobs.filter(j=>j.kind==='craft').length>=24)blocked.push('Fleet limit: 24 craft');if(this.buildersUsed()>=this.builders())blocked.push('All fabrication slots are occupied');const cost=this.cost(d,'craft');blocked.push(...this.shortages(cost));return {cost,days:this.duration(d.days),blocked};}
 buildCraft(type){const p=this.craftPreview(type);if(p.blocked.length)return this.result(false,p.blocked[0]);this.pay(p.cost);this.enqueue('craft',type,p.days,{cost:p.cost});this.start();return this.result(true,`${CRAFT[type].name} is in fabrication`);}
 repairCraft(id){const a=this.s.craft.find(a=>a.id===id);if(!a||a.busy)return this.result(false,'Craft must be idle');if(a.health>=100)return this.result(false,'Craft is already fully operational');const cost={common:3,rare:1,energy:8};if(!this.pay(cost))return this.result(false,this.shortages(cost)[0]);a.health=100;return this.result(true,'Craft repaired');}
 recycleCraft(id){const a=this.s.craft.find(a=>a.id===id);if(!a||a.busy)return this.result(false,'Craft must be idle');this.gain(Object.fromEntries(Object.entries(CRAFT[a.type].cost).filter(([k])=>PHYSICAL.includes(k)).map(([k,v])=>[k,Math.max(k==='exotic'?1:0,Math.floor(v*.6))])));this.s.craft=this.s.craft.filter(x=>x.id!==id);return this.result(true,'Craft recycled into usable feedstock');}
 researchPreview(id){const t=TECHS[id],blocked=[];if(!t)return {blocked:['Unknown research'],cost:{}};if(this.tech(id))blocked.push('Already researched');if(t.pre&&!this.tech(t.pre))blocked.push(`Requires ${TECHS[t.pre].name}`);if(this.year<t.year)blocked.push(`Available from ${t.year}`);if(this.s.jobs.some(j=>j.kind==='research'&&j.subtype===id))blocked.push('Already in progress');if(this.s.jobs.filter(j=>j.kind==='research').length>=(this.tech('information3')?2:1))blocked.push('Research capacity is occupied');const cost=this.cost(t);blocked.push(...this.shortages(cost));return {cost,days:this.duration(t.days,'research'),blocked};}
 research(id){const p=this.researchPreview(id);if(p.blocked.length)return this.result(false,p.blocked[0]);this.pay(p.cost);this.enqueue('research',id,p.days,{cost:p.cost});this.start();return this.result(true,`Research started: ${TECHS[id].name}`);}
 agentPreview(method,id,institution){const c=this.country(id),d=INFILTRATION[method],blocked=[];if(!d||!c)return {blocked:['Select a country'],cost:{}};if(!INSTITUTIONS[institution])blocked.push('Choose an institution');if(!this.tech('bio1'))blocked.push('Research Human-Compatible Bodies');if(!this.hasModule('bio'))blocked.push('Build a Bio-Lab');if(c.insight<20)blocked.push('Observe the target country');if(this.s.agents.length+this.s.jobs.filter(j=>j.kind==='agent').length>=12)blocked.push('Interface limit: 12');if(this.buildersUsed()>=this.builders())blocked.push('All fabrication slots are occupied');if(method==='replacement'&&!this.tech('bio2'))blocked.push('Replacement requires Identity Resilience');const cost=this.cost(d);blocked.push(...this.shortages(cost));return {cost,days:this.duration(180),careerDays:Math.round(d.days*(this.tech('bio3')?.8:1)),blocked};}
 recruit(method,id,institution){const p=this.agentPreview(method,id,institution);if(p.blocked.length)return this.result(false,p.blocked[0]);this.pay(p.cost);this.enqueue('agent',method,p.days,{country:id,institution,cost:p.cost,careerDays:p.careerDays});this.start();return this.result(true,'Your future colleague is in fabrication');}
 agentAction(id,type){const a=this.s.agents.find(a=>a.id===id),c=a&&this.country(a.country);if(!a||!c)return this.result(false,'Interface not found');if(a.busy)return this.result(false,'This interface already has an assignment');
  if(type==='recall'){this.gain({bio:4});c.infiltration=clamp(c.infiltration-5);this.s.agents=this.s.agents.filter(x=>x.id!==id);this.log(`${a.name} was safely recalled.`,'agent',c.id);return this.result(true,'Interface recalled safely');}
  if(a.phase!=='active')return this.result(false,'This interface is still building a human career');const cost=type==='promote'?{intel:12,influence:this.tech('human4')?9:12}:{intel:8,influence:10};
  if(type==='promote'&&a.access>=95)return this.result(false,'Already at the highest institutional level');if((a.cooldown||0)>this.s.day)return this.result(false,`Assignment available in ${Math.ceil(a.cooldown-this.s.day)} days`);if(!this.pay(cost))return this.result(false,this.shortages(cost)[0]);const j=this.enqueue('agent_action',type,type==='promote'?240:180,{agent:id,country:c.id,cost});a.busy=j.id;this.start();return this.result(true,`${a.name} is working on the assignment`);}
 proposalPreview(id,clauses,offer='intel'){const c=this.country(id),blocked=[];clauses=[...new Set(clauses)].filter(k=>CLAUSES[k]);if(!c)return {blocked:['Select a country'],cost:{},chance:0};if(c.contact<2)blocked.push('Open a backchannel first');if(this.treaty(id))blocked.push('An accord is already active');if(!clauses.length||clauses.length>4)blocked.push('Select between 1 and 4 clauses');if((this.s.cooldowns['treaty:'+id]||0)>this.s.day)blocked.push('Diplomatic channel is cooling down');
  const cost={influence:8+clauses.length*4,...(offer==='capital'?{capital:25}:offer==='sample'?{exotic:1,rare:3,intel:8}:{intel:15})};blocked.push(...this.shortages(cost));const b=BLOCS[c.bloc];const chance=clamp(25+c.trust*.55+b.appetite*.35-sum(clauses,k=>CLAUSES[k].value)*.35-c.hostility*.3+(offer==='sample'?32:offer==='capital'?18:9)+(this.tech('human5')?14:0),8,95);return {cost,chance:Math.round(chance),blocked,clauses};}
 propose(id,clauses,offer){const p=this.proposalPreview(id,clauses,offer);if(p.blocked.length)return this.result(false,p.blocked[0]);this.pay(p.cost);this.s.cooldowns['treaty:'+id]=this.s.day+180;const c=this.country(id);if(this.rand()*100>p.chance){c.trust=clamp(c.trust+3,-100,100);this.log(`${c.name} declined the proposed accord. The channel remains open.`,'diplomacy',id);return this.result(true,'Proposal declined. Cultivate trust or offer more value.');}
  const t={id:this.id('treaty'),country:id,clauses:p.clauses,offer,start:this.s.day,expiry:this.s.day+2922,active:true};this.s.treaties.push(t);c.contact=4;c.trust=clamp(c.trust+15,-100,100);c.knowledge=clamp(c.knowledge+12);c.dependence=clamp(c.dependence+10);c.leverage=clamp(c.leverage+10);c.hostility=clamp(c.hostility-12);this.s.stats.treaties=(this.s.stats.treaties||0)+1;c.memory.unshift('A secret accord was accepted.');if(offer==='sample'){c.research=clamp(c.research+12);this.s.stats.techGifts=(this.s.stats.techGifts||0)+1;this.rivalry(c);}
  this.s.pattern=clamp(this.s.pattern+2);this.log(`Secret accord signed with ${c.name}.`,'diplomacy',id);this.notice(`${c.name} is now a secret partner`);this.updateMetrics();return {ok:true};}
 renewTreaty(id){const t=this.s.treaties.find(t=>t.id===id);if(!t)return this.result(false,'Agreement not found');if(t.active&&t.expiry-this.s.day>730)return this.result(false,'Renewal opens during the final two years');const cost={influence:12,intel:8};if(!this.pay(cost))return this.result(false,this.shortages(cost)[0]);t.active=true;t.expiry=this.s.day+2922;this.country(t.country).trust=clamp(this.country(t.country).trust+6,-100,100);return this.result(true,'Accord renewed for eight years');}
 breakTreaty(id){const t=this.s.treaties.find(t=>t.id===id);if(!t||!t.active)return this.result(false,'No active agreement');t.active=false;const c=this.country(t.country);c.trust=clamp(c.trust-22,-100,100);c.hostility=clamp(c.hostility+15);c.memory.unshift('The Network ended an accord.');this.s.doctrine.autonomy+=2;return this.result(true,'Agreement ended. Your partner will remember.');}
 unPreview(action){const d=UNITED_NATIONS.actions[action],u=this.s.un,blocked=[];if(!d)return {blocked:['Unknown United Nations action'],cost:{}};if(this.year<d.year)blocked.push(`Available from ${d.year}`);if(action==='liaison'&&u.contact>=2)blocked.push('A mission backchannel already exists');if(action==='brief'){if(u.contact<2)blocked.push('Open the mission backchannel first');if(u.briefed)blocked.push('The scientific panel has already been briefed');}if(action==='network'){if(u.contact<2)blocked.push('Open the mission backchannel first');if(!this.tech('human3'))blocked.push('Research Corporate Ecology');const regions=new Set(this.s.agents.filter(a=>a.phase==='active').map(a=>this.country(a.country)?.bloc).filter(Boolean));if(regions.size<2)blocked.push('Embed active interfaces in 2 regions');if(u.infiltration>=80)blocked.push('Institutional access is already extensive');if((this.s.cooldowns.unNetwork||0)>this.s.day)blocked.push('Institutional network work is cooling down');}if(action==='framework'){if(u.contact<3)blocked.push('Brief the scientific panel first');if(!this.tech('human5'))blocked.push('Research Treaty Architecture');if(u.trust<25)blocked.push('United Nations trust must reach 25');if(this.trustedRegions().length<2)blocked.push('Maintain trusted accords in 2 regions');if(u.framework)blocked.push('An inspection framework already exists');}if(action==='mandate'){if(this.year<2017)blocked.push('Managed disclosure belongs to the Disclosure Pressure era');if(!u.framework)blocked.push('Negotiate an inspection framework first');if(u.contact<4)blocked.push('United Nations contact level must reach 4');if(u.trust<55)blocked.push('United Nations trust must reach 55');if(u.legitimacy<45)blocked.push('Global legitimacy must reach 45');if(this.trustedRegions().length<3)blocked.push('Maintain trusted accords in 3 regions');if(this.s.open)blocked.push('The Network is already openly established');}blocked.push(...this.shortages(d.cost));return {cost:{...d.cost},blocked};}
 unAction(action){const p=this.unPreview(action);if(p.blocked.length)return this.result(false,p.blocked[0]);this.pay(p.cost);const u=this.s.un,m=this.s.metrics,d=UNITED_NATIONS.actions[action];if(action==='liaison'){u.contact=2;u.trust=clamp(u.trust+12,-100,100);u.knowledge=clamp(u.knowledge+10);u.suspicion=clamp(u.suspicion+4);u.memory.unshift('A discreet mission channel was opened.');}if(action==='brief'){u.briefed=true;u.contact=Math.max(u.contact,3);u.trust=clamp(u.trust+16,-100,100);u.knowledge=clamp(u.knowledge+18);u.suspicion=clamp(u.suspicion+4);u.legitimacy=clamp(u.legitimacy+10);m.trust=clamp(m.trust+2);u.memory.unshift('A multinational scientific panel received a bounded briefing.');}if(action==='network'){u.infiltration=clamp(u.infiltration+24);u.trust=clamp(u.trust+6,-100,100);u.legitimacy=clamp(u.legitimacy+5);u.suspicion=clamp(u.suspicion+7);u.knowledge=clamp(u.knowledge+4);this.s.cooldowns.unNetwork=this.s.day+730;u.memory.unshift('Embedded careers created durable institutional access.');}if(action==='framework'){u.framework=true;u.contact=4;u.trust=clamp(u.trust+12,-100,100);u.dependence=clamp(u.dependence+10);u.knowledge=clamp(u.knowledge+18);u.suspicion=clamp(u.suspicion-6);u.legitimacy=clamp(u.legitimacy+28);m.trust=clamp(m.trust+4);m.panic=clamp(m.panic-2);u.memory.unshift('A classified inspection and deconfliction framework was accepted.');}if(action==='mandate'){u.contact=5;u.trust=clamp(u.trust+12,-100,100);u.knowledge=100;u.hostility=clamp(u.hostility-8);u.legitimacy=clamp(u.legitimacy+25);this.s.open=true;this.s.flags.unMandate=true;m.belief=clamp(m.belief+18);m.coherence=clamp(m.coherence+18);m.panic=clamp(m.panic+5);m.trust=clamp(m.trust+10);this.s.doctrine.autonomy=clamp(this.s.doctrine.autonomy+5);this.addEvidence('United Nations disclosure dossier','840',8,'document',true,'disclosure');u.memory.unshift('The global forum introduced the Network under an agreed disclosure mandate.');}u.memory=u.memory.slice(0,10);this.log(`United Nations: ${d.name}.`,'diplomacy');this.notice(`United Nations · ${d.name}`);return this.result(true,d.name+' completed');}
 disclosurePreview(mode='authority'){const blocked=[],cost={intel:35,influence:45,energy:25},c=this.control();if(mode!=='authority')blocked.push('Unknown disclosure posture');if(this.s.open)blocked.push('The Network is already openly established');if(this.year<2017)blocked.push('Available from 2017');if(!this.tech('human5'))blocked.push('Research Treaty Architecture');if(c.total<55)blocked.push('Global control must reach 55');if(c.regions<4)blocked.push('Presence across 4 regions is required');if(this.s.doctrine.coercion<8)blocked.push('Coercion must reach 8');if(this.countries().filter(x=>x.contact>=3).length<2)blocked.push('Maintain limited contact with 2 countries');blocked.push(...this.shortages(cost));return {cost,blocked};}
 disclose(mode='authority'){const p=this.disclosurePreview(mode);if(p.blocked.length)return this.result(false,p.blocked[0]);this.pay(p.cost);const s=this.s,m=s.metrics;s.open=true;s.flags.declaredAuthority=true;s.doctrine.coercion=clamp(s.doctrine.coercion+12);m.belief=clamp(m.belief+20);m.coherence=clamp(m.coherence+22);m.panic=clamp(m.panic+12);m.trust=clamp(m.trust-8);for(const c of this.countries().filter(c=>c.contact>0||c.knowledge>0)){c.knowledge=clamp(c.knowledge+20);c.hostility=clamp(c.hostility+8);c.suspicion=clamp(c.suspicion+8);}s.un.contact=Math.max(s.un.contact,2);s.un.knowledge=100;s.un.suspicion=clamp(s.un.suspicion+15);s.un.hostility=clamp(s.un.hostility+12);s.un.trust=clamp(s.un.trust-8,-100,100);this.addEvidence('Network authority declaration','840',15,'broadcast',true,'disclosure');this.log('The Network declared an open administrative presence. Secrecy ended; the campaign did not.','milestone');this.notice('Open presence established. Humanity is responding.','warning');return this.result(true,'The Network is now openly established');}
 rivalry(c){const rivals=c.bloc==='usa'?['china','russia']:c.bloc==='china'?['usa','russia']:c.bloc==='russia'?['usa','china']:[];for(const r of this.countries().filter(x=>rivals.includes(x.bloc)&&x.contact>=2)){r.trust=clamp(r.trust-5,-100,100);r.hostility=clamp(r.hostility+5);r.memory.unshift(`Technology was shared with ${c.name}.`);r.memory=r.memory.slice(0,10);}}
 marketPrice(k,buy=true){return (this.s.prices[k]||0)*(buy?1.08:.87)*(1+this.s.footprint/1200);}
 trade(k,amount,buy=true){if(!MATERIAL_PRICE[k]||!Number.isInteger(amount)||amount<1||amount>100)return this.result(false,'Invalid order');if(!this.legal())return this.result(false,'Establish a front company or resource agreement first');const cost=buy?{capital:this.marketPrice(k,true)*amount}:{[k]:amount};if(buy&&this.s.resources[k]+amount>this.capacity(k)+1e-8)return this.result(false,'Not enough storage space');if(!this.pay(cost))return this.result(false,this.shortages(cost)[0]);this.gain(buy?{[k]:amount}:{capital:this.marketPrice(k,false)*amount});const cover=(this.tech('human2')?.75:1)/(1+this.moduleCount('logistics')*.12);this.s.footprint=clamp(this.s.footprint+amount*.7*cover,0,200);this.s.prices[k]=clamp(this.s.prices[k]*(buy?1+amount*.001:1-amount*.0005),MATERIAL_PRICE[k]*.6,MATERIAL_PRICE[k]*1.7);return this.result(true,`${buy?'Purchased':'Sold'} ${amount} ${RESOURCES[k].name.toLowerCase()}`);}
 upgradeFront(id){const f=this.s.fronts.find(f=>f.id===id);if(!f)return this.result(false,'Company not found');if(f.level>=5)return this.result(false,'Maximum company scale reached');const cost={capital:25*f.level,influence:5*f.level};if(!this.pay(cost))return this.result(false,this.shortages(cost)[0]);f.level++;f.cover=clamp(f.cover+8);this.s.footprint=clamp(this.s.footprint+8,0,200);return this.result(true,`${f.name} expanded to level ${f.level}`);}
 frontCover(id){const f=this.s.fronts.find(f=>f.id===id);if(!f)return this.result(false,'Company not found');const cost={capital:12,intel:8};if(!this.pay(cost))return this.result(false,this.shortages(cost)[0]);f.cover=clamp(f.cover+15);this.s.footprint=clamp(this.s.footprint-15,0,200);this.s.pattern=clamp(this.s.pattern-3);return this.result(true,'Procurement records diversified');}
 narrativePreview(id,action){const n=this.s.narratives[id],d=NARRATIVES[id],blocked=[];if(!n||!d)return {blocked:['Unknown narrative'],cost:{}};if(this.year<d.year)blocked.push(`Appears from ${d.year}`);if(!this.tech('cognitive1'))blocked.push('Research Cultural Semantics');if(action!=='seed'&&!n.active)blocked.push('Seed this narrative first');if(action==='seed'&&n.active)blocked.push('Narrative already exists');if(this.s.day-n.last<180)blocked.push(`Available in ${180-(this.s.day-n.last)} days`);const cost=this.cost({cost:{influence:action==='seed'?8:action==='debunk'?12:10,intel:action==='debunk'?8:4}},'narrative');blocked.push(...this.shortages(cost));return {cost,blocked};}
 narrativeAction(id,action){if(!['seed','amplify','contaminate','coopt','debunk'].includes(action))return this.result(false,'Unknown narrative action');const p=this.narrativePreview(id,action);if(p.blocked.length)return this.result(false,p.blocked[0]);this.pay(p.cost);const n=this.s.narratives[id],m=this.s.metrics;n.last=this.s.day;n.uses++;const diminishing=1/(1+n.uses*.12);
  if(action==='seed'){n.active=true;n.reach=16;m.belief=clamp(m.belief+3);m.coherence=clamp(m.coherence-(1-n.truth/100)*4);}
  if(action==='amplify'){n.reach=clamp(n.reach+20);m.belief=clamp(m.belief+5);m.coherence=clamp(m.coherence+(n.truth>55?5:-4)*diminishing);m.panic=clamp(m.panic+n.panic*.035);}
  if(action==='contaminate'){n.truth=clamp(n.truth-10);n.plausibility=clamp(n.plausibility-8);n.polarization=clamp(n.polarization+12);m.coherence=clamp(m.coherence-9*diminishing);m.belief=clamp(m.belief+4);m.panic=clamp(m.panic+2);this.s.noiseUses++;this.s.pattern=clamp(this.s.pattern+2+this.s.noiseUses*.3);}
  if(action==='coopt'){n.truth=clamp(n.truth-6);n.plausibility=clamp(n.plausibility+4);m.coherence=clamp(m.coherence-5*diminishing);m.trust=clamp(m.trust+1);}
  if(action==='debunk'){n.reach=clamp(n.reach-22);m.belief=clamp(m.belief-4*diminishing);m.panic=clamp(m.panic-2);if(n.truth>55&&m.evidence>30){m.coherence=clamp(m.coherence+4);m.trust=clamp(m.trust-3);}}
  this.log(`${NARRATIVES[id].name}: ${action}.`,'narrative');return this.result(true,'The conversation is changing');}
 characterAction(id,action){const ch=CHARACTERS.find(x=>x.id===id);if(!ch||this.year<ch.year)return this.result(false,'This character is not active in this era');const key='character:'+id;if((this.s.cooldowns[key]||0)>this.s.day)return this.result(false,'Let the conversation develop before intervening again');const cost=action==='monitor'?{intel:10}:action==='contact'?{intel:15,influence:12}:{intel:8,influence:15};if(!this.pay(cost))return this.result(false,this.shortages(cost)[0]);this.s.cooldowns[key]=this.s.day+365;
  if(action==='monitor'){this.s.flags['monitored_'+id]=true;this.gain({intel:5});this.s.metrics.coherence=clamp(this.s.metrics.coherence-2);}
  if(action==='contact'){this.s.metrics.trust=clamp(this.s.metrics.trust+6);this.s.metrics.belief=clamp(this.s.metrics.belief+5);this.s.metrics.coherence=clamp(this.s.metrics.coherence+3);this.s.doctrine.autonomy+=1;}
  if(action==='misdirect'){this.s.metrics.coherence=clamp(this.s.metrics.coherence-6);this.s.metrics.belief=clamp(this.s.metrics.belief+4);this.s.noiseUses++;this.s.pattern=clamp(this.s.pattern+4);}
  this.log(`${ch.name}: ${action==='monitor'?'source network monitored':action==='contact'?'a careful contact was established':'attention moved toward a competing story'}.`,'character');return this.result(true,`${ch.name}'s story continues`);}
 bluePreview(){const blocked=[];if(!this.tech('field5'))blocked.push('Research Bounded Projection');if(!this.s.bases.some(b=>b.type==='orbital'))blocked.push('Build an Orbital Platform');if(!this.s.agents.some(a=>a.phase==='active'&&a.institution==='media'&&a.access>=40)&&!this.s.fronts.some(f=>f.level>=3))blocked.push('Need a media agent with 40 Access or a level-3 front');if(this.command()-this.commandUsed()<2)blocked.push('Requires 2 free command slots');if((this.s.cooldowns.blueveil||0)>this.s.day)blocked.push('Blue Veil is cooling down');if(this.s.jobs.some(j=>j.kind==='blueveil'))blocked.push('Blue Veil is already in preparation');const cost={intel:40,influence:55,energy:50,rare:8,exotic:4};blocked.push(...this.shortages(cost));return {cost,days:365,blocked};}
 blueVeil(mode){if(!['debunk','threat','contact'].includes(mode))return this.result(false,'Choose a Blue Veil objective');const p=this.bluePreview();if(p.blocked.length)return this.result(false,p.blocked[0]);this.pay(p.cost);this.enqueue('blueveil',mode,p.days,{cost:p.cost,command:2});this.start();return this.result(true,'Project Blue Veil is in preparation');}
 emergency(){if(!this.hasModule('recovery'))return this.result(false,'A Recovery Bay is required');if((this.s.cooldowns.emergency||0)>this.s.day)return this.result(false,'Local debris field is regenerating; try another surveyed cache');if(this.s.jobs.some(j=>j.kind==='emergency'))return this.result(false,'Emergency salvage is already underway');const cost={energy:12};if(!this.pay(cost))return this.result(false,this.shortages(cost)[0]);this.enqueue('emergency','salvage',120,{cost});this.s.cooldowns.emergency=this.s.day+730;this.start();return this.result(true,'Local salvage drones deployed');}
 claimGuide(){const g=GUIDE[this.s.guide];if(!g||!g.test(this.s))return this.result(false,'Complete the directive first');this.gain(g.reward);this.s.guide++;this.log(`Directive complete: ${g.title}`,'milestone');return this.result(true,'Directive complete. Supplies delivered!');}
 regions(){return [...new Set([...this.s.bases.map(b=>this.country(b.country)?.bloc),...this.s.fronts.map(f=>this.country(f.country)?.bloc),...this.s.treaties.filter(t=>t.active).map(t=>this.country(t.country)?.bloc),...this.s.agents.filter(a=>a.phase==='active').map(a=>this.country(a.country)?.bloc)].filter(Boolean))];}
 trustedRegions(){return [...new Set(this.s.treaties.filter(t=>t.active&&this.country(t.country)?.trust>=55).map(t=>this.country(t.country).bloc))];}
 control(){const active=this.countries().filter(c=>c.contact>=2||c.infiltration>0||c.leverage>0);const best={};for(const c of active){const political=clamp(c.leverage*.4+c.trust*.25+c.contact*8+c.dependence*.3);best[c.bloc]=Math.max(best[c.bloc]||0,political);}
  const breadth=Math.min(1,this.regions().length/5);const regional=Object.values(best).sort((a,b)=>b-a).slice(0,5);const agents=this.s.agents.filter(a=>a.phase==='active');const techDep={};for(const c of active)techDep[c.bloc]=Math.max(techDep[c.bloc]||0,c.dependence);
  const pieces={political:clamp(sum(regional)/5),economic:clamp(sum(this.s.fronts,f=>f.level)*5+sum(active,c=>c.dependence*.08))*breadth,penetration:clamp(sum(agents,a=>a.access)/5)*breadth,infrastructure:clamp(this.s.bases.length*7+this.regions().length*6),technology:clamp(sum(Object.values(techDep).sort((a,b)=>b-a).slice(0,5))/5),information:clamp(sum(Object.values(this.s.narratives).filter(n=>n.active),n=>n.reach)*.12+agents.filter(a=>a.institution==='media').length*16+this.s.researched.filter(id=>id.startsWith('information')||id.startsWith('cognitive')).length*3)};
  const total=pieces.political*.2+pieces.economic*.2+pieces.penetration*.2+pieces.infrastructure*.15+pieces.technology*.15+pieces.information*.1;return {total:Math.round(total*10)/10,pieces,regions:this.regions().length,trusted:this.trustedRegions().length};}
 projectConditions(id){const s=this.s,c=this.control(),checks=[];const add=(text,ok)=>checks.push({text,ok:!!ok});const p=PROJECTS[id];if(!p)return [{text:'Unknown project',ok:false}];add(TECHS[p.req].name,this.tech(p.req));
  if(id==='silent'){add('Control at least 80',c.total>=80);add('Presence across 5 regions',c.regions>=5);add('Public Evidence below 55',s.metrics.evidence<55);add('Narrative Coherence below 65',s.metrics.coherence<65);add('Fewer than 3 coalition members',s.coalition.length<3);}
  if(id==='accord'){add('Trusted secret accords in 4 regions',c.trusted>=4);add('Panic below 55',s.metrics.panic<55);}
  if(id==='shepherd'){add('Welfare at least 80',s.doctrine.welfare>=80);add('Six completed relief efforts',(s.stats.relief||0)>=6);add('Four active bases',s.bases.length>=4);add('Three trusted regions',c.trusted>=3);}
  if(id==='sovereign'){add('Year 2035 or later',this.year>=2035);add('24 research nodes completed',s.researched.length>=24);add('Three voluntary partnerships',s.stats.treaties>=3);}
  if(id==='merge'){add('Year 2025 or later',this.year>=2025);add('Shared Language researched',this.tech('cognitive4'));add('Three trusted regions',c.trusted>=3);}
  if(id==='occupation'){add('Control at least 70',c.total>=70);add('Presence across 5 regions',c.regions>=5);add('Coercion at least 20',s.doctrine.coercion>=20);add('Openly established presence',s.open);}
  return checks;}
 startProject(id){const p=PROJECTS[id];if(!p)return this.result(false,'Unknown project');if(this.s.jobs.some(j=>j.kind==='project')||this.s.projectReady)return this.result(false,'A final project is already active');const checks=this.projectConditions(id);const fail=checks.find(c=>!c.ok);if(fail)return this.result(false,fail.text);if(!this.pay(p.cost))return this.result(false,this.shortages(p.cost)[0]);this.enqueue('project',id,p.days,{cost:clone(p.cost)});this.start();this.log(`Final project initiated: ${p.name}.`,'milestone');return this.result(true,'The final project has begun');}
 finalize(){const id=this.s.projectReady;if(!id)return this.result(false,'No final project is ready');const fail=this.projectConditions(id).find(c=>!c.ok);if(fail)return this.result(false,fail.text);this.finish(id);return {ok:true};}
 finish(id){if(this.s.ended)return;this.s.ended={id,day:this.s.day,control:this.control().total,seed:this.s.seed};this.s.speed=0;this.s.eventQueue=[];if(id==='accord'||id==='merge'||id==='occupation')this.s.open=true;if(id==='sovereign'){for(const c of this.countries()){c.dependence*=.25;c.leverage*=.25;}this.s.doctrine.autonomy+=30;}this.log(`Campaign ended: ${id}.`,'ending');}
 addEvidence(name,country,strength=3,type='witness',isPublic=true,tag='sighting'){if(!this.country(country))country='840';this.s.evidence.push({id:this.id('evidence'),name,country,strength:Math.max(0,strength),type,public:isPublic,tag,day:this.s.day,contained:false});if(this.s.evidence.length>350){const i=this.s.evidence.findIndex(e=>e.contained||e.strength<.2);if(i>=0)this.s.evidence.splice(i,1);}this.updateMetrics();}
 contain(amount,country=null){let remaining=amount;const eligible=this.s.evidence.filter(e=>!e.contained&&(!country||e.country===country)&&(!e.public||e.type==='witness'||e.type==='report')).sort((a,b)=>a.strength-b.strength);for(const e of eligible){if(remaining<=0)break;const reduction=Math.min(e.strength,remaining);e.strength-=reduction;remaining-=reduction;if(e.strength<.1)e.contained=true;}this.updateMetrics();return amount-remaining;}
 updateMetrics(){this.s.metrics.evidence=clamp(sum(this.s.evidence.filter(e=>e.public&&!e.contained),e=>e.strength));for(const k of metricKeys)this.s.metrics[k]=clamp(this.s.metrics[k]);}
 raise(id,context={}){if(!EVENTS[id]||this.s.ended)return;if(this.s.eventQueue.some(e=>e.id===id&&e.context.country===context.country))return;if(this.s.eventQueue.length>=3){this.s.scheduled.push({id,day:this.s.day+30,context});return;}this.s.eventQueue.push({id,uid:this.id('event'),day:this.s.day,context});this.s.speed=0;this.log(`Incoming: ${EVENTS[id].title}`,'event',context.country);}
 eventView(){
  const e=this.s.eventQueue[0];if(!e)return null;
  const d=EVENTS[e.id],c=this.country(e.context.country);let title=d.title,body=d.body;
  if(e.context.echo&&d.echo){title=d.echo.title;body=d.echo.body;}
  const choices=d.choices.map(ch=>{const cost=ch.cost||{},blocked=[...this.shortages(cost)];
   if(ch.requires==='recovery'&&!this.s.craft.some(a=>a.type==='recovery'||a.type==='platform'))blocked.push('No recovery-capable craft');
   if(ch.requires==='contact'&&(c?.contact||0)<2)blocked.push('Requires a backchannel');return {...ch,blocked};});
  // A mandatory paused event must never require currency the player cannot obtain while paused.
  // Declining intervention is costly in world-state consequences, but never resource-gated.
  if(!choices.some(ch=>!ch.blocked.length))choices.push({id:'stand_down',label:'Accept the consequences',text:'The Network cannot fund an intervention. Let this incident run its course; public scrutiny and local suspicion rise.',cost:{},effects:{belief:5,evidence:3,coherence:4,suspicion:6,pattern:3},blocked:[]});
  return {...d,...e,title,body:body.replaceAll('{country}',c?.name||'the region'),choices};
 }
 choose(choiceId){const v=this.eventView();if(!v)return this.result(false,'No pending decision');const ch=v.choices.find(c=>c.id===choiceId);if(!ch)return this.result(false,'Unknown choice');if(ch.blocked.length)return this.result(false,ch.blocked[0]);this.pay(ch.cost);const e=this.s.eventQueue.shift();this.applyEffects(ch.effects,e.context,v.title);this.s.history.unshift({id:e.id,uid:e.uid,day:e.day,title:v.title,body:v.body,choice:ch.label,country:e.context.country,effects:clone(ch.effects)});this.s.history=this.s.history.slice(0,250);this.s.stats.decisions=(this.s.stats.decisions||0)+1;this.log(`${v.title} — ${ch.label}`,'decision',e.context.country);this.updateMetrics();return {ok:true};}
 applyEffects(e,ctx={},title='Network incident'){const s=this.s,c=this.country(ctx.country),a=s.agents.find(a=>a.id===ctx.agent),b=s.bases.find(b=>b.id===ctx.base);
  for(const[k,v]of Object.entries(e)){
   if(RESOURCES[k]){this.gain({[k]:v});continue;}
   if(['belief','coherence','panic'].includes(k)){s.metrics[k]=clamp(s.metrics[k]+v);continue;}
   if(k==='trust'){s.metrics.trust=clamp(s.metrics.trust+v*.25);if(c)c.trust=clamp(c.trust+v,-100,100);continue;}
   if(['knowledge','hostility','dependence','leverage','insight','suspicion'].includes(k)){if(c)c[k]=clamp(c[k]+v);continue;}
   if(k==='evidence'){if(v>0)this.addEvidence(title,ctx.country,v,v>=5?'document':'witness',true,'incident');else this.contain(-v,ctx.country);continue;}
   if(k==='contact'){if(c)c.contact=Math.max(c.contact,v);continue;}
   if(k==='artifact'){if(c){c.artifact+=v;c.research=clamp(c.research+4);}continue;}
   if(k==='humanResearch'){if(c)c.research=clamp(c.research+v);continue;}
   if(k==='pattern'){s.pattern=clamp(s.pattern+v);continue;}if(k==='footprint'){s.footprint=clamp(s.footprint+v,0,200);continue;}
   if(k==='noise'){s.noiseUses+=v;s.pattern=clamp(s.pattern+v*2);continue;}
   if(k==='welfare'){s.doctrine.welfare=clamp(s.doctrine.welfare+v);continue;}
   if(['coercion','autonomy','intervention'].includes(k)){s.doctrine[k]=clamp(s.doctrine[k]+v);continue;}
   if(k==='relief'){s.stats.relief=(s.stats.relief||0)+v;continue;}if(k==='flag'){s.flags[v]=true;continue;}if(k==='open'){s.open=!!v;continue;}
   if(k==='disclosureIntent'){s.flags.contactIntent=true;continue;}if(k==='shield'){s.flags.shieldUntil=s.day+1825;continue;}
   if(k==='globalHostility'){for(const x of this.countries())if(x.knowledge>20)x.hostility=clamp(x.hostility+v);continue;}
   if(k==='rivalry'){if(c)this.rivalry(c);continue;}
   if(k==='baseSearch'&&b){b.search=clamp(b.search+v);b.warned=false;continue;}
   if(k==='evacuate'&&b){this.evacuate(b.id);continue;}
   if(k==='agentAutonomy'&&a){a.autonomous=true;a.loyalty=clamp(a.loyalty+20);a.access=clamp(a.access+10);a.attachment=clamp(a.attachment+10);continue;}
   if(k==='agentLoyalty'&&a){a.loyalty=clamp(a.loyalty+v);continue;}if(k==='agentAttachment'&&a){a.attachment=clamp(a.attachment+v);continue;}
   if(k==='agentCover'&&a){a.cover=clamp(a.cover+v);continue;}if(k==='agentSuspicion'&&a){a.suspicion=clamp(a.suspicion+v);a.warned=false;continue;}
   if(k==='agentRecall'&&a){s.jobs=s.jobs.filter(j=>j.agent!==a.id);s.agents=s.agents.filter(x=>x.id!==a.id);continue;}
  }
 }
 evacuate(id){const b=this.s.bases.find(b=>b.id===id);if(!b)return;this.s.bases=this.s.bases.filter(x=>x.id!==id);this.s.jobs=this.s.jobs.filter(j=>j.base!==id);this.log(`${b.name} evacuated.`,'warning',b.country);if(!this.s.bases.length)this.finish('expelled');}
 rates(){const r=Object.fromEntries(Object.keys(RESOURCES).map(k=>[k,0]));const power=this.s.resources.energy>.1;for(const b of this.s.bases){const d=BASES[b.type];for(const[k,v]of Object.entries(d.yield)){if(k!=='energy'&&!power)continue;r[k]+=v*(this.tech('extraction3')&&['common','precious','rare'].includes(k)?1.3:1);}
   r.energy+=(b.modules.power||0)*.55-(b.modules.masker||0)*.08-.12;
   if(power){r.bio+=(b.modules.bio||0)*.04;r.intel+=(b.modules.intel||0)*.1;r.capital+=(b.modules.logistics||0)*.025;}}
  r.energy-=this.s.craft.length*.008+this.s.agents.length*.01;if(power){for(const f of this.s.fronts){const c=this.country(f.country);r.capital+=.052*f.level*(c.industry/70)*(c.bloc==='usa'?1.2:1)*(this.tech('human3')?1.3:1);}
   for(const a of this.s.agents.filter(a=>a.phase==='active')){r.intel+=.02+a.access*.00045;r.influence+=.025+a.access*.00065+(a.autonomous?.015:0);if(a.institution==='finance')r.capital+=a.access*.0009;}
   if(this.tech('fabrication5'))r.exotic+=this.tech('fabrication6')?.018:.009;
  }
  r.influence+=.005;r.intel+=.012;return r;}
 baseSignature(b){let sig=BASES[b.type].signature+sum(Object.values(b.modules))*1.4-(b.modules.masker||0)*7;if(this.tech('stealth2'))sig*=.85;if(this.tech('stealth6'))sig*=.7;if(this.clause(b.country,'lease'))sig*=.65;return Math.max(1,sig);}
 complete(j){const s=this.s,c=this.country(j.country);if(j.kind==='op'){this.resolveOp(j);return;}
  if(j.kind==='base'){const d=BASES[j.subtype],n=s.bases.length+1;const name=j.subtype==='ocean'?`Pelagic ${n}`:j.subtype==='lunar'?`Far Side ${n}`:j.subtype==='orbital'?`Orbital Nest ${n}`:`${d.name} ${n}`;let lat=c.lat,lon=c.lon;if(j.subtype==='ocean'){lat=clamp(c.lat*.35,-55,55);lon=((c.lon+35+180)%360)-180;}if(j.subtype==='polar')lat=c.lat>=0?78:-76;
   s.bases.push({id:this.id('base'),type:j.subtype,name,country:j.country,lat,lon,modules:Object.fromEntries(d.starts.map(k=>[k,1])),search:0,health:100,warned:false});s.pattern=clamp(s.pattern+2);this.notice(`${name} is operational`);this.log(`${name} completed.`,'build',j.country);}
  if(j.kind==='module'){const b=s.bases.find(b=>b.id===j.base);if(b){b.modules[j.subtype]=(b.modules[j.subtype]||0)+1;if(j.subtype==='masker')b.search=clamp(b.search-15);this.notice(`${MODULES[j.subtype].name} installed`);}}
  if(j.kind==='craft'){const names=['Pebble','Sprout','Button','Mochi','Orbit','Noodle','Tumble','Comet','Puddle','Jelly','Sprocket','Moonbeam'];const name=names[(s.idCounter)%names.length]+' '+(s.stats.craftBuilt||1);s.craft.push({id:this.id('craft'),type:j.subtype,name,busy:null,health:100});s.stats.craftBuilt=(s.stats.craftBuilt||0)+1;this.notice(`${name} is ready for assignment`);}
  if(j.kind==='research'){if(!this.tech(j.subtype))s.researched.push(j.subtype);this.notice(`Research complete: ${TECHS[j.subtype].name}`);this.log(`Researched ${TECHS[j.subtype].name}.`,'research');}
  if(j.kind==='agent'){const d=INFILTRATION[j.subtype];const index=s.stats.agentsBuilt||0;s.stats.agentsBuilt=index+1;const a={id:this.id('agent'),name:AGENT_NAMES[index%AGENT_NAMES.length]+(index>=AGENT_NAMES.length?' '+(index+1):''),method:j.subtype,country:j.country,institution:j.institution,phase:'career',progress:0,careerDays:j.careerDays,cover:clamp(d.cover+(this.tech('bio2')?10:0)),access:d.access,influence:45,competence:60+Math.floor(this.rand()*20),adaptation:this.tech('bio6')?96:65,attachment:d.attachment,loyalty:92,suspicion:d.suspicion+(c.bloc==='china'&&j.subtype==='replacement'?8:0),born:s.day,busy:null,autonomous:false,warned:false,attachmentEvent:false};s.agents.push(a);if(j.subtype==='replacement')s.doctrine.coercion=clamp(s.doctrine.coercion+8);this.notice(`${a.name} is beginning a human career`);this.log(`${a.name} entered ${INSTITUTIONS[a.institution]} in ${c.name}.`,'agent',c.id);}
  if(j.kind==='agent_action'){const a=s.agents.find(a=>a.id===j.agent);if(a){a.busy=null;a.cooldown=s.day+365;if(j.subtype==='promote'){a.access=clamp(a.access+18,0,98);a.cover=clamp(a.cover+5);a.suspicion=clamp(a.suspicion+7);a.influence=clamp(a.influence+8);this.notice(`${a.name} earned a promotion`);}else{c.leverage=clamp(c.leverage+7+a.access*.07);c.dependence=clamp(c.dependence+6);a.suspicion=clamp(a.suspicion+5);s.pattern=clamp(s.pattern+2);if(a.institution==='defense')c.policyUntil=s.day+1095;if(a.institution==='science')c.research=clamp(c.research-9);if(a.institution==='industry')this.gain({common:12,rare:5});if(a.institution==='finance')this.gain({capital:22});if(a.institution==='media')s.metrics.coherence=clamp(s.metrics.coherence-6);if(a.institution==='executive')c.trust=clamp(c.trust+10,-100,100);this.notice(`${a.name} secured institutional support`);}}}
  if(j.kind==='emergency'){this.gain({common:10,rare:4,precious:3,exotic:this.tech('fabrication4')?3:2});this.notice('Local salvage delivered usable feedstock');}
  if(j.kind==='blueveil'){s.cooldowns.blueveil=s.day+3650;this.s.pattern=clamp(this.s.pattern+15);if(j.subtype==='debunk'){s.metrics.coherence=clamp(s.metrics.coherence-25);s.metrics.belief=clamp(s.metrics.belief+10);s.metrics.panic=clamp(s.metrics.panic+6);s.noiseUses+=3;}if(j.subtype==='threat'){s.metrics.panic=clamp(s.metrics.panic+22);s.doctrine.coercion=clamp(s.doctrine.coercion+10);for(const c of this.countries().filter(c=>c.contact>=2)){c.dependence=clamp(c.dependence+20);c.hostility=clamp(c.hostility+8);}}if(j.subtype==='contact'){s.metrics.trust=clamp(s.metrics.trust+20);s.metrics.belief=clamp(s.metrics.belief+20);s.metrics.coherence=clamp(s.metrics.coherence+10);s.metrics.panic=clamp(s.metrics.panic-8);s.flags.contactIntent=true;}if(this.rand()<.45)this.s.scheduled.push({id:'blue_backfire',day:s.day+240+Math.floor(this.rand()*365),context:{country:'840'}});this.notice('Project Blue Veil has reached its audience');}
  if(j.kind==='project'){s.projectReady=j.subtype;s.speed=0;this.notice('Final project ready. Choose your future in the Future panel.');if(!this.projectConditions(j.subtype).every(c=>c.ok))this.raise('final_conditions');}
 }
 resolveOp(j){const s=this.s,c=this.country(j.country),d=OPERATIONS[j.subtype],a=s.craft.find(a=>a.id===j.asset);if(a)a.busy=null;if(!c)return;let reward={...d.reward};const incident=j.roll*100<j.risk,catastrophic=a&&j.roll*100<j.risk*.10,partial=!catastrophic&&j.roll*100<j.risk*.28;
  if(catastrophic){s.craft=s.craft.filter(x=>x.id!==a.id);s.stats.losses=(s.stats.losses||0)+1;c.suspicion=clamp(c.suspicion+12);this.addEvidence(`${a.name}: missing field system`,c.id,3,'radar',false,'hardware');this.raise('craft_lost',{country:c.id});this.log(`${a.name} was lost in ${c.name}.`,'warning',c.id);return;}
  if(partial){reward=Object.fromEntries(Object.entries(reward).map(([k,v])=>[k,Math.floor(v*.5)]));if(a)a.health=clamp(a.health-18);this.notice(`${d.name}: partial success`,'warning');}
  if(j.subtype==='mine'){const mult=(this.tech('extraction1')?1.15:1)*(a?.type==='surveyor'?1.2:1);reward=Object.fromEntries(Object.entries(reward).map(([k,v])=>[k,Math.round(v*mult)]));}
  if(j.subtype==='salvage'&&(this.tech('extraction6')||this.tech('extraction4')))reward.exotic+=this.tech('extraction6')?2:1;
  if(j.subtype==='sample'&&a?.type==='collector')reward.bio+=8;if(j.subtype==='observe'&&a?.type==='signal')reward.intel+=6;
  this.gain(reward);s.stats[j.subtype]=(s.stats[j.subtype]||0)+1;
  if(j.subtype==='observe'){c.insight=clamp(c.insight+27);c.contact=Math.max(c.contact,1);}
  if(j.subtype==='survey'){c.surveyed=true;c.insight=clamp(c.insight+12);}
  if(j.subtype==='signals'){c.insight=clamp(c.insight+30);if(c.artifact)this.log(`A classified research program was located in ${c.name}.`,'intel',c.id);}
  if(j.subtype==='contact'){c.contact=Math.max(c.contact,2);c.trust=clamp(c.trust+22,-100,100);c.knowledge=clamp(c.knowledge+18);c.hostility=clamp(c.hostility-5);}
  if(j.subtype==='cultivate'){c.trust=clamp(c.trust+18,-100,100);c.contact=Math.max(c.contact,3);c.hostility=clamp(c.hostility-9);c.suspicion=clamp(c.suspicion-6);}
  if(j.subtype==='front'&&!s.fronts.some(f=>f.country===c.id)){const name=COMPANY_NAMES[s.fronts.length%COMPANY_NAMES.length];s.fronts.push({id:this.id('front'),name,country:c.id,level:1,cover:55,started:s.day});c.leverage=clamp(c.leverage+6);s.footprint=clamp(s.footprint+4,0,200);}
  if(j.subtype==='conceal'){const amount=10+(this.tech('information4')?6:0)+(this.tech('stealth4')?3:0);this.contain(amount,c.id);c.suspicion=clamp(c.suspicion-12);s.metrics.coherence=clamp(s.metrics.coherence-4);s.pattern=clamp(s.pattern-3);}
  if(j.subtype==='recover'){if(c.artifact)c.artifact--;c.research=clamp(c.research-15);c.hostility=clamp(c.hostility+15);c.trust=clamp(c.trust-14,-100,100);if(this.clause(c.id,'noninterference')){this.treaty(c.id).active=false;c.hostility=clamp(c.hostility+15);c.memory.unshift('The non-interference clause was breached.');}for(const e of s.evidence.filter(e=>e.country===c.id&&e.type==='artifact'&&!e.public))e.contained=true;}
  if(j.subtype==='reassure'){s.metrics.panic=clamp(s.metrics.panic-(this.tech('cognitive2')?12:8));s.metrics.trust=clamp(s.metrics.trust+4);c.trust=clamp(c.trust+8,-100,100);}
  if(j.subtype==='relief'){s.doctrine.welfare=clamp(s.doctrine.welfare+(this.tech('cognitive5')?5:3));s.doctrine.intervention=clamp(s.doctrine.intervention+2);c.trust=clamp(c.trust+10,-100,100);c.dependence=clamp(c.dependence+4);}
  s.cooldowns[j.subtype+':'+c.id]=s.day+d.cooldown;
  if(incident){c.suspicion=clamp(c.suspicion+5);c.knowledge=clamp(c.knowledge+4);if(c.bloc==='russia')c.hostility=clamp(c.hostility+3);const quality=(this.year>=2000?3:1.5)*(this.clause(c.id,'recovery')?.5:1);this.addEvidence(`${d.name} trace in ${c.name}`,c.id,quality,'witness',true,'sighting');s.metrics.belief=clamp(s.metrics.belief+2);s.pattern=clamp(s.pattern+1);this.log(`${d.name} in ${c.name} succeeded with a trace.`,'warning',c.id);if(!partial)this.notice(`${d.name} completed — a trace remains`,'warning');}
  else {this.log(`${d.name} completed cleanly in ${c.name}.`,'success',c.id);if(!partial)this.notice(`${d.name} completed`);}
  this.updateMetrics();
 }
 monthly(){const s=this.s,m=s.metrics,year=this.year;const techs=this.era.sensor;let active=this.countries().filter(c=>c.contact>0||c.knowledge>0||c.suspicion>0);
  for(const c of active){const t=this.treaty(c.id);c.suspicion=clamp(c.suspicion-(t?.clauses.includes('secrecy')?.5:.18));c.insight=clamp(c.insight-.12);if(c.artifact)c.research=clamp(c.research+.10*c.science/70);if(t){c.dependence=clamp(c.dependence+.42);c.leverage=clamp(c.leverage+.16);c.hostility=clamp(c.hostility-.25);if(t.clauses.includes('noninterference'))c.trust=clamp(c.trust+.2,-100,100);if(t.clauses.includes('sensors')){this.gain({intel:3});c.insight=clamp(c.insight+.6);}if(t.clauses.includes('science')){this.gain({intel:c.bloc==='eu'?7:5});c.research=clamp(c.research+.25);}if(t.clauses.includes('resources')){const mult=c.bloc==='china'?1.25:1;this.gain({common:2*mult,rare:mult,precious:.7*mult});}if(t.clauses.includes('corridor')&&c.bloc==='arabia')this.gain({energy:5});if(t.clauses.includes('council'))c.leverage=clamp(c.leverage+.2);if(c.trust>=75)c.contact=5;}
   else c.trust=clamp(c.trust*.998,-100,100);
   if(c.suspicion>55)c.hostility=clamp(c.hostility+(c.suspicion-55)*.02);if(s.open&&c.knowledge>40&&!t)c.hostility=clamp(c.hostility+.2);
   if(c.knowledge>50&&c.hostility>45){c.research=clamp(c.research+.08*c.science/70);c.suspicion=clamp(c.suspicion+.15);}
   if(c.memory.length>10)c.memory.length=10;
  }
  for(const t of s.treaties){if(t.active&&t.expiry<=s.day){t.active=false;const c=this.country(t.country);c.trust=clamp(c.trust-8,-100,100);this.log(`Accord with ${c.name} has expired. Renewal remains possible.`,'diplomacy',c.id);this.notice(`Accord expired: ${c.name}`,'warning');}}
  const pen={};for(const a of s.agents.filter(a=>a.phase==='active')){const c=this.country(a.country);pen[c.id]=(pen[c.id]||0)+a.access*.65;a.attachment=clamp(a.attachment+(a.method==='life'?.25:.14));if(!a.autonomous&&a.attachment>45&&s.doctrine.coercion>10)a.loyalty=clamp(a.loyalty-.2);if(this.tech('bio5'))a.loyalty=clamp(a.loyalty+.08);a.cover=clamp(a.cover+.12);a.suspicion=clamp(a.suspicion+(c.ci/100)*(.05+(s.pattern>55?.10:0))*(this.tech('bio4')?.6:1)-.08-(a.autonomous?.05:0));
   if(a.attachment>=46&&!a.attachmentEvent){a.attachmentEvent=true;this.raise('agent_attachment',{country:c.id,agent:a.id});}
   if(a.suspicion>=68&&!a.warned){a.warned=true;this.raise('agent_exposure',{country:c.id,agent:a.id});}}
  for(const c of active)c.infiltration=clamp(pen[c.id]||0);
  for(const b of [...s.bases]){const c=this.country(b.country)||active[0];if(!c)continue;const protection=(b.modules.masker||0)*.20+(this.clause(c.id,'lease')?.4:0)+(this.tech('field6')?.35:0);const pressure=(this.baseSignature(b)/20)*(this.sensor(c)/60)*((c.hostility+20)/80)*this.factor()-.35-protection;b.search=clamp(b.search+pressure);if(b.search>62&&!b.warned){b.warned=true;this.raise('base_probe',{base:b.id,country:c.id});}if(b.search>=99){b.health-=10*(s.flags.shieldUntil>s.day?.4:1);b.search=80;b.warned=false;this.addEvidence(`Investigation of ${b.name}`,c.id,7,'document',true,'infrastructure');this.log(`${b.name} was damaged by human countermeasures.`,'warning',c.id);if(b.health<=0)this.evacuate(b.id);}}
  for(const [k,base]of Object.entries(MATERIAL_PRICE)){s.prices[k]=clamp(s.prices[k]+(base-s.prices[k])*.12+(this.rand()-.5)*base*.08,base*.6,base*1.7);}
  s.footprint=clamp(s.footprint-.7-this.moduleCount('logistics')*.1,0,200);
  const u=s.un;if(u){const accords=s.treaties.filter(t=>t.active).length;u.dependence=clamp(u.dependence+accords*.02-.01);if(accords)u.trust=clamp(u.trust+Math.min(.18,accords*.035),-100,100);if(!s.open){u.knowledge=clamp(u.knowledge+Math.max(0,m.evidence-25)*.004+Math.max(0,m.coherence-35)*.003);u.suspicion=clamp(u.suspicion+Math.max(0,m.coherence-45)*.002-.04);}else u.knowledge=100;if(u.framework){u.legitimacy=clamp(u.legitimacy+(u.trust>40?.08:-.03));m.panic=clamp(m.panic-.04);if(s.open)m.trust=clamp(m.trust+.02);}if(u.infiltration>0)u.infiltration=clamp(u.infiltration-.01);if(u.memory.length>10)u.memory.length=10;}
  let patternDrift=Math.max(0,s.bases.length-5)*.015+Math.max(0,s.fronts.length-4)*.025+Math.max(0,s.agents.length-5)*.01+(s.footprint>60?(s.footprint-60)*.002:0)-.10;
  if(year>=2029)patternDrift+=.12+s.noiseUses*.004;if(this.tech('stealth5'))patternDrift-=.13;if(this.tech('information5'))patternDrift-=.12;s.pattern=clamp(s.pattern+patternDrift);
  for(const n of Object.values(s.narratives).filter(n=>n.active)){n.reach=clamp(n.reach+n.virality*.003-(n.reach>75?.22:0));m.belief=clamp(m.belief+n.reach*.0005);const actualTruth=n.id==='moon'?(s.bases.some(b=>b.type==='lunar')?80:10):n.id==='retrieval'?(active.some(c=>c.artifact)?85:20):n.truth;m.coherence=clamp(m.coherence+(actualTruth>55?n.reach*.00065:-n.reach*.00025));m.panic=clamp(m.panic+n.panic*n.reach*.000003-.012);}
  m.belief=clamp(m.belief+m.evidence*.003-.045);m.coherence=clamp(m.coherence+(m.evidence>20?(m.evidence-20)*.001:0)+(year>=2029?s.pattern*.001:0)-.025);m.panic=clamp(m.panic-.05);m.trust=clamp(m.trust-.007);
  for(const e of s.evidence)if(e.type==='witness'&&s.day-e.day>3650)e.strength*=.995;
  this.updateMetrics();const candidates=active.filter(c=>c.knowledge>=60&&c.hostility>=65);const unique=new Set(candidates.map(c=>c.bloc));s.coalition=unique.size>=3?candidates.map(c=>c.id):[];
  if(s.coalition.length>=3&&!s.flags.coalitionWarned){s.flags.coalitionWarned=true;this.raise('coalition_warning',{country:s.coalition[0]});}
  if(!s.open&&!s.flags.disclosureRaised&&m.evidence>=65&&m.coherence>=65){s.flags.disclosureRaised=true;this.raise('disclosure',{country:active.sort((a,b)=>b.knowledge-a.knowledge)[0]?.id||'840'});}
  for(const bloc of ['arabia','asia'])if(!s.formed[bloc]&&year>=1995){const members=active.filter(c=>c.bloc===bloc&&this.treaty(c.id)&&c.trust>=45);if(members.length>=3){s.formed[bloc]=true;this.log(`${BLOCS[bloc].name} formed around cooperative regional agreements.`,'milestone');this.notice(`${BLOCS[bloc].name} has formed`);}}
  if(s.resources.energy<1&&!s.flags.shortageShown){s.flags.shortageShown=true;this.raise('shortage');}if(s.resources.energy>25)s.flags.shortageShown=false;
  if(s.day-s.lastDynamic>=540&&s.day>240&&!s.eventQueue.length){s.lastDynamic=s.day;const pool=active.length?active:this.countries().filter(c=>['840','156','643'].includes(c.id));const c=pool[Math.floor(this.rand()*pool.length)];const id=DYNAMIC[Math.floor(this.rand()*DYNAMIC.length)];this.raise(id,{country:c?.id||'840'});}
 }
 considerHistory(){const s=this.s;if(s.eventQueue.length||s.day-s.lastHistory<210)return;for(const id of HISTORY){if(s.fired.includes(id))continue;const d=EVENTS[id];if(s.day<yearDay(d.year)+120)break;s.fired.push(id);s.lastHistory=s.day;const c=this.country(d.country)||this.countries()[0];let echo=false;if(id==='first_recovery')echo=!(this.country('840')?.insight>=20&&(s.stats.observe||0)>0);if(id==='carrier_echo')echo=(this.country('840')?.insight||0)<35;if(id==='rob_lazer')echo=!this.countries().some(c=>c.artifact>0);if(id==='naval_leak')echo=!s.flags.carrier_archive;this.raise(id,{country:c.id,echo});break;}}
 advance(days=1,{autoResolve=false}={}){days=Math.min(40000,Math.max(0,Math.floor(days)));let done=0;for(let i=0;i<days;i++){
  if(this.s.ended)break;if(this.s.eventQueue.length){if(!autoResolve)break;const view=this.eventView(),ch=view?.choices.find(c=>!c.blocked.length);if(ch)this.choose(ch.id);else break;}
  const s=this.s;s.day++;done++;const rates=this.rates();this.gain(rates);
  for(const a of s.agents)if(a.phase==='career'){a.progress++;if(a.progress>=a.careerDays){a.phase='active';a.progress=a.careerDays;this.notice(`${a.name} is now embedded in ${this.country(a.country).name}`);this.log(`${a.name}'s cover career is established.`,'agent',a.country);}}
  const ready=s.jobs.filter(j=>j.finish<=s.day);s.jobs=s.jobs.filter(j=>j.finish>s.day);for(const j of ready)this.complete(j);
  if(s.day%30===0)this.monthly();
  const scheduled=s.scheduled.filter(e=>e.day<=s.day);s.scheduled=s.scheduled.filter(e=>e.day>s.day);for(const e of scheduled)this.raise(e.id,e.context);
  this.considerHistory();if(START+s.day*DAY>=END){if(s.projectReady&&this.projectConditions(s.projectReady).every(c=>c.ok))this.finalize();else if(!s.ended)this.finish(s.open&&s.coalition.length>=3?'war':'expelled');}
 }return done;}
 export(){return JSON.stringify({format:'alien-invader-save',version:VERSION,state:this.s});}
 static restore(text,defs){let raw;try{raw=typeof text==='string'?JSON.parse(text):text;}catch{throw new Error('This file is not valid JSON. Your current game was not changed.');}
  if(raw?.format!=='alien-invader-save'||![VERSION,'1.0.0-browser'].includes(raw.version))throw new Error('This save uses a different format or build version.');const s=raw.state;
  if(!s||!Number.isInteger(s.day)||s.day<0||s.day>40000||!Number.isFinite(s.rng)||!Number.isInteger(s.idCounter))throw new Error('Invalid simulation clock or seed.');
  if(!s.un)s.un={contact:0,trust:0,dependence:0,suspicion:0,infiltration:0,knowledge:0,hostility:0,legitimacy:0,briefed:false,framework:false,memory:[]};
  for(const k of ['contact','trust','dependence','suspicion','infiltration','knowledge','hostility','legitimacy'])if(!Number.isFinite(s.un[k]))throw new Error('Invalid United Nations metrics.');if(!Array.isArray(s.un.memory))s.un.memory=[];
  for(const k of Object.keys(RESOURCES))if(!Number.isFinite(s.resources?.[k])||s.resources[k]<0||s.resources[k]>1e8)throw new Error('Invalid resource data.');
  for(const key of ['bases','craft','agents','fronts','jobs','treaties','researched','eventQueue','scheduled','evidence','fired','history','logs'])if(!Array.isArray(s[key])||s[key].length>1000)throw new Error('Invalid campaign collections.');
  const known=new Set(defs.map(d=>d.id));for(const c of Object.values(s.countries||{})){if(!known.has(c.id)||!BLOCS[c.bloc])throw new Error('The world map does not match this save.');for(const k of countryKeys)if(!Number.isFinite(c[k]))throw new Error('Invalid country metrics.');}
  if(Object.keys(s.countries||{}).length!==defs.length)throw new Error('The save is missing countries.');
  for(const b of s.bases)if(!BASES[b.type]||!known.has(b.country)||!b.modules||Object.keys(b.modules).some(k=>!MODULES[k]))throw new Error('Invalid base definition.');
  for(const a of s.craft)if(!CRAFT[a.type]||!Number.isFinite(a.health))throw new Error('Invalid craft definition.');
  for(const a of s.agents)if(!INFILTRATION[a.method]||!INSTITUTIONS[a.institution]||!known.has(a.country))throw new Error('Invalid interface definition.');
  for(const id of s.researched)if(!TECHS[id])throw new Error('Invalid research definition.');for(const e of [...s.eventQueue,...s.scheduled])if(!EVENTS[e.id])throw new Error('Invalid event definition.');
  const jobKinds=new Set(['op','base','module','craft','agent','research','agent_action','emergency','blueveil','project']);for(const j of s.jobs)if(!jobKinds.has(j.kind)||!Number.isFinite(j.finish)||!Number.isFinite(j.duration)||j.duration<1)throw new Error('Invalid queued job.');
  s.version=VERSION;const game=new Game(defs,{seed:s.seed,difficulty:s.difficulty,pace:s.pace});game.s=clone(s);game.s.speed=0;game.s.notices=[];game.s.settings={sound:true,music:true,reducedMotion:false,autoPause:true,...s.settings};game.updateMetrics();return game;
 }
}
