import * as THREE from 'three';
import {OrbitControls} from './vendor/OrbitControls.js';
import {drawFeature} from './world.js';
import {BLOCS,clamp} from './data.js';
const RAD=Math.PI/180;
export const location=(lat,lon,r=2.16)=>new THREE.Vector3(Math.cos(lat*RAD)*Math.cos(lon*RAD)*r,Math.sin(lat*RAD)*r,-Math.cos(lat*RAD)*Math.sin(lon*RAD)*r);
const mat=(color,extra={})=>new THREE.MeshStandardMaterial({color,roughness:.8,...extra});
function sphere(parent,radius,color,position=[0,0,0],scale=[1,1,1],material=null){const mesh=new THREE.Mesh(new THREE.SphereGeometry(radius,20,14),material||mat(color));mesh.position.set(...position);mesh.scale.set(...scale);parent.add(mesh);return mesh;}
function makeUFO(scale=1){const g=new THREE.Group();sphere(g,1,'#eaf1d9',[0,0,0],[.24,.052,.24]);const rim=new THREE.Mesh(new THREE.TorusGeometry(.216,.019,8,40),mat('#b09bcf'));rim.rotation.x=Math.PI/2;g.add(rim);sphere(g,1,'#c1b3dc',[0,.045,0],[.13,.055,.13]);sphere(g,1,'#8ed3b2',[0,.075,.018],[.047,.062,.043]);sphere(g,1,'#203e40',[-.018,.087,.052],[.012,.022,.008]);sphere(g,1,'#203e40',[.018,.087,.052],[.012,.022,.008]);const dome=sphere(g,1,'#d3f6ea',[0,.059,0],[.13,.11,.13],new THREE.MeshPhysicalMaterial({color:'#d3f6ea',transparent:true,opacity:.38,roughness:.1,metalness:.03,depthWrite:false}));dome.renderOrder=2;
 for(let i=0;i<8;i++){const a=i/8*Math.PI*2;sphere(g,.012,'#fff0a8',[Math.cos(a)*.214,-.005,Math.sin(a)*.214]);}g.scale.setScalar(scale);return g;}
export class Globe{
 constructor(container,world,onSelect,onBase){this.container=container;this.world=world;this.onSelect=onSelect;this.onBase=onBase;this.layer='political';this.selected=null;this.game=null;this.reduced=false;this.titleMode=true;this.zoomTarget=null;this.hover=null;this.lastMapKey='';this.lastAssets='';this.focusTarget=null;this.layers={};this.disposables=[];
  this.canvasMap=document.createElement('canvas');this.canvasMap.width=2048;this.canvasMap.height=1024;this.mapCtx=this.canvasMap.getContext('2d');this.idMap=document.createElement('canvas');this.idMap.width=2048;this.idMap.height=1024;const ic=this.idMap.getContext('2d',{willReadFrequently:true});ic.fillStyle='#000';ic.fillRect(0,0,2048,1024);
  for(const f of world.features){const n=f.mapIndex;drawFeature(ic,f,2048,1024,`rgb(${n&255},${n>>8&255},${n>>16&255})`);}this.idPixels=ic.getImageData(0,0,2048,1024).data;
  this.texture=new THREE.CanvasTexture(this.canvasMap);this.texture.colorSpace=THREE.SRGBColorSpace;this.texture.anisotropy=4;this.drawMap();
  this.renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,1.8));this.renderer.setClearColor(0x000000,0);this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.2;container.appendChild(this.renderer.domElement);this.renderer.domElement.setAttribute('aria-label','Interactive Earth. Drag to rotate, scroll to zoom, click a country.');this.renderer.domElement.setAttribute('role','img');
  this.scene=new THREE.Scene();this.camera=new THREE.PerspectiveCamera(35,1,.1,100);this.camera.position.copy(location(18,-25,8.8));this.controls=new OrbitControls(this.camera,this.renderer.domElement);this.controls.enableDamping=true;this.controls.dampingFactor=.075;this.controls.enablePan=false;this.controls.minDistance=5.7;this.controls.maxDistance=12;this.controls.rotateSpeed=.58;this.controls.zoomSpeed=.65;this.controls.autoRotate=true;this.controls.autoRotateSpeed=.35;
  this.scene.add(new THREE.HemisphereLight('#fffced','#6eafb3',2.1));const key=new THREE.DirectionalLight('#fff9e0',3);key.position.set(-3,5,5);this.scene.add(key);const fill=new THREE.DirectionalLight('#b8d9ff',1.1);fill.position.set(5,-1,-3);this.scene.add(fill);
  const geo=new THREE.SphereGeometry(2.1,160,100);const pos=geo.attributes.position,uv=geo.attributes.uv;
  for(let i=0;i<pos.count;i++){const idx=this.indexAt(uv.getX(i),1-uv.getY(i));if(idx>0){const v=new THREE.Vector3().fromBufferAttribute(pos,i).normalize().multiplyScalar(2.128+.006*Math.sin(i*1.7));pos.setXYZ(i,v.x,v.y,v.z);}}geo.computeVertexNormals();
  this.earth=new THREE.Mesh(geo,new THREE.MeshStandardMaterial({map:this.texture,roughness:.94,metalness:.015}));this.scene.add(this.earth);
  const atmos=new THREE.Mesh(new THREE.SphereGeometry(2.22,72,48),new THREE.ShaderMaterial({uniforms:{glow:{value:new THREE.Color('#b0e4db')}},vertexShader:'varying vec3 n;varying vec3 v;void main(){vec4 p=modelViewMatrix*vec4(position,1.0);n=normalize(normalMatrix*normal);v=-p.xyz;gl_Position=projectionMatrix*p;}',fragmentShader:'uniform vec3 glow;varying vec3 n;varying vec3 v;void main(){float rim=pow(1.0-abs(dot(normalize(n),normalize(v))),3.0);gl_FragColor=vec4(glow,rim*0.38);}',transparent:true,side:THREE.BackSide,depthWrite:false}));this.scene.add(atmos);
  this.addTerrain();this.addClouds();this.addOrbit();this.assets=new THREE.Group();this.scene.add(this.assets);this.moving=[];
  this.hero=makeUFO(1.35);this.scene.add(this.hero);this.heroOrbit=0;
  const selGeo=new THREE.RingGeometry(.074,.09,40);this.selection=new THREE.Mesh(selGeo,new THREE.MeshBasicMaterial({color:'#fff8ca',side:THREE.DoubleSide,transparent:true,opacity:.9,depthWrite:false}));this.scene.add(this.selection);
  this.labels=document.createElement('div');this.labels.className='globe-labels';container.appendChild(this.labels);this.tooltip=document.createElement('div');this.tooltip.className='map-tooltip';container.appendChild(this.tooltip);this.labelNodes=[];
  this.raycaster=new THREE.Raycaster();this.pointer=new THREE.Vector2();let down=null;
  this.renderer.domElement.addEventListener('pointerdown',e=>{down={x:e.clientX,y:e.clientY};this.focusTarget=null;});
  this.renderer.domElement.addEventListener('pointerup',e=>{if(down&&Math.hypot(e.clientX-down.x,e.clientY-down.y)<7){const f=this.pick(e);if(f)this.onSelect(f.id);}down=null;});
  this.renderer.domElement.addEventListener('pointermove',e=>{if(down){this.tooltip.style.display='none';return;}const f=this.pick(e);this.renderer.domElement.style.cursor=f?'pointer':'grab';if(f){const r=container.getBoundingClientRect();this.tooltip.textContent=f.name;this.tooltip.style.display='block';this.tooltip.style.left=`${Math.min(e.clientX-r.left+14,r.width-160)}px`;this.tooltip.style.top=`${e.clientY-r.top-35}px`;}else this.tooltip.style.display='none';});
  this.renderer.domElement.addEventListener('pointerleave',()=>this.tooltip.style.display='none');
  this.observer=new ResizeObserver(()=>this.resize());this.observer.observe(container);this.resize();this.frame=this.frame.bind(this);requestAnimationFrame(this.frame);
 }
 indexAt(u,v){const x=clamp(Math.floor(u*2048),0,2047),y=clamp(Math.floor(v*1024),0,1023),i=(y*2048+x)*4;const n=this.idPixels[i]+(this.idPixels[i+1]<<8)+(this.idPixels[i+2]<<16);return n<=this.world.features.length?n:0;}
 at(lat,lon){return this.indexAt((lon+180)/360,(90-lat)/180);}
 pick(e){const r=this.renderer.domElement.getBoundingClientRect();this.pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);this.raycaster.setFromCamera(this.pointer,this.camera);const hit=this.raycaster.intersectObject(this.earth)[0];if(!hit?.uv)return null;const n=this.indexAt(hit.uv.x,1-hit.uv.y);return this.world.features[n-1]||null;}
 color(f){const c=this.game?.country(f.id);if(this.selected===f.id)return '#f3d693';if(f.id==='010'||f.id==='304')return '#e2eddf';if(!c)return new THREE.Color(BLOCS[f.bloc].color).lerp(new THREE.Color('#a7ce9e'),.45).getStyle();
  const gradient=(a,b,t)=>new THREE.Color(a).lerp(new THREE.Color(b),clamp(t,0,1)).getStyle();
  if(this.layer==='sensors')return gradient('#c9dbc0','#df9688',this.game.sensor(c)/100);
  if(this.layer==='exposure')return gradient('#b8d8b7','#ed9d84',(c.suspicion+(c.insight>=75?c.knowledge:0)*.5)/130);
  if(this.layer==='intelligence')return gradient('#d9dece','#76b5ae',c.insight/100);
  if(this.layer==='resources')return c.surveyed?'#c9c886':'#a7c9b0';
  if(this.layer==='economy')return this.game.s.fronts.some(x=>x.country===f.id)?'#e8c37f':this.game.legal(f.id)?'#b8d399':'#a6c6b1';
  if(this.layer==='technology')return gradient('#c5d8b7','#aaa0ce',(c.insight>=60?c.research:0)/100);
  if(this.layer==='network')return this.game.regions().includes(c.bloc)?'#99cbb3':'#ccd5bb';
  if(this.game.treaty(c.id))return '#8dccae';if(c.hostility>60)return '#dda294';return new THREE.Color(BLOCS[f.bloc].color).lerp(new THREE.Color('#accc9e'),.35).getStyle();
 }
 drawMap(){const c=this.mapCtx,w=2048,h=1024;c.fillStyle='#7cbcc8';c.fillRect(0,0,w,h);c.lineWidth=.65;
  for(const f of this.world.features)drawFeature(c,f,w,h,this.color(f),'rgba(247,255,223,0.42)');
  if(this.selected){const f=this.world.features.find(f=>f.id===this.selected);if(f){c.lineWidth=2.2;drawFeature(c,f,w,h,null,'#fff7ce');}}
  this.texture.needsUpdate=true;
 }
 addTerrain(){const trees=new THREE.InstancedMesh(new THREE.ConeGeometry(.037,.115,6),mat('#58967b'),110);const trunks=new THREE.InstancedMesh(new THREE.CylinderGeometry(.008,.011,.048,5),mat('#a89068'),110);const dummy=new THREE.Object3D();let n=0,tries=0,seed=123;const rnd=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};
  while(n<110&&tries++<3000){const lat=-50+rnd()*112,lon=-180+rnd()*360;if(!this.at(lat,lon))continue;const r=location(lat,lon,1).normalize();dummy.position.copy(r.clone().multiplyScalar(2.181));dummy.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),r);dummy.scale.setScalar(.55+rnd()*.8);dummy.updateMatrix();trees.setMatrixAt(n,dummy.matrix);trees.setColorAt(n,new THREE.Color(['#6faa83','#68a083','#8bb58a'][n%3]));dummy.position.copy(r.clone().multiplyScalar(2.145));dummy.updateMatrix();trunks.setMatrixAt(n,dummy.matrix);n++;}trees.count=n;trunks.count=n;this.scene.add(trees,trunks);
  const mounts=new THREE.Group();const ranges=[[30,82],[35,95],[39,70],[46,10],[-20,-69],[-35,-70],[40,-110],[54,-120],[4,38],[-3,138],[-43,171]];for(let r=0;r<ranges.length;r++){for(let j=0;j<4;j++){const lat=ranges[r][0]+j*1.9,lon=ranges[r][1]+j*2.2;if(!this.at(lat,lon))continue;const g=new THREE.Group();const sz=.075+(j%3)*.018;const mount=new THREE.Mesh(new THREE.ConeGeometry(sz,sz*1.8,5),mat('#b8bfaa'));mount.position.y=sz*.52;g.add(mount);const cap=new THREE.Mesh(new THREE.ConeGeometry(sz*.48,sz*.85,5),mat('#f5f1dd'));cap.position.y=sz*1.1;g.add(cap);g.position.copy(location(lat,lon,2.125));g.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),g.position.clone().normalize());mounts.add(g);}}this.scene.add(mounts);
  const cities=new THREE.Group();for(const id of ['840','156','643','250','276','826','392','356','076','710','682','036']){const f=this.world.defs.find(f=>f.id===id);if(!f)continue;const g=new THREE.Group();for(let i=0;i<3;i++){const box=new THREE.Mesh(new THREE.BoxGeometry(.031,.045+i*.019,.035),mat(i%2?'#e7d3a6':'#f3e9ce'));box.position.set((i-1)*.045,.024+i*.009,0);g.add(box);}g.position.copy(location(f.lat,f.lon,2.143));g.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),g.position.clone().normalize());cities.add(g);}this.scene.add(cities);
 }
 addClouds(){this.clouds=new THREE.Group();const material=mat('#fffdf2',{transparent:true,opacity:.91});const geometry=new THREE.SphereGeometry(1,14,10);for(let i=0;i<17;i++){const lat=-48+(i*37)%106,lon=-180+(i*67)%360;const cluster=new THREE.Group();for(let j=0;j<4;j++){const p=new THREE.Mesh(geometry,material);p.scale.set(.075+j%2*.028,.037+j%3*.012,.067);p.position.set((j-1.5)*.083,j%2*.022,Math.sin(j)*.025);cluster.add(p);}cluster.position.copy(location(lat,lon,2.23));cluster.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),cluster.position.clone().normalize());this.clouds.add(cluster);}this.scene.add(this.clouds);}
 addOrbit(){const pts=[];for(let i=0;i<=160;i++){const a=i/160*Math.PI*2;pts.push(new THREE.Vector3(Math.cos(a)*2.8,Math.sin(a)*.62,Math.sin(a)*2.35));}const orbit=new THREE.Line(new THREE.BufferGeometry().setFromPoints(pts),new THREE.LineDashedMaterial({color:'#88b4ae',transparent:true,opacity:.32,dashSize:.045,gapSize:.055}));orbit.computeLineDistances();this.scene.add(orbit);
  const pts2=[];for(let i=0;i<110;i++){const a=i*2.399963;const r=4.5+(i%7)*.55;pts2.push(Math.cos(a)*r,Math.sin(a*1.9)*4.5,-4-(i%4));}const starGeo=new THREE.BufferGeometry();starGeo.setAttribute('position',new THREE.Float32BufferAttribute(pts2,3));this.stars=new THREE.Points(starGeo,new THREE.PointsMaterial({color:'#789993',size:.018,transparent:true,opacity:.4}));this.scene.add(this.stars);
 }
 resize(){const w=Math.max(1,this.container.clientWidth),h=Math.max(1,this.container.clientHeight);this.camera.aspect=w/h;this.camera.updateProjectionMatrix();this.renderer.setSize(w,h,false);}
 focus(id,instant=false){const f=this.world.defs.find(f=>f.id===id);if(!f)return;this.selected=id;const distance=clamp(this.camera.position.length(),7.6,10);this.focusTarget=location(f.lat*.72,f.lon,distance);if(instant){this.camera.position.copy(this.focusTarget);this.focusTarget=null;this.controls.update();}this.selection.position.copy(location(f.lat,f.lon,2.16));this.selection.quaternion.setFromUnitVectors(new THREE.Vector3(0,0,1),this.selection.position.clone().normalize());this.drawMap();}
 setLayer(layer){this.layer=layer;this.drawMap();}
 zoom(direction){const v=this.camera.position.clone().normalize();this.camera.position.addScaledVector(v,direction*.7);this.camera.position.setLength(clamp(this.camera.position.length(),this.controls.minDistance,this.controls.maxDistance));this.focusTarget=null;}
 rotate(x,y=0){const s=new THREE.Spherical().setFromVector3(this.camera.position);s.theta+=x;s.phi=clamp(s.phi+y,.2,Math.PI-.2);this.camera.position.setFromSpherical(s);this.focusTarget=null;}
 update(game,selected,titleMode=false){this.game=game;this.reduced=game?.s.settings.reducedMotion||false;this.titleMode=titleMode;this.controls.autoRotate=titleMode&&!this.reduced;const mapKey=[selected,this.layer,Math.floor(game.s.day/90),game.s.treaties.filter(t=>t.active).length,game.s.fronts.length].join(':');if(mapKey!==this.lastMapKey){this.selected=selected;this.drawMap();this.lastMapKey=mapKey;}
  const key=[game.s.bases.map(b=>b.id).join(','),game.s.jobs.filter(j=>j.kind==='op').map(j=>j.id).join(','),game.s.agents.map(a=>a.id+':'+a.phase).join(',')].join('|');if(key!==this.lastAssets){this.refreshAssets();this.lastAssets=key;}}
 clearGroup(group){for(const o of [...group.children]){group.remove(o);o.traverse?.(n=>{n.geometry?.dispose();if(Array.isArray(n.material))n.material.forEach(m=>m.dispose());else n.material?.dispose();});}}
 refreshAssets(){this.clearGroup(this.assets);this.labels.innerHTML='';this.labelNodes=[];this.moving=[];if(!this.game)return;const s=this.game.s;
  for(const b of s.bases){const p=location(b.lat,b.lon,b.type==='orbital'?2.63:2.19);const pin=new THREE.Group();const ring=new THREE.Mesh(new THREE.TorusGeometry(.055,.011,6,24),new THREE.MeshBasicMaterial({color:b.search>60?'#e8917a':'#fff2c8'}));pin.add(ring);sphere(pin,.035,b.search>60?'#e8917a':'#8fd4b2',[0,0,.016]);pin.position.copy(p);pin.quaternion.setFromUnitVectors(new THREE.Vector3(0,0,1),p.clone().normalize());this.assets.add(pin);
   const label=document.createElement('button');label.className='base-map-label';label.textContent=b.type==='ocean'?'Pelagic node':b.type==='lunar'?'Lunar relay':b.name;label.addEventListener('click',e=>{e.stopPropagation();this.onBase(b.id);});this.labels.appendChild(label);this.labelNodes.push({el:label,pos:p});}
  for(const j of s.jobs.filter(j=>j.kind==='op'&&j.asset)){const c=this.game.country(j.country),base=s.bases[0];if(!c||!base)continue;const start=location(base.lat,base.lon,1),end=location(c.lat,c.lon,1),points=[];
   for(let i=0;i<=52;i++){const t=i/52;let p=new THREE.Vector3().lerpVectors(start,end,t);if(p.lengthSq()<.001)p.set(0,1,0);p.normalize().multiplyScalar(2.18+Math.sin(Math.PI*t)*.35);points.push(p);}const curve=new THREE.CatmullRomCurve3(points);const line=new THREE.Line(new THREE.BufferGeometry().setFromPoints(points),new THREE.LineDashedMaterial({color:'#b8a0d7',transparent:true,opacity:.7,dashSize:.035,gapSize:.024}));line.computeLineDistances();this.assets.add(line);const ship=makeUFO(.52);this.assets.add(ship);this.moving.push({ship,curve,job:j});}
 }
 frame(time){requestAnimationFrame(this.frame);const t=time*.001;if(this.focusTarget){this.camera.position.lerp(this.focusTarget,.075);if(this.camera.position.distanceTo(this.focusTarget)<.008)this.focusTarget=null;}this.controls.update();
  if(!this.reduced){this.clouds.rotation.y=t*.004;const a=t*.12;this.hero.position.set(Math.cos(a)*2.8,Math.sin(a*.7)*.42+1.4,Math.sin(a)*2.55);this.hero.rotation.set(Math.sin(t*.8)*.055,-a+.8,Math.sin(t*.5)*.07);}else{this.hero.position.set(-2.45,1.1,1.5);}
  this.hero.visible=this.titleMode||this.moving.length<3;this.selection.visible=!!this.selected&&!this.titleMode;this.selection.scale.setScalar(this.reduced?1:1+Math.sin(t*2)*.08);
  for(const m of this.moving){const progress=this.game?clamp((this.game.s.day-m.job.start)/m.job.duration,0,1):0;m.ship.position.copy(m.curve.getPoint(progress));m.ship.position.addScaledVector(m.ship.position.clone().normalize(),this.reduced?0:Math.sin(t*2)*.018);m.ship.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),m.ship.position.clone().normalize());}
  this.camera.updateMatrixWorld();const camDir=this.camera.position.clone().normalize();const w=this.container.clientWidth,h=this.container.clientHeight;
  for(const l of this.labelNodes){const visible=l.pos.clone().normalize().dot(camDir)>.3&&!this.titleMode;const p=l.pos.clone().project(this.camera);l.el.style.display=visible?'block':'none';if(visible)l.el.style.transform=`translate(${(p.x*.5+.5)*w}px,${(-p.y*.5+.5)*h}px) translate(-50%,12px)`;}
  this.renderer.render(this.scene,this.camera);
 }
}
